### ISSUE TITLE
Design and implement basic components

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#101]
A high level task for creating the basic repeated building blocks that the web ui will use. Things like buttons, tables, citations, etc. See the current Figma sketch for the types of components we'll have:

![image](https://user-images.githubusercontent.com/8326331/133534992-187ec5de-5924-4792-b79e-d87ff66acac9.png)

**Comment by vincerubinetti** [comment]
Most basic components are implemented as of now. And since this issue is kind of vague, closing. Will just design and implement new components as they are needed.
