### ISSUE TITLE
Explore page figma design

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#108]
This will be the most difficult design task of the app. We will need a very good plan for this page before we start touching code for it. This is the "meat and potatoes".

To come up with the design, we will need all of our research gathered, distilled, and considered. Then we'll need to sit down and iterate on a design for a while, requiring the input of the more biology-experienced people on the team like Julie and Moni.

A sub task will be figuring out, with Kent probably, how to normalize the data from the backend better such that the frontend can display it more generically.

**Comment by vincerubinetti** [comment]
Done and signed off on by group circa Jan 2022.
