### ISSUE TITLE
Home page figma design

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#109]
Design home page in Figma sketch. In progress in current Figma sketch, and still needs work.

Barring changes from monarch-initiative/monarch-api#111 , the home page will include the content:
- big bold header with logo and title and simple nav menu options
- simple search box identical to what we end up with from monarch-initiative/monarch-api#108 , but maybe pared down a little
- a "what is" section. big info graphic that explains what monarch is (it's a knowledge graph and ecosystem), what cool features it has (fuzzy phenotype search), what cool stats it has (X genes, X diseases, etc), then link to help page for more info on architecture
- a "how to use" section. select graphics and workflows from monarch-initiative/monarch-api#110 
- a "who's using" section. a section where we link to and showcase other people using monarch and how they're using it (how we showcase this still tbd)

**Comment by vincerubinetti** [comment]
The general design described above is pretty set. We have monarch-initiative/monarch-api#110 for tracking the "how to" section, and monarch-initiative/monarch-api#131 for the "what is" section.
