### ISSUE TITLE
endpoint: datasets

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#11]
const url = `${biolink}/metadata/datasets`;
const { nodes, edges } = await request<_Datasets>(url);

**Comment by glass-ships** [comment]
This isn't actually in our dataset. 
Maybe this is from sources or something? 
Could use biolink model toolkit to look up infores stuff?

**Comment by vincerubinetti** [comment]
Is this still necessary? Our frontend doesn't use it anymore, as of #265 , we just link to your pre-generated docs. But maybe other people would still want the API endpoint?

**Comment by glass-ships** [comment]
ohhh that's what that meant. yeah sounds obsolete to me
