### ISSUE TITLE
Create short gif/video tutorials for how to do specific things on the website

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#110]
In general, the web app shouldn't need to be heavily documented. "A UI is like a joke: if you have to explain it, it's not that good". However, we'll still want some explanatory content to ease people into using the UI. We also can use these as advertisements/demos of what the app can do, to put on the home page, twitter, etc.

~How do we want to make the content? Are we using After Effects to create animations? Can we set up an automation that uses the actual Vue components to make a screen recording such that when the UI components change look/behavior we automatically get an updated recording? This would be really cool. Cypress is already set up and installed for end to end testing, and it has the ability to record videos, so maybe we can do this!~

To save time, let's just due manual screen recordings for now. We can explore automated recording or after-effects-ing up the recording later.

**Comment by vincerubinetti** [comment]
WIP list of video recordings to make:

- how to search for a gene and disease. show typing into search box and setting filters from dropdown.
- ???

**Comment by vincerubinetti** [comment]
Related (investigation of using cypress to automate the recordings):

https://github.com/cypress-io/cypress/discussions/22764

**Comment by vincerubinetti** [comment]
Record in 4:3 at highest resolution you can on your monitor. For me, I can do 1600 × 1200. Record at 60 fps.

Page preparation:

- Fullscreen browser so that page is as wide as screen and there are no OS UI shadows (e.g. MacOS dock shadow)
- Page zoom to 150%
- `$section` sass variable to `680px`
- `await sleep(300)` in appropriate places to force loading spinners 

Paste into console:

```javascript
// ignore scrollbar and center page perfectly
document.body.style.overflow = "overlay";
// hide sections as necessary
document
  .querySelectorAll("header, footer, main > section:nth-child(1)")
  .forEach((element) => (element.style.display = "none"));
// allow auto-typing something quickly into an input on command:
window.addEventListener("keydown", (event) => {
  if (event.key === "d" && event.ctrlKey) {
    const input = document.querySelector("input");
    "renal fanconi syndrome".split("").forEach((char, index) => {
      setTimeout(() => {
        input.value += char;
        input.dispatchEvent(new Event("input"));
      }, index * 20);
    });
  }
});
```

Using OBS studio:

- Display capture as source, and show cursor
- Set hotkeys for easy starting/stopping of recording, so no trimming/editing needed
- 1600x1200 as base/canvas resolution and output/scaled resolution
- 60 fps
- Transform for display capture:
  - Size: native resolution of your monitor (e.g. 3456 x 2234 for 16" M1 MacBook Pro)
  - Bounding box type: scale to width of bounds
  - Alignment in bounding box: top center
  - Bounding box size: 1600x1200
  - Crop tightly to page content of interest
- Output mode advanced, recording:
  - Format: mp4
  - Bitrate: 10000 Kbps

**Comment by vincerubinetti** [comment]
I experimented using [nut.js](https://github.com/nut-tree/nut.js) (a better alternative to robot.js). The approach of automating the mouse movements and keyboard events seems like too much effort and too brittle for not enough benefit. But here's my code for posterity:

<details><summary>code</summary>

```javascript
const {
  keyboard,
  mouse,
  Button,
  Point,
  left,
  right,
} = require("@nut-tree/nut-js");

keyboard.config.autoDelayMs = 20;

const sleep = (ms = 0) => new Promise((resolve) => setTimeout(resolve, ms));

const pause = () => sleep(500);

const smooth = (t) => 1 - Math.pow(1 - t, 4);

const interpolate = (a, b, t) => a + (b - a) * t;

const move = async (x, y) => {
  const m = await mouse.getPosition();
  const points = Array(500)
    .fill(0)
    .map((_, index, array) => smooth(index / array.length))
    .map((t) => ({
      x: interpolate(m.x, x, t),
      y: interpolate(m.y, y, t),
    }));

  for (const { x, y } of points) {
    await sleep(2);
    await mouse.setPosition(new Point(x, y));
  }

  await pause();
};

const click = async () => {
  await mouse.click(Button.LEFT);
  await pause();
};

const type = async (string) => {
  await keyboard.type(string);
  await pause();
};

const setup = async (x, y) => {
  await sleep(3000);
  await move(x, y);
  await mouse.move(left(100));
  await mouse.move(right(100));
  await sleep(1000);
};

const nodeSearch = async () => {
  await setup(600, 340);
  await move(800, 215);
  await click();
  await type("renal fanconi syndrome");
  await move(800, 265);
  await click();
  await move(600, 340);
};

nodeSearch();
```
</details>

**Comment by vincerubinetti** [comment]
Remotion is a react library that might match the auto-creation needs described here. Look into whether there is a Vue equivalent.
