### ISSUE TITLE
Decide on support structure and define contact methods

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#112]
Decide on support structure going forward, and which services to use for what.

Vince recommends consolidating all the various contact methods as much as possible, and focusing on GitHub as the single source of truth and single destination:

- deprecate google groups, the "help desk", the "mailing list", the gitter forum, etc. replace with just GitHub discussions.
- use issues for specific feature requests and bugs reports, if the user can manage it
- general feedback form directly on the app that somehow funnels into one of the above two
- use email as a last resort, for general inquiries (media inquiries?) and miscellaneous, or for users who really don't want to sign up for a github account

**Comment by monicacecilia** [comment]
Google Groups: would deprecate only 'Monarch-Friends.' Other Google Groups remain.

**Comment by vincerubinetti** [comment]
What we landed on:

- `help-desk` captures feature requests, bug reports, and any other kind of user conversations. knowledgeable monarch people then funnel issues to the appropriate repo.
- the 3.0 website has a feedback form that serves as a one-way help desk. it simply is a way to post an issue on the help desk right from the website (with extra metadata), without needing a github account
- email used as last resort, and for general/misc requests (like media)
- everything else should be ignored/deprecated
