### ISSUE TITLE
Gather data from google analytics 

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#114]
Examine Google Analytics data (on Monarch 2.0 website) in depth and see if there are any insights to glean from it that will improve the new app vs the old, whether it be related to bugs, user behavior, navigation, bounce rate, etc.

**Comment by putmantime** [comment]
**Identify metrics that we want to see improved.**

Identify how often people go deeper into the app from a node page.  
Identify dead ends.
  - 
How much time, how many pages they go to
How many times does a user link out to a publication

**Comment by kevinschaper** [comment]
The format I used for the event actions was "[nodeType] node, [cardType] card, [action]"

For example: 

gene node, phenotype card, expand card
disease node, causal gene card, open publication

The event categories are more broad, not using any values from the page: 
* "node page expand card"
* "node page association table expand support"
* "node association table evidence open publication"

Hopefully this gets us an idea on the current UI of where folks are drilling down and eventually choosing to look at a publication

PR: https://github.com/monarch-initiative/monarch-ui/pull/471

**Comment by vincerubinetti** [comment]
For posterity: I don't believe this revealed all that much useful information, especially compared to the user interviews. That is why it was closed.
