### ISSUE TITLE
Gather old user research

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#115]
- [x] locate any old conference research where user testing was conducted
- [x] @jmcmurry document any old user research that you remember

**Comment by jmcmurry** [comment]
overview is [here](https://docs.google.com/document/d/1L71pMHCQdJV2LqKTd2JhxSqy8E4Q62tq-RJCt7Dvhok/edit); I wasn't able to find anything else. There was also a very odd biocuration survey done [here](https://docs.google.com/spreadsheets/d/1P0CE80msPXI7YY_3jFkQS3HjM5P3XcPrgStTE8SXShk/edit#gid=0) not by me. 

Notes from one interview are [here](https://docs.google.com/document/d/1zCe0ITnQb8UV5iuXagWKwckX8yw4l8cHV0hP1OSJyv4/edit) and [here](https://docs.google.com/document/d/1gbkXBarJyZCoMGrNcey-_PMLu7zsGby7MIjPz4UQYuQ/edit)

See also [here](https://docs.google.com/document/d/1thYtPn419olYVk_mQfItAbLlM7FUgcy_bzsoELnBq0Q/edit) for a plan we put together for Helmsley FDN.

As this is unfortunately all that exists that I'm aware of, I'd like to close the ticket.
