### ISSUE TITLE
What to do about messy `xrefs` code

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#118]
2.0 UI has a [giant block of code](https://github.com/monarch-initiative/monarch-ui/blob/e3e5b8ee9d22fab211bb2ba91d6ee2054a34a659/src/views/Node.vue#L850-L961) for determining the "external resources" section of the node page. I am unable to decipher the code. 

This code also seems to rely on the results from `getNeighborhood`. So in total, the amount of code it takes just to get links to external references (from just ids i think?) is incredibly high.

Related to monarch-initiative/monarch-api#119 , we need to go through each line and figure out how to make it readable and more simple.

**Comment by vincerubinetti** [comment]
To add to this, there's these pieces of code:

https://github.com/monarch-initiative/monarch-ui/blob/e3e5b8ee9d22fab211bb2ba91d6ee2054a34a659/src/lib/conf/xrefs.js
https://github.com/monarch-initiative/monarch-ui/blob/e3e5b8ee9d22fab211bb2ba91d6ee2054a34a659/src/lib/utils.js#L66-L78

It'd be great if we could simplify and clarify this mapping. Right now it's a map of maps... should probably just be one level of map if possible.

**Comment by putmantime** [comment]
Addressed by https://github.com/monarch-initiative/monarch-api/issues/14
