### ISSUE TITLE
What to do about messy `getNeighborhood` code

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#119]
2.0 has a [giant block of code](https://github.com/monarch-initiative/monarch-ui/blob/b0ce0d4a359e51e2b1f578c587ed2e84d9e4482e/src/api/bio-link.js#L157-L316) used to get the super/equivalent/sub-classes for the node "neighborhood". For some reason, that's also where `xrefs` and `synonyms` for a node seem to come from.

A general question. What do we do about this. Even a comment in the 2.0 code says that it is a mess. We need to go through even line of that and see whether it is still necessary, or if there is a better way to do it. E.g. are [these lines](https://github.com/monarch-initiative/monarch-ui/blob/b0ce0d4a359e51e2b1f578c587ed2e84d9e4482e/src/api/bio-link.js#L138-L153) necessary? Why do we have hardcoded exceptions for a handful of nodes?

The `/bioentity/{id}` endpoint already returns `xrefs` and `synonyms` fields that I've so far been using for the info on the node page.

**Comment by putmantime** [comment]
Addressed by https://github.com/monarch-initiative/monarch-api/issues/14
