### ISSUE TITLE
What to do with `/sim/compare` results that are `+` separated lists?

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#122]
This issue originates from [this comment](https://github.com/monarch-initiative/monarch-ui-new/pull/83#discussion_r830142264) in monarch-initiative/monarch-ui-new#83 .

Take these example sets of phenotypes to compare: `HP:0004970,HP:0004933,HP:0004927` vs `HP:0004872,HP:0012499,HP:0002650`. The `/sim/compare` endpoint returns a single match with an id of `HP:0004872 + HP:0012499 + HP:0002650`. Am I supposed to split this match into separate matches based on those `+`'s?  What does this list represent, a "variant combination" as @falquaddoomi wonders? Does it behave as a single entity?

Or, is this a result of the `POST` `/sim/compare` endpoint being able to accept *multiple sets* of phenotypes to compare, and that's why there is only one match, and the `+`'s are supposed to separate individual phenotype matches within the set?

The 2.0 UI doesn't seem to do any splitting of the `+` list. Instead, it seems to (incorrectly) provide each phenotype in the second set as its own set (see https://github.com/biolink/biolink-api/issues/389#issuecomment-1067470880)

**Comment by putmantime** [comment]
It is the latter.  I can not speak to the reason behind the '+' delimited id and label, but when providing multiple profiles that is how the different matches are differentiated.

`sim_payload = {
  "reference_ids": [
      "HP:0004970",
      "HP:0004933",
      "HP:0004927"
  ],
  "query_ids": [
    [
        "HP:0004872",
        "HP:0012499",
        "HP:0002650"
    ],
      [
        "HP:0004871",
        "HP:0012500",
        "HP:0002650"
    ]
  ]
}`

Returns a match for each with 'id': 'HP:0004871 + HP:0012500 + HP:0002650', and 'id': 'HP:0004872 + HP:0012499 + HP:0002650'

So that is the id for the matching set.
Does that answer the question?

**Comment by vincerubinetti** [comment]
That partially answers the question. The root question though is what to do with the results, then. Here's what it looks like right now:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/8326331/159960301-3abc848c-a2fd-4bb9-a861-ff7a08d4f582.png">

---

Note the link to [HP:0004872 + HP:0012499 + HP:0002650](https://monarch-ui-new.monarchinitiative.org/unknown/HP:0004872%20+%20HP:0012499%20+%20HP:0002650)

Naturally, that is not a valid node page. So should I just split them by `+` and link to their separate node pages? Should I split them by `+` into entirely separate rows, with the (66) similarity score in each row?  Is that even useful information then, if they all have the same similarity score?

**Comment by putmantime** [comment]
@jmcmurry could you please have a look and give some advice on this issue and what the first iteration should do?

**Comment by jmcmurry** [comment]
It is possible I don't understand the question. Lemme try.

Each input phenotype in the first set should be its own row (ideally regardless of whether or not it is matched).
As for what to do with the custom set of comparators, we could take one of two approaches
A) break those out into a separate column for each phenotype
B) have the label show up as "custom phenotype set"

B seems like the easiest path to victory as it is most consistent with the bucket behavior we currently have. 

I don't know whether owlsim supports multiple groups of phenotypes as comparators, but if so, B is the only option. The corresponding input would need to support this too though.

As for having them link to a node page (if that is in question), the most straightforward would be to turn the linking off as it is not meaningful to have a node page for custom phenotypes.

As a general rule, my personal preference would be to default NOT hide any unmatched phenotypes unless there are too many to display. They should go on the bottom of course so as not to obscure relevant data.

Hope this helps? Let me know where I may not be quite addressing the question.

**Comment by jmcmurry** [comment]
as for the pairwise comparisons that owlsim supports, the better visualization for this would be the triptych, but that's a whole other conversation. Let's stick with B and unlinked comparators with generic labels. Comparison group 1, 2, etc.

**Comment by vincerubinetti** [comment]
If I'm interpreting your reply correctly, it sounds like you're talking about phenogrid. I'm talking just about the `top 10 matches` section above it, which is analogous to the "Source data for each match result" table in 2.0.

>  don't know whether owlsim supports multiple groups of phenotypes as comparators

Are you referring to this API endpoint?

<img width="557" alt="image" src="https://user-images.githubusercontent.com/8326331/160008222-1d79533c-ff72-4eeb-905d-4c566a665c48.png">

> The corresponding input would need to support this too though.

Why? Do you mean it the endpoint would need to be able to do multiple phenotype sets vs. multiple phenotype sets?

> it is not meaningful to have a node page for custom phenotypes.

I don't know what you mean by custom phenotypes. They're all just phenotype ids being passed to the API for comparison. Whether they're phenotypes that the user searched for and selected, or that they pasted from somewhere else, or that they got from associated genes/diseases...

> Let's stick with B and unlinked comparators with generic labels. Comparison group 1, 2, etc.

If we're going to say this, there will only ever be 1 row of results under `top 10 matches`. A row that says "phenotype group B" (or "comparison group 1" as you phrased it), along with its similarity score. Unless you intend the UI to be able to have multiple comparison groups.

Please take a look at this issue: https://github.com/biolink/biolink-api/issues/389#issuecomment-1067470880

It seemed to me that the 2.0 UI was doing things incorrectly, and splitting the comparison phenotypes into separate sets of one phenotype each. Is that actually what we want? If so, we need to convey that in the UI somehow... that the first list of phenotypes you input is one set all together, and the second list you input is split up into multiple sets...

---

Overall this raises more questions than it answers. I think we need to talk about it in person.

**Comment by jmcmurry** [comment]
Agreed we should meet. In meantime, correct, I was only referring to phenogrid representation given an input of two custom bags of phenotypes; I can't speak authoritatively to owlsim behavior in the back end
My guess is both use cases (whole bag of phenotypes and breaking out the bag into atomic phenoptes) probably need to be supported, so I would maybe suggest parameterizing and documenting this better
The latter might be needed for triptych viz, for example

**Comment by vincerubinetti** [comment]
Okay that sounds good.

Reminder that only the "atomic" use case is possible in 2.0 and this wasn't in our 3.0 feature-parity plan. But I think I should be able to make a quick modification that makes both of those use cases possible. I'd add a fourth option to the gray dropdown you see in the screenshot:

- these phenotypes (as a set)...
- these phenotypes (individually)...
- all genes of taxon...
- all human diseases

Does that sound relatively self explanatory? (We can add more detailed explanation in a tooltip).

Also, now that I'm a little more clear, it sounds like just splitting the `+` and linking to each phenotype's node page separately can't really hurt. We could still have "Comparison phenotype set" on top of that.

**Comment by jmcmurry** [comment]
for phenogrid, there's not much to be gained by "these phenotypes (individually)..." but I don't object to it either. It would just be a much more sparse matrix and would force phenogrid to show all of the phenotypes whether matched or not

Owlsim should continue to support both, however because of the eventual different visualizations we've designed (for another day)

**Comment by vincerubinetti** [comment]
> My guess is both use cases (whole bag of phenotypes and breaking out the bag into atomic phenoptes) probably need to be supported

Okay you mean just the backend/API needs to support them, not necessarily the web app (at least on the above-screenshotted "phenotype explorer" page).

> there's not much to be gained by "these phenotypes (individually)...". It would just be a much more sparse matrix

Okay just to reiterate, that's what UI 2.0 does now. It sounds like you're confirming what I thought in https://github.com/biolink/biolink-api/issues/389, which is that it was a mistake.

**Comment by jmcmurry** [comment]
1) correct, both use cases for backend, but the bag-only (not broken out) for the UI
2) biolink makes sense from back end, but UI 2.0 probably doesn't make sense. It isn't wrong, but it is weird.

**Comment by vincerubinetti** [comment]
Okay I ended up doing this and I don't see anything wrong with it so going to close.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/8326331/160900282-76daa8e0-01e6-4ce6-9daf-c3aa2f35b34d.png">

**Comment by vincerubinetti** [comment]
Just future note to self, make sure the lines cutoff after one line.
