### ISSUE TITLE
Do the node search filters work the way we want them to

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#124]
I can foresee people complaining about this. The way I currently have this implemented is like this:

![image](https://user-images.githubusercontent.com/8326331/158646175-4f1a8a1e-1450-4c45-b603-4d070a40670e.png)

Where arrows are things that can change other things.

In the 2.0 UI, there would also be a two way arrow between the filter boxes. That is, if you selected a particular category to filter by, that would also update the available options and facet counts in the taxon filter box.

I did things in a more linear way to drastically simplify the code, and I also found it to be a little bit more intuitive, except for one detail:

Try searching "microcephaly", and selecting "phenotype" from the category filter. The options under the taxon filter will remain exactly the same, *along with their counts*. However, if you actually then also filter by a taxon, you'll find no matches (because the backend returns no match for "microcephaly" and "type=phenotype". Thus, the count numbers basically end up saying, this is how many results you'll get with the "microcephaly" search string, and *no other filters enabled*.

I'm not sure we even want to "fix" this. The 2.0 way comes with limitations, like only being able to select one category/taxon at a time. But if we do, I need to be able to wrap my head around the compounding effects of the filters. Because, selecting a taxon will affect the available categories, which can affect the available taxons, leading to an infinite loop. In fact, the category filter can even [change itself](https://api.monarchinitiative.org/api/search/entity/microcephaly?boost_q=category%3Adisease%5E5&boost_q=category%3Aphenotype%5E5&boost_q=category%3Agene%5E0&boost_q=category%3Agenotype%5E-10&boost_q=category%3Avariant%5E-35&category=phenotype&min_match=67%25&prefix=-OMIA&rows=10&start=0).

Perhaps the count number is the only true problem and potential for confusion here, and perhaps I could do a "half-solution" that just updates count numbers but not the list of options itself. Or an even simpler and dumb solution would be to just hide the count numbers if any filters are active.

---

If you look at something like google fonts, you see that when you select an option in one filter, they don't update the list of options in another filter. The options are static.

I.e., selecting the "display" type most likely eliminates results from certain languages, but all languages still appear in the language dropdown.

Another good example would be Amazon. When you select one filter option, the options for other filters don't seem to change.

**Comment by putmantime** [comment]
@jmcmurry Could you provide some opinions on this?

**Comment by jmcmurry** [comment]
> "perhaps I could do a "half-solution" that just updates count numbers but not the list of options itself. Or an even simpler and dumb solution would be to just hide the count numbers if any filters are active"

Either of these solutions is ok with me, whatever is easier. This isn't something I think it is worth investing a lot in.
