### ISSUE TITLE
Gather phenotype explorer examples

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#126]
We have examples for the "Node Search" and "Text Annotator" explore modes; we should also have examples for the "Phenotype Explorer" mode.

At the moment, I just picked a few random phenotypes:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/8326331/157688466-35499726-f8e4-4ce6-a538-1147fb08ff04.png">

But they don't seem to return meaningful comparison results.

It'd be nice to have someone actually knowledgeable hand pick some phenotypes that will produce interesting results.

It'd also be nice to have 3 examples: 1) phenotype set vs. phenotype set, 2) phenotype set vs genes of taxon, 3) phenotype set vs human diseases.

**Comment by vincerubinetti** [comment]
@jmcmurry Maybe you could help out with this one?

**Comment by putmantime** [comment]
Group A Plod1 RGD:621382
Group B Ssh3 MGI:2683546
