### ISSUE TITLE
Clarify node category mapping

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#130]
This issue comes from monarch-initiative/monarch-ui-new#74. In that PR I made a sort of vague plea of helplessness regarding what to do about category mapping. It's all very nebulous and muddy to me, and what I ultimately sort of need is someone to tell me exactly how they want to implement each thing. This issue attempts to clarify my questions so someone can help.

---

First, here are the relevant code in UI 2.0 that I'll be referencing:

https://github.com/monarch-initiative/monarch-ui/blob/master/src/lib/category-map.js
https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/bio-link.js#L318
https://github.com/monarch-initiative/monarch-ui/blob/master/src/views/Node.vue#L412
https://github.com/monarch-initiative/monarch-ui/blob/master/src/views/Search.vue#L257

---

- Why does BioLink return category as an array of strings instead of one string? Is the first entry the main category and the others are some kind of sub categories? Or is it that a node can be in multiple categories at once?
- In `category-map.js`, it looks like we prioritize "gene", then "variant", if they appear anywhere in the array of categories. Why is this?
- What type of categories does the BioLink search endpoint support? I would assume that hopefully it takes categories in the same way that it outputs them. If so, the mapping in `category-map.js` would have to be reversed before using the category to filter search results, and I don't see that being done anywhere in the 2.0 code. Is that mapping a sort of intentional, permanent conversion of the category?
- In `category-map`, multiple input values can map to the same output values, meaning that we lose information. Do I need to keep the original, "raw" category on the node for use later, like querying back to BioLink?
- If BioLink outputs categories as an array, what do we use to input those back into BioLink... just the first entry? All of them?
- Why is this mapping in `category-map` necessary at all? Is it to convert the category to a "supported" category, i.e. one that we have a custom Node page layout for?
- There are 3-4 arrays/lists scattered throughout the 2.0 code of category types, and they're all slightly different. Put simply, what the hell is going on here. It would be really great if there was just **a consistent, normalized `category` field** that a node had, and a **well defined list of values it could possibly be**, and that **single list** of values would also correspond to the different category icons, category node pages, category faceting, etc.
- If we are mapping categories, then how do we handle category facet and facet count? The answer may be in the `Search.vue` code linked above, but all of this code is just too uncommented and ad hoc (I'm sorry to the authors) for me to make sense of. Do I simply delete the category facets that don't map to anything? Since multiple input categories can map to the same output, do I detect that and combine their counts? There are a lot of questions here that can lead to issues like the facet counts not adding up to the total results, or the wrong categories being searched for. I really need clarity of what to do here.

--- 

For now, what I'm going to do is simply ignore the mapping all together, and just take the first entry. This way should at least be consistent.

The best solution might be to just "play dumb" at the start, and let people point out issues, e.g. "this specific category should really be displayed as if it were a variant".

**Comment by vincerubinetti** [comment]
Here is yet another category mapping block of code, again slightly different and only used in one instance:

https://github.com/monarch-initiative/monarch-ui/blob/b0ce0d4a359e51e2b1f578c587ed2e84d9e4482e/src/api/bio-link.js#L492-L512

**Comment by putmantime** [comment]
@cmungall or @jmcmurry 
Can you comment on the logic behind categories?
Do we need this complicated of logic around mapping multiple categories etc?

**Comment by jmcmurry** [comment]
Hmm; can you give an example of an entity that would be mapped to more than one category? I would expect cats to be disjoint.

I don't think 1-to-many is something I requested?

maybe this is not your question?

**Comment by vincerubinetti** [comment]
Here is one. I can probably find many more if you want.

https://api.monarchinitiative.org/api/bioentity/FlyBase:FBgn0029157

**Comment by jmcmurry** [comment]
I defer to @putmantime  on this one; sequence feature is just a sub-category of gene. It isn't a separate category.
There are also cases where text is an exact match to more than one category ('anemia' can be both a phenotype and a disease)

**Comment by vincerubinetti** [comment]
Here's an example of inconsistent category names necessitating hard coded maps:

https://api.monarchinitiative.org/api/bioentity/UBERON%3A0003101?rows=100&facet=false&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false

returns the category as "anatomical entity", but the `/bioentity/{type}/{id}` needs `anatomy` as the type. Also sometimes the term "type" is used and sometimes "category". Are they interchangeable? Are they different?

**Comment by jmcmurry** [comment]
Oof sorry; I don't know the answer to whether type and category are interchangeable. It is possible that anatomy is materialized as an attribute (eg. for example on genes expressed in certain tissues). @putmantime ?

**Comment by vincerubinetti** [comment]
For posterity:

<details><summary>code</summary>

```typescript

// this is a simplified (but hopefully equivalent) port of the code in:
// https://github.com/monarch-initiative/monarch-ui/blob/master/src/lib/category-map.js

// manually map category parts
const map: Record<string, Category> = {
  gene: "gene",
  variant: "variant",
  "sequence feature": "variant",
  genotype: "genotype",
  phenotype: "phenotype",
  disease: "disease",
  pathway: "pathway",
  "anatomical entity": "anatomy",
  publication: "publication",
  case: "case",
  "cell line": "model",
  organism: "model",
};

// turn category (array of category "parts") into single, supported category string
export const mapCategory = (category: Array<string>): Category => {
  // map category parts based on manual map
  const mappedCategory = [...new Set(category.map((part) => map[part]))];

  // prioritize genes and variants if matched
  if (mappedCategory.includes("gene")) return "gene";
  if (mappedCategory.includes("variant")) return "variant";

  // otherwise just return map of first category part
  return mappedCategory[0] || "unknown";
};

type Category = typeof categories[number];
```

</details>

My attempt at simplifying the 2.0 code in question. The above code was sitting in 3.0 commented out, and I wanted to cut off the loose end but I didn't want to lose it completely.

**Comment by vincerubinetti** [comment]
With the new Monarch API, categories are a single value in the form of e.g. biolink:PhenotypicFeature, and it has been working well so far. It can be passed back to the backend successfully, and easily converted to a more human readable name consistently on the frontend. I consider this sufficiently answered.
