### ISSUE TITLE
Make home page infographic

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#131]
On the homepage, below the logo and search box, we want an infographic/graphic of sorts. In my opinion, the goals of this graphic are:

- To be visually grabbing
- To convey what Monarch is at glance (it's a cross-species knowledge graph with an ecosystem of analytical tools around it)
- To convey ideas with visuals and minimal text, without being too dense (this has to work well on mobile screens)

Perhaps the interactive visualization on https://tislab.org/ is the right level of "busy-ness". For more text/number details we want to show/advertise, like usage numbers, node counts, etc, we'll have those underneath the graphic as shown in the Figma sketch below.

Maybe this is a diagram/infographic of a pseudo-graph. Maybe it has a few nodes like disease/gene/phenotype, each with different species icons next to them. Maybe we could have no text at all, but have several hover-able points of interest that show some explainer text in a tooltip.

Figma sketch:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/8326331/155213762-ccf01bc5-2972-4c09-b255-166b2089f27d.png">

**Comment by vincerubinetti** [comment]
While waiting to figure out what the infographic should be, I think I'll just include the node counts and high level features. That is, the things from the screenshot above besides the gray rectangle.

I may be able to get the counts programmatically from this source (or we can just hard code it for now):

https://storage.googleapis.com/monarch-ingest/latest/qc_report.yaml

For the features, I'm thinking:

- Extensive cross-species knowledge graph
- One-of-a-kind fuzzy phenotype search
- Powerful suite of tools for programmatic analysis

If you have thoughts on this, please let me know.

**Comment by jmcmurry** [comment]
It is fine to repurpose the tislab overview as this is pretty spot on already and -- bonus -- done.

**Comment by vincerubinetti** [comment]
Which visual are referring to @jmcmurry ?

---

Actually, the more I think about this, maybe we just want the high level features... just a few "features", each with an icon and a very short ~10 word description. Just an elevator pitch, sort of.

If someone could think of how to combine all of them into a single infographic (in a way that actually adds value) that's great. But I can't think of a way. So for now I think I'll just do the features.
