### ISSUE TITLE
Make diagram of monarch infrastructure

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#132]
Create an architecture overview diagram. A clean graph of all of the various services and datasources involved in the entire Monarch ecosystem in one chart.

The website monarchinitiative.org should be a hub where everything about monarch can be reached. That is, it doesn't have to contain every scrap of information about all parts of the monarch ecosystem, but all information about all parts of the monarch ecosystem should be _reachable_ using the website as a single starting point.

To that end, [the overview page](https://monarch-ui-new.monarchinitiative.org/overview) should now have a network/graph/flowchart graphic of the monarch ecosystem/"architecture", including owlsim, exomiser, lyrical, biolink, phenogrid, etc. Not just the pipeline stuff, but peripheral tools and packages as well. Basically, every piece of **software** that is related to monarch. But NOT including the data-sources/ontologies, which are already captured on the sources page. And NOT the tools that will be built into the website as features, like phenotype profile search and text annotator.

@putmantime is probably the ones to construct this diagram. You can sketch it out however you want (pen and paper, lucidchart, whatever), and ~I'll~ Julie will make it pretty.

We can have each item be hoverable and link to its respective repository, license info, docs, etc. Please provide those too. If that info is missing for an item, it should probably exist eventually (let's make an issue).

**Comment by vincerubinetti** [comment]
Basically we need a more detailed and updated version (and a fresh coat of paint on) this diagram:

![image](https://user-images.githubusercontent.com/8326331/160903489-351e5ec6-6855-4858-8b55-7c02b3d4cb38.png)

**Comment by vincerubinetti** [comment]
Also assigning this to Julie for design/aesthetic purposes.

**Comment by jmcmurry** [comment]
This isn't ready for my input. I need more detail from @putmantime but Tim, feel free to print it and just red pen it and scan it. When you're done, please re-assign

**Comment by vincerubinetti** [comment]
At the moment, tislab is in the process of redesigning/reworking the whole pipeline and api. As such, maybe we should just wait on this diagram, because it will all change (hopefully) soon.

For now, I can just use the existing diagram above. And people can use google to find each piece's associated github repo and docs and etc.
