### ISSUE TITLE
Remove `dc` and `foaf` from ontology list on about page

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#133]
There are four ontologies -- prefixed `dc`, `faldo`, `foaf`, `oban`  -- [that 2.0 lists in the code](https://github.com/monarch-initiative/monarch-ui/blob/e3e5b8ee9d22fab211bb2ba91d6ee2054a34a659/src/views/Licensing.vue#L111-L143), but do not render because they're not part of the [obo foundry's list of ontologies](https://obofoundry.org/registry/ontologies.jsonld).

According to Tim, `oban` and `faldo` probably will no longer be part of the graph very soon. So that just leaves `dc` and `foaf`.

There may be an API to get metadata for these two like we're doing with all the rest via OBO, but if it's just 2 entries... I'd rather just enter that info manually (unless it's likely to change frequently).

Someone with the knowledge, please type in [metadata](https://github.com/monarch-initiative/monarch-ui-new/blob/main/src/types/sources.ts) in `/src/api/ontologies.json` like:

```json
{
  "id": "foaf",
  "name": "Firebird Ontology Anatomy Fish",
  "description": "blah blah blah"
},
```

**Comment by vincerubinetti** [comment]
Here are the fields the frontend accepts. Fill out as many as you can or are relevant. You can just type them here in the issue if you want.

```json
  {
    "id": "MonarchArchive:#mgi",
    "name": "Mouse Genome Informatics",
    "image": "mgi.png",
    "description": "MGI is the international database resource for the laboratory mouse, providing integrated genetic, genomic, and biological data to facilitate the study of human health and disease.",
    "usage": "We list genotype-phenotype associations and asserted disease-models. We use MGI identifiers as the main hook into mouse data. Additionally, we utilize the Mouse Phenotype Ontology (MP) in our cross-species ontology, to link all mouse phenotype annotations from various sources, which is developed by MGI.",
    "vocabulary": "ECO, MA, MP, SO",
    "license": "http://reusabledata.org/mgi.html"
  },
```

**Comment by vincerubinetti** [comment]
@kevinschaper Maybe you could help out with this one?

**Comment by falquaddoomi** [comment]
I'm pretty sure that `foaf` is the ["Friend of a friend ontology"](https://en.wikipedia.org/wiki/FOAF_(ontology)); there's a logo and other metadata on that wiki page that I linked. Similarly, `dc` is likely ["Dublin Core"](https://en.wikipedia.org/wiki/Dublin_Core), an ontology for describing information resources, i.e. books, videos, etc. The project homepage is https://www.dublincore.org/.

**Comment by kevinschaper** [comment]
They do feel a little harder to match up to the metadata

**Comment by vincerubinetti** [comment]
@falquaddoomi Thank you, I should be able to get `name` `image` and `description` from those links. 

@putmantime I will still need someone to tell me `usage` and `vocabulary`.

**Comment by kevinschaper** [comment]
@matentzn Do you know what the usage is for dc and foaf? I feel like maybe they're both something related to something like provenance/metadata, but I'm not really sure.

**Comment by matentzn** [comment]
Dc is mostly (but not exclusively) used for: term attribution (dc:creator, dc:contributor), dates and licenses. Very important namespace for general metadata. FOAF, contrary to the primary purpose of the vocabulary, is used for a few select elements of ontology-level metadata (website/hompage) and images related to terms. 

Both are important vocabs, but please do not import dc or foaf as "ontologies". They are not. We have our own way to deal with dc and foaf properties in PHENIO by importing OMO (the obo metadata ontology) which has all relevant foaf and dc properties in it. You should still deal with the prefixes in your context file.

**Comment by vincerubinetti** [comment]
After talking with Tim, this is my understanding (please excuse any inaccuracies and refer to Tim, because I am not a biologist):

These two ontologies are *not* being used *directly*. They were listed because they are subsets/sub-parts of OBO, which we are using directly. As such, Tim believes there's no reason to even have these two in the list at all. 

~Changing this issue to be "remove the entries".~ Apparently I had never added the above-mentioned 4 ontologies to the list in the first place, maybe because I didn't have the details.

**Comment by matentzn** [comment]
Yeah this sounds correct, but dont call them ontologies, better refer to them as controlled vocabularies. :D Sorry man don't want to be annoying.
