### ISSUE TITLE
endpoint: node-publication

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#16]
const params = { db: "pubmed", retmode: "json", id: ids.join(",") };
  const url = `${entrez}/esummary.fcgi`;
  const { result } = await request<_Summary>(url, params);

--

  const params = { db: "pubmed", retmode: "text", rettype: "abstract", id };
  const url = `${entrez}/efetch.fcgi`;
  return await request<string>(url, params, {}, "text");

**Comment by kevinschaper** [comment]
Since this doesn't call biolink api, I don't think we have any changes to make
