### ISSUE TITLE
Pull in real metadata for homepage

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#167]
The frontend homepage currently just has dummy numbers for # of genes/diseases/etc. Let's add real numbers. Probably don't need a new API endpoint yet, can probably just read from YAML metadata dump.

**Comment by kevinschaper** [comment]
We could get this from either the kgx or monarch-qc yaml, but only if we can package them up in some way that the running api will know where to get them - or we could potentially supply this from solr. Probably we should start out by making an endpoint that supplies the necessary data and then we have flexibility about where it comes from

**Comment by glass-ships** [comment]
Could implement this in #265 after adding a related endpoint

**Comment by kevinschaper** [comment]
This could actually just come from the category facet field on the search endpoint (example below). I've had trouble in the past with home pages making a call to the api, so if we did this, we'd want it to fail very gently if somebody views the home page while the api is restarting/etc. 

```
  "facet_fields": [
    {
      "label": "category",
      "facet_values": [
        {
          "label": "biolink:Gene",
          "count": 514018
        },
        {
          "label": "biolink:PhenotypicQuality",
          "count": 89431
        },
        {
          "label": "biolink:Disease",
          "count": 26469
        },
        {
          "label": "biolink:Pathway",
          "count": 22248
        },
        {
          "label": "biolink:AnatomicalEntity",
          "count": 20954
        },
        {
          "label": "biolink:GrossAnatomicalStructure",
          "count": 10327
        },
        {
          "label": "biolink:Cell",
          "count": 10000
        },
        {
          "label": "biolink:CellularComponent",
          "count": 5264
        },
        {
          "label": "biolink:MolecularEntity",
          "count": 3333
        },
        {
          "label": "biolink:BiologicalProcess",
          "count": 2862
        },
        {
          "label": "biolink:MacromolecularComplex",
          "count": 2128
        },
        {
          "label": "biolink:NamedThing",
          "count": 1877
        },
        {
          "label": "biolink:MolecularActivity",
          "count": 1274
        },
        {
          "label": "biolink:CellularOrganism",
          "count": 962
        },
        {
          "label": "biolink:PhenotypicFeature",
          "count": 498
        },
        {
          "label": "biolink:Vertebrate",
          "count": 388
        },
        {
          "label": "biolink:Virus",
          "count": 304
        },
        {
          "label": "biolink:PathologicalProcess",
          "count": 228
        },
        {
          "label": "biolink:ChemicalEntity",
          "count": 137
        },
        {
          "label": "biolink:SmallMolecule",
          "count": 60
        },
        {
          "label": "biolink:ClinicalCourse",
          "count": 40
        },
        {
          "label": "biolink:GeneticInheritance",
          "count": 33
        },
        {
          "label": "biolink:Onset",
          "count": 21
        },
        {
          "label": "biolink:Protein",
          "count": 21
        },
        {
          "label": "biolink:RNAProduct",
          "count": 3
        },
        {
          "label": "biolink:OrganismalEntity",
          "count": 1
        },

```

**Comment by glass-ships** [comment]
presumably we'd generate it as a fixture beforehand so it's not calculating those numbers live on every refresh (since they're not likely to change while it's up and running)

**Comment by vincerubinetti** [comment]
Perhaps doing this in the same place where you generate the frontend fixtures would be good, except save it to src/assets/meta.json instead.

**Comment by kevinschaper** [comment]
We can get node category counts from the search endpoint, but association counts aren't nicely exposed yet. We have a sort of orphaned monarch_py method called get_association_facets that we probably should expose (but might want to refactor first?  maybe add counts to the regular association endpoint instead?) - but if we just want to have a single metadata endpoint that has both node and association category info, we can use this method in solr_implementation.py:

```
[ field for field in si.get_association_facets(facet_fields=['category']).facet_fields[0].facet_values]
```

**Comment by glass-ships** [comment]
#287
