### ISSUE TITLE
Provide categories as single value and human readable.

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#170]
API currently returns a list with a single value. We need to provide a single value.

Incorporate 'category_label' in response for any call that returns categories

biolink:PhenotypicFeature - > Phenotypic Feature

**Comment by vincerubinetti** [comment]
This is now being done on the frontend for display purposes only (that is, when being passed back to the api, it retains the biolink: prefix and casing). It is already implemented as of several PRs ago.
