### ISSUE TITLE
endpoint: phenotype-explorer

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#18]
const url = `${biolink}/bioentity/${category}/${id}/phenotypes`;
 const { associations } = await request<_PhenotypeAssociations>(url, params);

-- 

  const url = `${biolink}/sim/compare`;
  const response = await request<_Comparison>(url, {}, options);

--

  const url = `${biolink}/sim/search`;
  const response = await request<_Comparison>(url, params);

**Comment by sagehrke** [comment]
@glass-ships can this be closed?

**Comment by glass-ships** [comment]
to be honest i'm not sure - i haven't been looking at semsim for a bit 

i believe we have compare in, @kevinschaper are search and/or phenotypes ready? 

if you want we can just close this and open/refer to more specific tickets about those in particular

**Comment by glass-ships** [comment]
closing in favor of more recent tickets about compare and search, now that the endpoint/UI page exists
