### ISSUE TITLE
Implement similarity compare using oak

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#192]
@justaddcoffee already made a PR for this monarch-initiative/monarch-py#96, so this is just an issue to track the work

It sounds like semsimiam support for phenotype comparison is not quite ready yet, but we can still hook it up using a the regular ontology implementation and semantic sql. 

For this issue/PR, let's shoot for:

- [x] Comparison returns output for example from UI (two sets of HP terms)
- [x] Uses phenio.db (just letting monarch-py download the latest, not sync'd yet, not using monarch-kg.db)
- [x] Output from API/python module should use the same model as oak
- [x] CLI method exists, takes term lists

**Comment by kevinschaper** [comment]
Model to match is: 

https://github.com/INCATools/ontology-access-kit/blob/7739a5fd0ab50269a9edb4fce4f547ec50341e7d/src/oaklib/datamodels/similarity.yaml#L45

**Comment by glass-ships** [comment]
hey @justaddcoffee just wanted to ask, i think you went over the `subject_best_match` and `object_best_match` in our meeting yesterday but it went a bit over my head - would you be willing to reiterate what the difference there is?

**Comment by glass-ships** [comment]
- [ ] Maybe make a script to grab specific version of oaklib semsim schema (i think `pkgutils` is deprecated, but maybe there's an equivalent?)

**Comment by glass-ships** [comment]
The work on this has moved to PR #239

**Comment by glass-ships** [comment]
@kevinschaper this is ready to close right?
