### ISSUE TITLE
Node association table search should not be case sensitive

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#198]
The `/entity/<id>/<category>` endpoint takes a search param that is meant to search within the displayed columns. Right now rather than using a proper dismax style query parser to search, it's just using a dumb `*{query}*` against subject and object labels. 

It should be implemented in a different way so that it's case insensitive.

**Comment by sagehrke** [comment]
@kevinschaper can you share a status update on this ticket, please? Thank you!

**Comment by kevinschaper** [comment]
Confirmed that this is working on beta.monarchinitiative.org
