### ISSUE TITLE
Add SAB Page to the Website

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#206]
I suggest we add a page on the Website dedicated to the Monarch SAB. 

**Include:** 
- [ ] Members (picture, organization, position)
- [ ] Meeting Cadence
- [ ] SAB purpose

**Comment by sagehrke** [comment]
@monicacecilia @putmantime Does this seem like a good idea? Or unnecessary?

**Comment by monicacecilia** [comment]
dupe of #74
