### ISSUE TITLE
Create page for Phenomics First Resource

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#210]
Create a new page describing the Phenomics First Resource. 
Okay to reuse materials from this aging PR as appropriate. https://github.com/monarch-initiative/monarch-ui/pull/406

**Comment by glass-ships** [comment]
A page now exists in the #265 PR, under `frontend/src/pages/about/PagePhenomicsFirst.vue`
I noticed there are a few incomplete sections - is there anyone knowledgeable enough about PFR to fill in those blanks?

**Comment by vincerubinetti** [comment]
Closed by #265
