### ISSUE TITLE
Add `force` flag to similarity compare that will still return results if not all phenotype terms match

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#213]
Adding this as a follow-on to monarch-initiative/monarch-app#192. 

@matentzn noticed that the biolink-api phenotype compare gives a 500 error if given a phenotype term that it can't find (which obviously must be extra frustrating right now with such old data supporting the endpoint). We should add a `force` option that will ignore terms that can't be found. 

This is likely also dependent on how oak behaves when it can't find a term, and could require making a change to the oak codebase as well.

**Comment by matentzn** [comment]
I think this is a good idea. Right now, the client needs to try except each call and filter out unknown phenotypes deliberately..

**Comment by kevinschaper** [comment]
With semsimian, IDs that aren't found are ignored. There is no explicit message that they aren't included, but at the same time, the subject & object best match results won't include the ID. I think we could extend our return model to be more explicit about ignoring an ID, but I don't think that was necessarily what this issue is about. I'm inclined to close this, since our current behavior matches the behavior requested in this issue.
