### ISSUE TITLE
Table format breaks on entity with --extra

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#215]
monarch-py doesn't know how to flatten a nested object into more columns for a table

**Comment by sagehrke** [comment]
@glass-ships Can you please clarify what this is blocking in relation to the Launch Milestone?

**Comment by glass-ships** [comment]
Thanks for the reminder @sagehrke i just hadn't gotten the chance to look at this in a good while. 
Will be closed by #345, can re-open later if this becomes an important requirement
