### ISSUE TITLE
Orthology associations not very helpful without taxon info

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#227]
We need to figure out how to include some taxon info here. 

It could be that we put taxon info on the edge (and we may need to do that for other reasons) and then use that taxon id & label in a column. 

We could also take an approach of doing something like putting taxon info into the subject_label or object_label as necessary - so that `pax2` for pig would look like `pax2 (sus scrofa)` - I think this is interesting because we could actually put that into the name field on the entity.  

<img width="857" alt="Screenshot 2023-07-14 at 7 19 48 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/5d2c4741-fa1f-4e45-9fc4-c4655fbde8e2">

**Comment by kevinschaper** [comment]
I should have looked at v3, it looks like it'll be another column 

<img width="915" alt="Screenshot 2023-07-14 at 7 31 13 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/42c14428-530d-4079-854d-9cf10b4a5573">

which means I need to prioritize https://github.com/monarch-initiative/monarch-ingest/issues/485

**Comment by vincerubinetti** [comment]
I'm adding this as an extra table column in the table view. But should we add this to the summary view?

**Comment by vincerubinetti** [comment]
This was at least added to the table view for associations:

https://github.com/monarch-initiative/monarch-app/blob/main/frontend/src/pages/node/AssociationsTable.vue#L174-L183

For summary, if gene names/symbols are truly not helpful at all without the taxon, maybe I could put the taxon in parenthesis immediately after, and not bolded. Eg: "**Pax2** (sus scrofa)".

**Comment by kevinschaper** [comment]
There's a little bit of information in the capitalization of gene names (human is always all caps, mouse/rat/? is capitalized first letter), but I do think that putting the taxon info right in the name/link definitely fits the use case nicely of why somebody would look at orthology associations.
