### ISSUE TITLE
Update text annotation capabilities for Monarch App

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#234]
Use OntoRunner/OGER to replace the old text annotator. 
https://github.com/monarch-initiative/ontorunner
https://github.com/OntoGene/OGER

The main workflow for the Monarch app is to enter text and extract phenotypes to be exported to the explorer. 

The old endpoint looked like: 
```
const url = ${biolink}/nlp/annotate/entities;
const response = await request<_Annotations>(url, params, options);
const { spans } = response;
```

**Comment by glass-ships** [comment]
As an update: 

Madan has done beautiful work adding this functionality to monarch-py's oak implementation. 
We've made an API endpoint for it in the backend, all that's left is to implement it in the frontend (likely with Vince's help, hopefully this Friday)
