### ISSUE TITLE
Serve dev, staging and production versions of the UI

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#235]
**monarch-app.monarchinitiative.org** could be our stand-in for production, which will be served from monarchinitiative.org after we release. This UI needs to be versioned to match the release that is running on api-v3.monarchinitiative.org

**beta.monarchinitiative.org** could be our staging site (I think this is a name we already have registered?), this will serve our candidate releases before they make it to production. 

**dev.monarchinitiative.org** could be our development site, it should serve the monarch-app main branch and whatever KG is the latest at http://data.monarchinitiative.org/monarch-kg-dev/latest 

We'll need to be able to build and deploy the UI so that the correct versions are deployed and will call the right api.

**Comment by kevinschaper** [comment]
Right now, we're serving monarch-app from GitHub pages, but that mechanism doesn't allow us to serve 3 sites. 

I like the idea of just serving from an http server on v3 stack, because it seems the most straightforward, and then we manage the UI hostname to VM linkage from the same load balancer UI that we're using for the api. 

What do you both think @falquaddoomi @vincerubinetti?

**Comment by vincerubinetti** [comment]
Fwiw Netlify could accommodate this if we had the different versions as different branches. Not sure I like adding branch clutter though. Might be easier and more consistent to just deploy the webapp to the same place everything else is being deployed to.

**Comment by vincerubinetti** [comment]
This is done I think? Though still room for improvement, i.e. `api-dev.mi.org/v3/api` -> `dev.mi.org/v3/api` so frontend can simply always (or most of the time) use a relative url. But this is perhaps tracked in #283.
