### ISSUE TITLE
Create New Monarch Team Page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#259]
What: Create a Monarch Initiative Team page. 

- This is also a kind request to make all efforts to avoid making it look like [this](https://monarchinitiative.org/about/team).  🙈
- Instead, we could try something like what [Digital Marmalade](https://www.digitalmarmalade.co.uk/our-story), [Matchstic](https://matchstic.com/about), or even [Etsy](https://www.etsy.com/team) have done. Simple, fun concepts, with a better visual for each participant. 

Fixes https://github.com/monarch-initiative/helpdesk/issues/83 -- reported by @sagehrke and @nlharris 

@putmantime @kevinschaper 👀👆🏽

**Comment by vincerubinetti** [comment]
How far do you want to go with this. Those are nice designs you linked, but the reason I made things so compact is because there are a lot of people listed. Unless maybe you want to pick a handful of people (maybe 12 or so) to highlight with bigger profile pictures and maybe short bios. And let me know if there is more descriptive text you want to add to the page. I wouldn't know what to write for that.

**Comment by nlharris** [comment]
> It would actually be super helpful if you (or someone) could take a look at the latest version at https://monarch-app.monarchinitiative.org/team and if there are any glaring issues/changes which need addressing, let us know via the new issue?

That page mostly looks good! Sarah G needs to be added to the CU section. Nicole V needs to be removed from CU and either moved to a section for her new institution or (more likely) moved to alumni.

David OS is no longer at EBI and I'm not sure he's even part of Monarch anymore -- move to Alumni? He's been replaced by James McLaughlin (https://www.linkedin.com/in/jamesamcl/). And Nico is listed twice; don't need to list him under EBI.

QMUL has some new people; maybe someone else can specify who they are.

**Comment by sagehrke** [comment]
As an FYI @glass-ships can assist with this update per a discussion in our Tech Team planning call this week.

**Comment by vincerubinetti** [comment]
Closed by #265
