### ISSUE TITLE
Clicking histopheno graph could filter annotation table

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#263]
We might want to implement this a different way, but here's my context:

glaucoma was mentioned in the context of term labels that are the same between HP & MONDO, so I was looking at the MONDO glaucoma page. I thought it was interesting that there's a skeletal phenotype. 

<img width="874" alt="Screenshot 2023-08-09 at 10 25 39 AM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/45506f01-c406-47de-a058-b088797e061f">

I noticed that hovering over the bar changes the color, and it feels as if clicking on skeletal system might give me details. It's a jump between sections, but we certainly could apply a skeletal system filter to the annotations table.  (well, technically, we can't yet, so I'll make another issue for that)

**Comment by sagehrke** [comment]
Related to issue #264

**Comment by monicacecilia** [comment]
dupe of #440
