### ISSUE TITLE
Can't filter annotations table by ancestor labels / histopheno slim 

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#264]
Looking at HistoPheno on https://monarch-app.monarchinitiative.org/node/MONDO:0005041?associations=biolink:DiseaseToPhenotypicFeatureAssociation, I wanted to know what the one skeletal phenotype for glaucoma was. 

Right now, the best I can do is scan down the page looking through the phenotype column to see what looks like it might be a skeletal phenotype.

One relatively quick solution would be to have the search box at the bottom of the table match against subject_closure_label and object_closure_label. The aspect of this that's a little unsatisfying is that the text that's being matched against wouldn't be displayed on the page - so we might want to make it a small step more complex by including some kind of field highlighting info, which could easily blow up into making it a less quick solution. Said a different way, the natural behavior of a search filter on a table is to only search against what is shown - getting outside of that natural behavior can explode into solving a lot of edge cases.

We could also consider adding a pulldown to filter the annotation table by the histopheno slim. This is less flexible that searching all ancestors and will be more work to implement than just a basic search, but it also feels like it's a much more controlled circumstance. We won't have to worry about text matching against irrelevant high level grouping terms, we don't have to choose the best highlight, etc.  This could also match up pretty well with #263

**Comment by monicacecilia** [comment]
All but 'become the clique' bits have been resolved. @kevinschaper will create a different ticket to update/review/resolve that issue.
