### ISSUE TITLE
subject and object entities (that aren't the page you're on) should be links

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#267]
Right now, we aren't linking to any entities from the associations table:

<img width="1126" alt="Screenshot 2023-08-09 at 7 04 36 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/92c6440b-c19b-45a1-b64c-e26497ecb746">

In 3a, there were links to the other side of any association.
<img width="1082" alt="Screenshot 2023-08-09 at 7 05 14 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/cf074807-1f47-49d8-983f-f806440b3ad7">

We should definitely at least link to the other side of associations, but I think it probably makes sense to change up our logic from 3a and just link to any entity that isn't the page we're already on. 

(thinking about how it also loses some of the sense of how each association relates to the entity page that we're on, it would be awesome if were able to make that association explicit, but I think that's a bigger change than we'd want to make right now)

**Comment by kevinschaper** [comment]
I guess I should add a screenshot of v2, which does link to both sides (and the predicate!), and I can imagine that it might have already been discussed to avoid linking to the descendent entities that are shown in the table, and if that's the case, then I'm definitely ok with just doing the other side of associations. 

<img width="1175" alt="Screenshot 2023-08-09 at 7 12 41 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/a1691e3b-36c7-4234-a657-2ef1e919273d">

**Comment by vincerubinetti** [comment]
This is already implemented. We did this during one of the mini-hackathons with Corey present. See this code:

https://github.com/monarch-initiative/monarch-app/blob/main/frontend/src/pages/node/AssociationsTable.vue#L27-L53 
https://github.com/monarch-initiative/monarch-app/blob/main/frontend/src/components/AppNodeBadge.vue#L13-L20

So rhere is something else wrong. In your screenshot, both are bold, so both have the `.name` css class, so the prop `link` is false, so `node.id` isn't matching the association `object` or `subject`.

**Comment by kevinschaper** [comment]
Ohh! shoot, ok, clearly I need to deploy to dev.

**Comment by kevinschaper** [comment]
re-opening, current behavior is linking to the "other" entity only for direct associations, but associations coming in for descendant annotations didn't get a link on either side. I'm going to try out linking to either side of the association if it's not just a link to the page we're on.
