### ISSUE TITLE
Update Publications list

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#269]
- Being addressed in #265 

We currently don't have a way to automate the process of generating a list of monarch publications

`scholarly` is a python library that interacts with Google Scholar that mostly works, but:  
- some publications don't populate with all info
- i'm not sure how to get the PUBMED URL for a given publication

so some manual curation would be required after generating the script. however this could get rather intense given how many there are

**Comment by glass-ships** [comment]
`scholarly` and SerpAPI seem to return pretty much the same results, just in a different form. 
Which is probably good, `scholarly` doesn't limit me to 100 searches/month or an account

**Comment by glass-ships** [comment]
No reliable way to get PUBMED IDs for a given publication title. 
Some (>50) results find no id at all, some return with multiple

**Comment by glass-ships** [comment]
Crossref API/`habanero` don't seem to be much more help either. 

Both PUBMED and Crossref successfully find appropriate results for many searches via their web interfaces, but APIs fail and are extremely difficult to work with / lacking in documentation.

This may just be a gruelingly manual process. 

We may want to consider maintaining an actual list of publications as a collaboration, be it:
- updating and strictly managing our Google Scholar articles to contain necessary info
- Dual uploading / utilizing Zenodo
- A Git repository with a yaml/json/something of all our publications (which gets updated when a new paper is published)

**Comment by glass-ships** [comment]
Seems like the plan for now is as follows (@sagehrke please correct me if i'm not totally following!): 

- As a first pass, I'll
  - Use the existing `publications.json`, the R24 data, and scholarly to come up with a manually curated list of publications with all data fields populated
  - Ensure DOIs are populated for all / as many pubs as possible (also manual)
- Going forward, we'll maintain Google Scholar a bit more precisely and use that as a way to get new publications? However this means:
  - we won't get DOIs or PMIDs for anything new 
  - the results will include anything that cites Monarch, not just directly funded papers. which leads me to
- Do we want to separate third party citations from monarch-proper papers?  Is there any good way to _tell_ just from the [scholarly results](https://github.com/monarch-initiative/monarch-app/blob/about/scripts/scholarly_output.py)? 
- Will the manual curation process still need to happen every time a new paper comes out, to appropriately add a DOI or PMID? (Probably)

**Comment by vincerubinetti** [comment]
This was completed in #265.
