### ISSUE TITLE
pagination limit needs to have a maximum

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#271]
Not a big surprise, but if you ask for limit=99999999 on the association endpoint, it does bad things to the VM. 

It's most obviously a problem for the association endpoint, but could still be a problem with search and a very smart user asking for a top level entity might be able to get too big of a result.

**Comment by caufieldjh** [comment]
Whatever you do, please please please make sure the limit is clearly documented

**Comment by kevinschaper** [comment]
It looks like using pydantic constraints with fastapi is a winner, check this out @caufieldjh:

<img width="467" alt="Screenshot 2023-08-11 at 4 31 31 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/67de3fc6-9c2b-4e8f-804e-00ceae6d90cd">

**Comment by kevinschaper** [comment]
I'm starting with 500 because that's the max in the UI. 

I played around with our current performance using 500, 1000 and 10000. A max of 1000 seemed ok, but I think matching the UI probably makes sense.
