### ISSUE TITLE
Add "relative" path to list of API urls?

### ISSUE THREAD

**Issue by falquaddoomi** [monarch-initiative/monarch-app#284]
Since hosting the UI alongside the rest of the v3 stack, I've noticed that all the options in the list below are absolute URLs.

https://github.com/monarch-initiative/monarch-app/blob/f4eb50c6220ee668cd5054f3df1f6e4609afe3e3/frontend/src/api/index.ts#L33-L38

Would it be possible to add an extra option, say "relative", that makes the API URL a relative URL, e.g. `{ relative: "/v3/api" }`?

With that in place, I'd be able to more easily test the UI container since it'll be running from the same host as the API.

**Comment by vincerubinetti** [comment]
@falquaddoomi @kevinschaper @glass-ships How does this code look, I'm thinking of changing it to this:

```ts
/** served location of webapp, verbatim from browser address bar */
const url = new URL(window.location.href);

/** get api name/version to use... */

/** ...from (sub) domain of url */
const fromDomain =
  url.hostname.match(/([/w-]+)?\.?(monarchinitiative)\.org/)?.[1] || "";
/** note: prod and running locally have none */

/** ...from env var */
const fromEnv = import.meta.env.VITE_API || "";

/** ...from param in url */
const fromParam = new URLSearchParams(url.search).get("api") || "";

/** name of monarch api version to use (highest to lowest override priority) */
export const apiName = fromParam || fromEnv || fromDomain || "";

console.info({ fromParam, fromEnv, fromDomain, apiName });

/** base monarch api url */
let monarch = `https://api-${apiName}.monarchinitiative.org/v3/api`;

/** special case for running server locally */
if (apiName === "local") monarch = `http://127.0.0.1:8000/v3/api`;

/** last resort fallback */
if (apiName === "") monarch = `https://api-next.monarchinitiative.org/v3/api`;

export { monarch };
```

This way, there's no "mapping" step, and whatever string is the flag just gets inserted verbatim into the api url. And because `fromDomain` comes directly from the url, this will solve the relative problem.

This only works if the `api-version.mi.org/v3/api` format always holds (which I think it should for consistency and to avoid confusion).

**Comment by glass-ships** [comment]
yeah this looks good! nice and simple ~~relatively~~

**Comment by falquaddoomi** [comment]
@vincerubinetti Seems reasonable to me. FWIW, I'm not always testing the app locally or on a subdomain of `.monarchinitiative.org`, which is why I asked for the relative URL option. I guess since my request is just for my personal ease of testing I can just forward the API server to match `127.0.0.1:8000` from the remote, so no worries; feel free to close this issue if you like.

**Comment by vincerubinetti** [comment]
~Can you give me an example of where you'd be testing where the URL format of the webapp and server don't conform to `XXX.mi.org` and `api-XXX.mi.org/v3/api`?~ I guess, what do you mean by relative specifically.

I want for it to be pretty easy to test and switch around the api version, so I'd like to support your use case.

**Comment by vincerubinetti** [comment]
I guess, maybe you're running both the app and server locally on different ports?

So maybe I should do this instead:

```ts
// and check if === "local" too, if this is always how it will be run locally
if (apiName === "relative") monarch = `/v3/api`;
```

**Comment by falquaddoomi** [comment]
For example, when I'm testing the stack, I'll spin it up on the `cuhealthai-foundations` project and it'll just have an IP, e.g. `http://34.172.175.63`. It'd be nice if I could tell the UI to use the API as just`/v3/api`, so that the origin is filled in automatically by the browser.

I've reversed my opinion that this is necessary, though; feel free to leave it as-is.

**Comment by vincerubinetti** [comment]
I think this is useful, I'll add it.

@glass-ships , should I also leave in `local` hard-coded to `127.0.0.1:8000` for your testing?

**Comment by glass-ships** [comment]
i'm not sure i totally understand the implementation you have in mind for faisal's use case, but it sounds like it could work for mine as well? i'll leave that up to you

**Comment by kevinschaper** [comment]
I'm wondering about swapping `/v3/api` to `/api/v3` - the reason we put v3 in front before was so that we could route requests between biolink-api & monarch-api from within the same load balancer, but that option went away fairly soon after. We'd need to change this on the api side as well, of course.

**Comment by vincerubinetti** [comment]
Is it possible to get rid of the suffix all together? Seems funny to have `/api` when it's already `api-dev.mi.org`. Regardless, I made a PR for this. Since this is the key interaction point between the frontend and backend, it affects all of you, so please take a look.

**Comment by falquaddoomi** [comment]
The suffix is required if nginx is going to be the entrypoint into the stack, otherwise I have no way of telling which requests should go to the API and which should go to the frontend. (At the moment, i presume anything that starts with `/v3/` is an API request and pass it off to the API service verbatim. If it doesn't, it gets sent to the frontend's `index.html`, as AFAIK you're supposed to do with client-side apps that perform their own internal routing.)

I also personally like including a coarse version indicator in the URL so that, if we ever do make breaking changes, people who depend on the old version will at least see that `/v3/` has become a 404 and won't instead misinterpret (for example) `v4` results as `v3` ones. If we end up having the resources and see a need, it provides us the option to support both versions concurrently for a smoother transition to the new version.

Actually, that reminds me that I'm a bit unclear on the domain allocations: if the UI is going to be hosted alongside the rest of the services, what will the domain name for the stack be? Is it `api-dev.mi.org`, `dev.mi.org`, or will the frontend and backend be on entirely different subdomains?

**Comment by kevinschaper** [comment]
Oh, we're going to serve the api from `dev.monarchitiative.org/v3/api` (or maybe `dev.monarchinitiative.org/api/v3`), so that the UI will be able to look for the api as a relative url on the same host. I wasn't sure about getting rid of the api hostnames, but I'm not sure if we should use them from the UI

**Comment by vincerubinetti** [comment]
@kevinschaper When is that change coming? Because that would make a bunch of my code in the linked PR irrelevant.

Also fwiw I vote for `/api/v3` instead of `/v3/api`. Keep the more static/stable thing closer to root. Also it feels like "v3 of what? oh, the api" if reading left to right.
