### ISSUE TITLE
Trim api inputs

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#296]
If I throw a couple of spaces in front of a MONDO ID going into the get entity endpoint

```
/v3/api/entity/%20%20MONDO%3A0019391
```

The api returns an Internal Server Error.

We should trim inputs, so that this doesn't return an error.  (I'll make a different issue for better error handling)

**Comment by glass-ships** [comment]
UI already trims input, and CLI doesn't seem to add in extra characters. 

Mostly an issue when manually entering API endpoints via URL. 

Could just do a strip on every endpoint in the FastAPI code, 

but kevin also suggests that turning inputs into Pydantic classes may be a worthwhile investment

**Comment by kevinschaper** [comment]
I'm inclined to close this, I don't know that it's an actual problem - it's probably enough that the UI trims the input
