### ISSUE TITLE
Show an explicit message rather than an empty pulldown when a node has no associations

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#302]
<img width="673" alt="Screenshot 2023-08-31 at 3 45 58 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/cd773c74-2fa9-4d2b-9ff2-1290a861c179">

MONDO:0004276 doesn't have any associations (at least, not that we show in the associations table), so it ends up with just an empty selector for choosing a type of associations to show. We could show some kind of explicit message to say that it doesn't have associations.

**Comment by vincerubinetti** [comment]
I'll fix this in #301

**Comment by vincerubinetti** [comment]
I'm assuming we should hide histopheno, too, if there's no phenotype counts to be shown?

<img width="854" alt="Screenshot 2023-08-31 at 5 28 22 PM" src="https://github.com/monarch-initiative/monarch-app/assets/8326331/c046a5b1-e2e3-4272-a912-ea9538725000">
