### ISSUE TITLE
Contact members for better headshots

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#304]
The [new team page](https://next.monarchinitiative.org/team) shows peoples' faces up-close and personal. Some of these photos are quite low resolution and could use a newer shot. Here is my flagging of problematic ones. ~~Perhaps the alums are not as critical.~~

**Issues**

- Matthew Brush (res)
- Shahim Essaid (res, lighting)
- Bryan Laraway (res)
- Seth Carbon (res, lighting)
- Sierra Taylor Moxon (res)
- Justin Reese (res)
- Sebastian Köhler (circle crop, res)

**Improvable**

- Melissa Haendel (res)
- Faisal Alquaddoomi (res, bg)
- Bryan Laraway (res)
- Peter Robinson (res)
- Hannah Blau (res slightly, cropping too tight)
- Chris Mungall (letterbox)
- Nomi Harris (res slightly)
- Damian Smedley (res slightly)
- Nicolas Matentzoglu (res, lighting)
- Kent Lloyd (res)
- Matthew Wheeler (res)
- Jason Williams (photo vs drawing?)

**Missing**

- Trish Whetzel
- Katherina Cortes
- Harshad Hegde
- Mark Miller
- Patrick Kalita
- Ben Coleman
- Daniel Danis
- Lauren Rekerle
- Martha Beckwith
- Anita Reane Caron
- Arwa Ibrahim
- James McLaughlin
- Ray Stefancsik
- Vinicius de Souza
- Carlo Kroll
- Valentina Cipriani
- Yasemin Bridges
- Ada Hamosh
- Chris Chute
- Joseph E Flack
- Nicole Vasilevsky

----

**Guidelines for good photo**

- High res, at least 300x300 (natively, non-upscaled).
- Square, tight crop (but without cutting off face).
- Face mostly centered.
- Well-lit, good contrast.
- Minimal background distraction. Depth-of-field blur on background ideal.

Ideal examples (photos as of writing):

- Tim Putman
- Sarah Gehrke
- Sabrina Toro
- Kevin Schaper
- Glass Elsarboukh

---

**Other related tasks** (make new issue?)

- [x] Check that all members' group affiliation and alum status are up to date.
- [ ] Check that all members have a website/linkedin/whatever link, as appropriate.
- [ ] Check that all members' listed roles are accurate.
- [ ] Check that everyone is OK with their pictures, as some of them were pulled from Slack, GitHub avatar, etc. Perhaps some are quite old and should be replaced with a newer one.
- [ ] Check that all photos are about less than 1000x1000 and 150kb (jpg), roughly, to save the user some bandwidth (even though photos are only loaded when they come into view).
- [ ] Do rough color/contrast/brightness equalization across all photos, either by eye or automatically with photoshop? Very low priority, they're all okay at the moment.

**Comment by glass-ships** [comment]
@putmantime / @sagehrke I'm noticing a lot of links (particularly for alumni) are out of date or lead to 404's. 

Two (maybe three) part question: 
- should I be including alumni in this email?
- what should I do for team members (current or alum) for whom I can't find an email address? 
- would be acceptable / in poor taste to google some members to get updated links / emails for contact?

**Comment by sagehrke** [comment]
Related to #399
