### ISSUE TITLE
Update to publications page on beta site

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#323]
Please update the following on the Publications page https://next.monarchinitiative.org/publications
- [x] Change title to **Monarch-related Publications**
- [x] Add subtext to the title that says "This list includes papers by the Monarch Team that were foundational to the current Monarch work."

Note for @glass-ships: the Google Scholar has been checked, and any publications that were listed with no publication date have been removed. A few publications were removed due to identifying they were not by our team, and only a couple were added that were missed in the initial creation of the Google Scholar account. Please check your Python script is working ok after I made the updates. 

@nlharris Can you please give the Google Scholar list a check? https://scholar.google.com/citations?hl=en&user=zmUEDj0AAAAJ&view_op=list_works&sortby=pubdate The second set of eyes out be great. If you find publications that are not applicable to our group and need to be removed, please ping me and I will notify Glass of the changes. Otherwise, a message saying they look ok to you would be great.

**Comment by nlharris** [comment]
The Google Scholar list looks good to me (though I only went back to about 2020). The few publications that were not obviously-to-me Monarch-related turned out to have one of our team members somewhere on the author list.

**Comment by nlharris** [comment]
minor issue: I just found the k-BOOM preprint listed 3 times. the 2019 version replaced the double-listed 2016 version, but the 2019 one is cited oddly, with melissa's name in front of the title.
oh, and i found one that's not us: [The 24th annual Nucleic Acids Research database issue: a look back and upcoming changes](https://academic.oup.com/nar/article-abstract/45/D1/D1/2770636) (probably mentions Monarch in the article, but the article isn't BY us)

**Comment by sagehrke** [comment]
Thanks Nomi - I have deleted [The 24th annual Nucleic Acids Research database issue: a look back and upcoming changes](https://academic.oup.com/nar/article-abstract/45/D1/D1/2770636) (probably mentions Monarch in the article, but the article isn't BY us)

**Comment by sagehrke** [comment]
I see the 3 k-BOOM preprints and the issue with the 2019 version. Should I just merge to one of the 2016 ones instead?

**Comment by nlharris** [comment]
the 2019 one would be better

**Comment by sagehrke** [comment]
Done! Fixed the title and merged all k-BOOM preprints to the 2019 version.

**Comment by vincerubinetti** [comment]
"Monarch-specific" is unnecessary. Everything on the site is Monarch specific. There will also be a paragraph below it that explains what the publications are exactly. It's also a more specific heading than any of the other headings on the site and thus inconsistent.
