### ISSUE TITLE
Answer the question: How do you decide "top 5 phenotypes"?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/monarch-app#329]
**Please describe your question, suggestion, or concern.**

These appear to be alphabetical (arbitrary & misleading),  this is a bit annoying because to see them all I need to switch to the table view, and change the number of viewable rows to the max (2 extra unnecessary steps)

**Comment by kevinschaper** [comment]
Thanks for submitting this @ValWood! 

What we have right now is ordering by evidence count first, then to ensure that results come back in a consistent order, alphabetically. We could slightly obfuscate this if we sorted by a hash function that would randomize a bit, but ultimately the problem we have is that by this method, the top 5 aren't really "top" very often - except in the rare instance that an association has more than one publication. 

I think we could definitely improve our ranking method by looking at something like information content scores and how rare a term is in annotations, but I also wonder if we should be framing the problem differently. 

If it's really about showing a top set of terms, we could break out from showing as triples and instead break it into a list (which would also be a way of doing result grouping) - but I could also see taking a summarization approach in some cases, like we do for the HistoPheno bar chart - or taking that the next logical step and moving to something like the ribbons used at MGI/Alliance/ZFIN that combine the "at a glance" summarization with the ability to drill down and see subsets of detailed annotations. 

Ribbon screenshots: 

<img width="1410" alt="Screenshot 2023-09-20 at 1 41 51 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/b2172078-63e2-4da3-8214-6b46d07e8d8e">

<img width="1367" alt="Screenshot 2023-09-20 at 1 44 34 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/5d52939b-c907-4714-9e92-787697b33748">

<img width="1376" alt="Screenshot 2023-09-20 at 1 45 36 PM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/743d6a5e-4a03-41b5-9fc3-6d641b7a294e">

**Comment by ValWood** [comment]
Ribbons  would  work if you are confident that your slim set covers all  terms (or you have a bin for 'other').

**Comment by kevinschaper** [comment]
I don't think it will be practical to implement a ribbon or a new phenotype section in the next release, but I think we're starting to have a better toolbox for ranking phenotypes / phenotype associations. 

Assuming that we get a new biolink model release, we will be capturing quantitative HPOA frequency information. That will be a helpful boosting choice for d2p.

For other phenotype associations, I think we could use the inverse document frequency in the Solr index as one measure of value for a phenotype association, and we may also be able to propagate information content scores for phenotype terms for an additional scoring input. 

I feel confident that we can at least begin to address this as a ranking problem in the March release.

**Comment by kevinschaper** [comment]
This ticket is (finally!) ready to close. We've moved to sorting phenotypes by frequency, and displaying a frequency column.

The change is currently deployed on beta.monarchinitiative.org and heading to monarchinitiative.org today if all goes well.

**Comment by ValWood** [comment]
I don't see the frequency column populated  for cdc2 on beta?

**Comment by ValWood** [comment]
ignore, I see the other ticket.
v
