### ISSUE TITLE
Phenotypes 86?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/monarch-app#338]
<img width="870" alt="Screenshot 2023-09-21 at 15 50 32" src="https://github.com/monarch-initiative/monarch-app/assets/7359272/63e7bfa4-afb8-4b97-989e-47fbbd81650d">

**Comment by sagehrke** [comment]
@kevinschaper and @glass-ships I am guessing there is a "K" missing (or something similar) after the "86" for number of phenotypes on the homepage https://next.monarchinitiative.org/
