### ISSUE TITLE
Update Monarch Technical Documentation with Release SOP

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#344]
Add a page for the SOP on Monarch Releases to the Monarch Technical Documentation: https://monarch-initiative.github.io/monarch-technical-documentation/ 
Make the instructions clear enough that anyone on the team could run a monthly Release. 

I suggest @kevinschaper drafts the SOP and @glass-ships adds it to the documentation site.

**Comment by kevinschaper** [comment]
A snippet for the doc, at least until we automate it (and we really should automate it)

Deploying changes to production:

Create a new github release, once the docker to generate the image is done, run these steps. 

```
export APP_VERSION=0.17.0
export RELEASE=2023-09-28

gcloud compute ssh --zone us-central1-a monarch-v3-${RELEASE}-manager -- sudo docker service update monarch-v3_api --with-registry-auth  --update-order=start-first --force --image us-central1-docker.pkg.dev/monarch-initiative/monarch-api/monarch-api:${APP_VERSION}

gcloud compute ssh --zone us-central1-a monarch-v3-${RELEASE}-manager -- sudo docker service update monarch-v3_nginx --with-registry-auth  --update-order=start-first --force --image us-central1-docker.pkg.dev/monarch-initiative/monarch-api/monarch-ui:${APP_VERSION}
```

In additional terminal windows, it may be useful to watch the process with:
```
gcloud compute ssh --zone us-central1-a monarch-v3-${RELEASE}-api -- sudo docker stats
```
and 
```
gcloud compute ssh --zone us-central1-a monarch-v3-${RELEASE}-manager -- sudo docker service logs -n 1 -f monarch-v3_api
```

Also, update the env in monarch-stack-v3 for this release to match the docker image version. 
(maybe that should come first, then put the docker commands into a makefile)

**Comment by glass-ships** [comment]
Regarding https://github.com/monarch-initiative/monarch-technical-documentation/issues/25

Would it be possible to get the DOI for final releases to include in this PR?

**Comment by glass-ships** [comment]
See: https://github.com/monarch-initiative/monarch-documentation/pull/28
