### ISSUE TITLE
Bang our own drum 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-app#348]
It would be great to have the front page of the Monarch App show a list of "our" ontologies with links to the specific resources -- Mondo, Hpo, Uberon, Oba, etc

**Comment by sagehrke** [comment]
I agree with this! Making the Monarch app the centralized location to find all of the many monarch tools, ontologies, etc would be great. **Can we make a concrete list of what to include and the best way to integrate it into the UI?** I feel like it would be great to have a new dropdown that is "Products" or something like that, and we can list everything with a short description and link to the content. The homepage could have a few of the Flagship Monarch projects (based on input from the Monarch leadership) listed with quick button links. 

Off the top of my head, it would be nice to have links to: HPO, Phenopackets, Mondo, Exomiser, LinkML, uPheno, OAK, Boomer, SSSOM, POET, PhEval, Uberon, OBO Academy training, KG-Hub(?), OBA

**Comment by sagehrke** [comment]
@glass-ships Please create the following at monarchinitiative.org: 
- Add another button to the top ribbon that is titled "Resources"
- On this new “Resources” landing page, you can follow the same formatting as the "About" page with the circle icon links. 
- Organize each resource into one of three categories: Standards, Ontologies, Tools
- Under each category, list the resource (from the Flagship product list I have shared with you). Each resource will have a button to an outside site that will either be a generic icon or the official project logo (preference is to use a project logo if it exists). Note: Logos can be found here: https://github.com/jmcmurry/closed-illustrations/tree/master/logos
- Each Resource will have the resource’s name, the link to the external site for the resource, and then a one-liner tagline for what the resource is.

**Comment by glass-ships** [comment]
Added some basic taglines for each resource - @sagehrke / @monicacecilia feel free to review and revise as appropriate
Also opened an issue for a textless mondo icon, and marked a few that have no logo (mostly for my own reference)

**Comment by vincerubinetti** [comment]
Does this need to be in the header? Can it just be a featured link at the top of the About page, or on the home page? The header is precious real estate.

**Comment by sagehrke** [comment]
Hi @vincerubinetti - yes, please. We'd like the "Resources" to be in the header, not nested on another page.

**Comment by glass-ships** [comment]
done in #463 - preview available [here](https://deploy-preview-463--monarch-app.netlify.app/resources)
please review at your convenience
