### ISSUE TITLE
Compare content between V2 and V3 graphs

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#350]
The goal is to produce comparisons that show the benefits of the new graph, or reveal holes that will be a priority to fill

First pass can include:
* Association, counts for subject_category+predicate+object_category
* Entity counts for:
  * category alone
  * prefix alone (maybe?)
  * category + taxon + prefix
  * unique prefixes (maybe?)

**Comment by sagehrke** [comment]
@amc-corey-cox Can you please share a status update? Thank you!

**Comment by kevinschaper** [comment]
I made a PR with the notebook that I started for counting entities and associations in the V2 graph mapping the old categories to biolink. I don't know that we need to get this perfect to complete this issue though.

**Comment by amc-corey-cox** [comment]
Hey Kevin, can you let me know if the QC Reports SRI-Reference comparison on
https://monarch-initiative.github.io/monarch-qc/
satisfies requirements for this? Click the SRI-Reference Comparison button at the top.

Let me know if we need anything else. We can go through your notebook if you have something we should add.

**Comment by kevinschaper** [comment]
Is it possible to do the same table, but using ID prefixes instead? 

Probably this is enough and we should consider the issue done, but I'm realizing that, for example, there's no useful category info for variants, so we can kind of guess that they're in the 17m named things, but maybe being able to also see a table broken up by prefix would help for that?  

(that could also reasonably be a different issue if it's not a quick addition)

**Comment by amc-corey-cox** [comment]
Unfortunately, the SRI reference stat file doesn't have the by ID. Otherwise, it would be easy to do if we have a file with that data in there. Or at least, I didn't see it in there when I parsed the data.

**Comment by amc-corey-cox** [comment]
I also have access to edge spo but it's so messy I commented it out... We could add it at the end if we think it is useful.

**Comment by kevinschaper** [comment]
Nah - let's call this done!
