### ISSUE TITLE
Panther has 303k fewer edges in 2023-09-28 build

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#351]
We're down 303,343 edges from Panther in the most recent build, and interestingly, it's not a mapping issue, because dangling edges for Panther is also down by 100k rows. 

The first thing we should do for this issue is to compare the ingest output from the last two versions: 
https://data.monarchinitiative.org/monarch-kg-dev/2023-09-28/transform_output/panther_genome_orthologs_edges.tsv
vs
https://data.monarchinitiative.org/monarch-kg-dev/2023-09-15/transform_output/panther_genome_orthologs_edges.tsv

That won't have taxon info, so it might end up being more practical to make subsets from monarch-kg-denormalized-edges.tsv from each. 

I'm putting this in the October 3rd release milestone, because I think that it's important to at least initially understand what's happening.

**Comment by kevinschaper** [comment]
I don't see anything systematically missing that points to a mapping or ingest problem. The change appears to be a result of the new Panther release: https://www.pantherdb.org/news/news20230917.jsp

For example, here are the human ortholog counts in our 2023-09-15 release:

| subject_taxon_label |       object_taxon_label       | count(*) |
|---------------------|--------------------------------|----------|
| Homo sapiens        | Canis lupus familiaris         | 19       |
| Homo sapiens        | Gallus gallus                  | 65       |
| Homo sapiens        | Saccharomyces cerevisiae S288C | 6573     |
| Homo sapiens        | Xenopus tropicalis             | 11406    |
| Homo sapiens        | Dictyostelium discoideum       | 11793    |
| Homo sapiens        | Sus scrofa                     | 16022    |
| Homo sapiens        | Bos taurus                     | 16820    |
| Homo sapiens        | Caenorhabditis elegans         | 20125    |
| Homo sapiens        | Rattus norvegicus              | 21628    |
| Homo sapiens        | Drosophila melanogaster        | 21732    |
| Homo sapiens        | Mus musculus                   | 24251    |
| Homo sapiens        | Danio rerio                    | 32337    |

vs our 2023-09-28 release: 

| subject_taxon_label |       object_taxon_label       | count(*) |
|---------------------|--------------------------------|----------|
| Homo sapiens        | Canis lupus familiaris         | 104      |
| Homo sapiens        | Sus scrofa                     | 114      |
| Homo sapiens        | Bos taurus                     | 3685     |
| Homo sapiens        | Schizosaccharomyces pombe      | 6026     |
| Homo sapiens        | Saccharomyces cerevisiae S288C | 6632     |
| Homo sapiens        | Xenopus tropicalis             | 11464    |
| Homo sapiens        | Dictyostelium discoideum       | 12127    |
| Homo sapiens        | Danio rerio                    | 15763    |
| Homo sapiens        | Caenorhabditis elegans         | 18993    |
| Homo sapiens        | Rattus norvegicus              | 21269    |
| Homo sapiens        | Drosophila melanogaster        | 21630    |
| Homo sapiens        | Mus musculus                   | 25123    |

**Comment by putmantime** [comment]
The data seems to have legitimately changed. We still need to assess the impact on the graph.
