### ISSUE TITLE
Add node category and association category counts to QC dashboard

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#361]
We should add two additional tables/sections to the qc dashboard that will show counts by category for nodes and edges, and include the change relative to the previous release.

We may need to update the QC generation code to support counts purely by category, or we may be able to do it by reading from the kgx generated graph report.

**Comment by amc-corey-cox** [comment]
Kevin, do you think this is complete with my reset PR to Monarch-qc?

**Comment by kevinschaper** [comment]
Yes! thank you!
