### ISSUE TITLE
Larger phenogrid example

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#367]
We may want to provide a larger example for phenogrid. This is a possible example.

https://dev.monarchinitiative.org/phenogrid?source=HP:0000939,HP:0000444,HP:0000546,HP:0000135,HP:0007618,HP:0004322,HP:0002669,HP:0002858,HP:0100324,HP:0005177,HP:0000320,HP:0000518,HP:0000819,HP:0001620,HP:0002155,HP:0001533,HP:0001608,HP:0002209,HP:0002211,HP:0002216,HP:0003777,HP:0007495,HP:0010721,HP:0100578,HP:0000035,HP:0000144,HP:0002664,HP:0002672,HP:0002860,HP:0002861,HP:0002890,HP:0003002,HP:0009726,HP:0012056,HP:0012060,HP:0100242,HP:0100526,HP:0100615,HP:0100649,HP:0100659,HP:0100833,HP:0002293,HP:0001838,HP:0002621,HP:0003202,HP:0004415,HP:0005978,HP:0007703,HP:0008065,HP:0003419,HP:0004349,HP:0005328,HP:0031956,HP:0031964,HP:0040217,HP:0000765,HP:0010468,HP:0011001,HP:0100585,HP:0100679,HP:0200042,HP:0200055,HP:0000822,HP:0000869,HP:0001387,HP:0001601,HP:0000855,HP:0000934,HP:0000962,HP:0001635,HP:0009125,HP:0000275,HP:000165&target=HP:0002761,HP:0002616,HP:0002650,HP:0002758,HP:0002827,HP:0002829,HP:0002999,HP:0003010,HP:0003083,HP:0003834,HP:0004872,HP:0004944,HP:0004947,HP:0005294,HP:0006243,HP:0007495,HP:0009763,HP:0010749,HP:0010750,HP:0010754,HP:0025014,HP:0025019,HP:0031364,HP:0031653,HP:0001278,HP:0001634,HP:0001653,HP:0001704,HP:0002315,HP:0002013,HP:0002018,HP:0002020,HP:0003394,HP:0003771,HP:0000974,HP:0001027,HP:0001030,HP:0001065,HP:0001073,HP:0001075,HP:0012378,HP:0012450,HP:0000015,HP:0000023,HP:0000139,HP:0000286,HP:0000481,HP:0000978,HP:0000993,HP:0001063,HP:0001270,HP:0001386,HP:0001537,HP:0001622,HP:0001760,HP:0001762,HP:0001763,HP:0001788,HP:0002035,HP:0002036,HP:0000938,HP:0001058,HP:0001252,HP:0001324,HP:0025509,HP:0030009

**Comment by vincerubinetti** [comment]
I updated the fixture data for sem sim compare in #372 . If you're talking about updating the built in "try an example" button in the UI, I'd want to split it up into "try a simple example" and "try a bigger example". For someone just playing around with the UI, it's nicer to see a smaller example to see how things are laid out, and also because it would presumably take less time for the analysis to complete.

**Comment by kevinschaper** [comment]
For the next release, we should converge on a medium sized example that's somewhere in between the 3x5 with little overlap and the example in this issue that includes two diseases with a ton of phenotypes

**Comment by amc-corey-cox** [comment]
I'll reach out to Moni and others we discussed the tryptic presentation idea. Sarah also suggested I reach out to Ada, ahamosh@jhmi.edu. Moni I added you here so you can see the whole issue. We should discuss this when you get back.

**Comment by amc-corey-cox** [comment]
One problem with our current small example is that it is just too small. Both edges of the matrix should have at least a few matched phenotypes. Ideally, I'd like the small set to be 3x5 matched phenotypes and at least one unmatched. This shows the user all of the basic functionality of the phenogrid. Having a larger example would also be nice; I'd like something around 15x20.

As I mentioned in #523, these may be obsoleted by fixing that issue and having reasonable auto-suggests on no input.

**Comment by amc-corey-cox** [comment]
Sarah shared this source for Monarch presentations that we could look through for diseases of general interest to Monarch community.

https://drive.google.com/drive/folders/1xKB_O3LmtW0MNCqC7tIyGU2D0Niq1jY9

**Comment by amc-corey-cox** [comment]
Marfan Syndrome vs Ehler's Danlos has been suggested as a starting point for creating a few more interesting/useful examples.

I'm planning to subset each of these in order to get smaller sets for examples. Please comment here if you'd like to see other diseases included in our examples.
