### ISSUE TITLE
Work on Rust Semsimian Server

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#370]
See: https://github.com/glass-ships/semsimian-server

**Comment by kevinschaper** [comment]
Yup, it's working!

**Comment by glass-ships** [comment]
we should probably transfer it over to the monarch org at some point, complete with any lingering issues and scripting changes needed in monarch-app

**Comment by kevinschaper** [comment]
Definitely. I'm also still kind of tempted to put it into monarch-app to simplify the docker build and deploy.

**Comment by glass-ships** [comment]
Still inclined to leave it as a standalone tool since:
- it shouldn't be getting changed nearly as often as the api
- there are possible applications for it outside of monarch-app (maybe?)
- monarch-app is already a pretty complicated/somewhat bloated repo as is
- ...?

but i'm open to other considerations
