### ISSUE TITLE
Add Variant information in Monarch

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/monarch-app#373]
At the Monarch meeting on 2023-10-05, we determined that we need more information about what we want from “variants” to prioritize the work and move forward with adding variants information in Monarch.

Each of the following points needs to be discussed.
 
**1. What are the use cases? What is the scientific question we want to answer? What do users want from variant information?
These need to be determined before any work can be done.** 
notes:
    - Variants in the same gene might lead to different phenotypes or different diseases depending on the location of the variant within the gene.
    - Variants in non-coding regions might lead to phenotypes/diseases. These wouldn’t be found if searching for a gene.
    - Would this information be incorporated into existing tools such as Exomiser? 

**2. What should the UI look like? How would a user get to the variants information?**
     - It is helpful when modeling data to know how users would search for and access variant information.
     - Do we need "ALL" available variants, or only the one of interest (e.g. because they have associated phenotype/disease data)

**3. What would the data model look like?** 
    - Translator data model discussion is helpful: https://docs.google.com/document/d/1wjelHfyScFGasMbUKuEYa8HRTb_MwrZzSffIaxjt8vc/edit#heading=h.tkzguiojvxve 
    - Some groups make the distinction between a “variant” and an “allele”. This might not be necessary to make this distinction depending on the use cases. 
    - What information do we need to include (e.g. is “loss of function” enough?)?

**4. What are the variant data sources and what do they have?**
(the following includes a list of information available. This list is not exhaustive.)
    - Sources: ClinVar (Human data), Alliance (Mods data), Mods  (Mods data)
    - Data: variants, alleles, variants-alleles, variants-phenotypes, allele-phenotypes, variants/alleles-gene

**Comment by sabrinatoro** [comment]
Please move this issue to "discussion" or to another repository if this one is not appropriate. Thank you! 

@cmungall @putmantime @monicacecilia @kevinschaper @mellybelly @sagehrke  (note: I am unable to tag everyone here (e.g. Sierra doesn't show up on the list). Please tag or assign people as you see fit.  Thank you!

**Comment by monicacecilia** [comment]
Discussed during Monarch Data Call on 2023-10-25.
