### ISSUE TITLE
Interactions associations are duplicated

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#377]
Submitted via email, the submitter noticed when viewing [interactions for NLRX1](http://next.monarchinitiative.org/HGNC:29890?associations=biolink:PairwiseGeneToGeneInteraction) that outgoing associations are listed first, and all of the incoming associations are duplicates. 

| subject_label |       predicate        | object_label |
|---------------|------------------------|--------------|
| NLRX1         | biolink:interacts_with | TBK1         |
| NLRX1         | biolink:interacts_with | TLR3         |
| NLRX1         | biolink:interacts_with | TRAF6        |
| NLRX1         | biolink:interacts_with | TUFM         |
| NLRX1         | biolink:interacts_with | UQCRC2       |
| NLRX1         | biolink:interacts_with | NLRC4        |
| NLRX1         | biolink:interacts_with | IFIH1        |
| NLRX1         | biolink:interacts_with | RIGI         |
| NLRX1         | biolink:interacts_with | ATG16L1      |
| NLRX1         | biolink:interacts_with | FASTKD5      |
| NLRX1         | biolink:interacts_with | STING1       |
| NLRX1         | biolink:interacts_with | MAVS         |
| NLRX1         | biolink:interacts_with | EYA4         |
| NLRX1         | biolink:interacts_with | IFNB1        |
| NLRX1         | biolink:interacts_with | ATG12        |
| NLRX1         | biolink:interacts_with | ATG5         |
| NLRX1         | biolink:interacts_with | IKBKB        |
| NLRX1         | biolink:interacts_with | IKBKG        |
| NLRX1         | biolink:interacts_with | IRF3         |
| TBK1          | biolink:interacts_with | NLRX1        |
| TLR3          | biolink:interacts_with | NLRX1        |
| TRAF6         | biolink:interacts_with | NLRX1        |
| TUFM          | biolink:interacts_with | NLRX1        |
| UQCRC2        | biolink:interacts_with | NLRX1        |
| NLRC4         | biolink:interacts_with | NLRX1        |
| IFIH1         | biolink:interacts_with | NLRX1        |
| RIGI          | biolink:interacts_with | NLRX1        |
| ATG16L1       | biolink:interacts_with | NLRX1        |
| FASTKD5       | biolink:interacts_with | NLRX1        |
| STING1        | biolink:interacts_with | NLRX1        |
| MAVS          | biolink:interacts_with | NLRX1        |
| EYA4          | biolink:interacts_with | NLRX1        |
| IFNB1         | biolink:interacts_with | NLRX1        |
| ATG12         | biolink:interacts_with | NLRX1        |
| ATG5          | biolink:interacts_with | NLRX1        |
| IKBKB         | biolink:interacts_with | NLRX1        |
| IKBKG         | biolink:interacts_with | NLRX1        |
| IRF3          | biolink:interacts_with | NLRX1        |

I don't know whether we would prefer to solve this as an ingest issue or a display issue.

**Comment by kevinschaper** [comment]
If we replace STRING with BioGRID, this problem might miraculously disappear.

**Comment by RichardBruskiewich** [comment]
Then issue #438 will be prioritized...

**Comment by RichardBruskiewich** [comment]
@kevinschaper, with the potential resolution of #438, are you in a position to check if the duplications are still there?

**Comment by amc-corey-cox** [comment]
We have added BioGRID. Removing STRING and relying on BioGRID would solve this issue. However, we have received communication from Melissa that we should probably keep STRING, too. This may be related to #328 and exasperating that issue.

**Comment by kevinschaper** [comment]
I thought that https://github.com/monarch-initiative/monarch-ingest/pull/558 solved this, but I'm still seeing duplicates in the UI. This will need some investigation.

**Comment by RichardBruskiewich** [comment]
Not sure I know where to look... Might be good to trace just one identifier or edge from start to finish, to sort this out.

**Comment by kevinschaper** [comment]
It turns out that this issue went into monarch-ingest right after the last kg build, but was visible in the intermediate build for this release, so I'm closing it now.
