### ISSUE TITLE
Publication review comments, small UI fixes for Vince

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#378]
- Manually (in frontend) de-dupe autocomplete dropdown results? Or wait for backend to implement.
- Hide hierarchy section for genes (if not already done).
- ~Move associations (and breadcrumbs?) to right below overview section.~ Move heritability detail to overview section. Rename "Details" section to "Sources" (? or "Extra Info"), and move to bottom of page. Rename "Provided by" detail to "Source Documentation"? Discuss more tomorrow.
- Use taxon labels instead of ids in phenotype explorer dropdown results.
- Show breadcrumbs section even if there's no breadcrumbs, with blank message to the effect of: "As you navigate to new nodes from this page, the path you traveled through the KG will be shown here. Try clicking on a different node in the hierarchy or associations section."
- Auto-scroll to analysis section in phenotype explorer. Do in same way as scrolling down to evidence section on node page. Review all pages to see if there's anywhere else I need to do this.
- Look for broken links, e.g. on terms page to old /sources page.
- Change "Evidence" section to be "Association Details". Change "Evidence (4)" button to "Details" with tooltip "Show evidence (4), providence, and other info about this association." Backend will remove "providence" counts from the evidence count.

Other:

- Header search box doesn't change hash tab back to "search" when on phenotype explorer tab.

**Comment by amc-corey-cox** [comment]
Drop the Taxon column from Gene associations -> Interaction (or Orthology) Tables

**Comment by amc-corey-cox** [comment]
We have decided to do a quick-and-dirty de-dupe to the autocomplete as a first start: see #386
I volunteered to jump in and implement this but if you want to take it I won't be upset.

**Comment by vincerubinetti** [comment]
Please let me take care of it. This issue and sub-tasks are all slated to be done by tomorrow ~3pm EST.
