### ISSUE TITLE
Change logging mode for dev & production servers

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#380]
Right now we're getting a lot of log noise when solr_service prints out requests going out to solr. I was tempted to remove that, but  obviously it makes more sense to not run our API in debug mode all of the time.

**Comment by glass-ships** [comment]
see #381

**Comment by glass-ships** [comment]
https://pawamoy.github.io/posts/unify-logging-for-a-gunicorn-uvicorn-app/

This may be worth a read

**Comment by kevinschaper** [comment]
Moving to 2023-11 release, though we may end up bumping it further back

**Comment by kevinschaper** [comment]
Closing, it would be nice to sort out our python logging at some point, but right now I don't think we'd get enough benefit from it to dig in on that.
