### ISSUE TITLE
PR ALMOST READY: FB xrefs not linking, possibly others

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#383]
> Link outs to external sites….I was looking at a drosophila gene and noticed that there is not linkout directly to the flybase gene – why is that.  I think this might be the case with other databases.

**Comment by kevinschaper** [comment]
Sierra is helping us out with the proper fix for this in #382

**Comment by kevinschaper** [comment]
and it's merged, thank you @sierra-moxon !!

**Comment by matentzn** [comment]
I still think the proper way to do this would be a sssom widget with mapping metadata etc.. but ok for now
