### ISSUE TITLE
Prune duplicate names from autocomplete

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#386]
Original title: Add species of interest qualifying the different species entities for search
https://docs.google.com/document/d/1qdgn-FPNQbF1eRz2LnQIKzdcpRfhllRXo6eUdI8hPjY/edit#bookmark=id.f4r1gq7umi5k

No taxon or descriptions in searches. For example, EXOSC2 brings up 9 identical values with no species qualification. It would be useful to see the species of interest qualifying the different species entities in the drop-down so you could go immediately to the one of interest.

**Comment by amc-corey-cox** [comment]
Vincent comment:
We show taxon labels in the full search results. Are they referring to the autocomplete dropdown? If so, we're eventually supposed to have that as a taxon-agnostic and deduplicated list, just for the purposes of autocomplete (so the user doesn't have to finish typing). Then they go to the full results page. We discussed this at length and agreed it was the best decision to separate the searchbox autocomplete and full results like this, and NOT have a "go to node page immediately" button like UI v2.0. People would do one or the other, and not know the other functionality existed. Plus, there is no UI precedence that I know of for this. Going from autocomplete to full results page (requiring an extra click) is how google does it, and that should be good enough here.

**Comment by amc-corey-cox** [comment]
Moni comment:

Yes, they mean the autocomplete dropdown menu. 
I agree. it would be nice to see the species or the source where it belongs.

**Comment by amc-corey-cox** [comment]
More commentary:
RESPONSE from Vin: 
We show taxon labels in the full search results. 
Are they referring to the autocomplete dropdown? 
[vince.rubinetti@gmail.com](mailto:vince.rubinetti@gmail.com): Yes, they are.

If so, we're eventually supposed to have that as a taxon-agnostic and deduplicated list, just for the purposes of autocomplete (so the user doesn't have to finish typing). Then they go to the full results page. We discussed this at length and agreed it was the best decision to separate the searchbox autocomplete and full results like this, and NOT have a "go to node page immediately" button like UI v2.0. 

Vin: People would do one or the other, and not know the other functionality existed. Plus, there is no UI precedence that I know of for this. 
[vince.rubinetti@gmail.com](mailto:vince.rubinetti@gmail.com): Yes, there is. We still do it in the main Monarch site.

**Comment by amc-corey-cox** [comment]
We're going to start with a simple drop duplicates on the return from the autocomplete.

**Comment by amc-corey-cox** [comment]
https://stackoverflow.com/questions/53630395/how-to-remove-duplicate-values-in-autocomplete

**Comment by kevinschaper** [comment]
Let's start by removing any duplicates, case sensitively (so we allow for FGF8, Ffg8, fgf8). 

(we'll need to fetch more than the `limit` argument to be sure we still can reach the limit)

**Comment by vincerubinetti** [comment]
> [vince.rubinetti@gmail.com](mailto:vince.rubinetti@gmail.com): Yes, there is. We still do it in the main Monarch site.

I mean precedence on sites other than our own, i.e. the web at large. 

This was something we specifically found confusion with in our interviews with people using the UI v2.0.

**Comment by vincerubinetti** [comment]
@kevinschaper Do you want me to do this in the frontend either as a stopgap or as a permanent solution?

**Comment by amc-corey-cox** [comment]
Added to the top-level small-fixes issue: #378
