### ISSUE TITLE
Some diseases do not have descriptions, for example https://next.monarchinitiative.org/MONDO:0009684

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#390]
@twhetzel confirmed that around half (from memory, I hope I'm not getting that wrong) of all MONDO terms don't have a description. 

From the perspective of the app, I think we could probably nudge people towards the issue tracker where they could suggest a description?  

It also might be an interesting project to generate descriptions?

**Comment by twhetzel** [comment]
Here's my comment:
There are a total of 7,419 Mondo terms without a definition using this SPARQL query:
```
PREFIX rdf: <[http://www.w3.org/1999/02/22-rdf-syntax-ns#](https://www.google.com/url?q=http://www.w3.org/1999/02/22-rdf-syntax-ns%23&sa=D&source=docs&ust=1697127797909545&usg=AOvVaw1G8Ui2N7QIyxmUoYboq8vn)>
PREFIX rdfs: <[http://www.w3.org/2000/01/rdf-schema#](https://www.google.com/url?q=http://www.w3.org/2000/01/rdf-schema%23&sa=D&source=docs&ust=1697127797909728&usg=AOvVaw16WmhuvCoAn6A9f89VwzO3)>
PREFIX owl: <[http://www.w3.org/2002/07/owl#](https://www.google.com/url?q=http://www.w3.org/2002/07/owl%23&sa=D&source=docs&ust=1697127797909788&usg=AOvVaw0SLnuIUTNk_5db8bjXKuwL)>
PREFIX obo: <[http://purl.obolibrary.org/obo/](https://www.google.com/url?q=http://purl.obolibrary.org/obo/&sa=D&source=docs&ust=1697127797909850&usg=AOvVaw3WNaTgOcmgfkTnnh3Y0qnw)>

SELECT DISTINCT ?class
WHERE {
?class a owl:Class.
FILTER (CONTAINS(STR(?class), "MONDO")).
OPTIONAL { ?class obo:IAO_0000115 ?definition }
OPTIONAL { ?class owl:deprecated ?deprecated }
FILTER (!BOUND(?definition) && (!BOUND(?deprecated) || ?deprecated = "false"^^xsd:boolean))
}
```

NOTE: @matentzn later added to the thread in the "Monarch NAR 2024 - Reviews" the following:
The only thing that is needed here is to say that we are using Mondo for our source of disease information, and not all diseases have definitions. This is common place in the world of biomedical ontologies.

**Comment by twhetzel** [comment]
If there is an interest to put in a link to suggest a Mondo term definition within the Monarch site that sounds fine to me, but this added feature does not seem required to address the Review comment and Nico's comment above should be sufficient.

For a feature request, I would also be interested if @nicolevasilevsky and @sabrinatoro have experience with the quality of definitions (term suggestions) provided in this way.

**Comment by sagehrke** [comment]
@matentzn will add a response to the paper. No other action needed.
