### ISSUE TITLE
ALREADY FIXED: No info present for “Hierarchy for any gene”, is this section even relevant for gene?

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#392]
Vincent Rubinetti: We made a change somewhere to hide this section for genes I thought. Maybe it was in a PR that didn't get merged.

**Comment by amc-corey-cox** [comment]
Vincent: We made a change somewhere to hide this section for genes I thought. Maybe it was in a PR that didn't get merged.

**Comment by amc-corey-cox** [comment]
Glass: no, that change is definitely in on main: [https://github.com/monarch-initiative/monarch-app/blob/main/frontend/src/pages/node/SectionHierarchy.vue#L6](https://www.google.com/url?q=https://github.com/monarch-initiative/monarch-app/blob/main/frontend/src/pages/node/SectionHierarchy.vue%23L6&sa=D&source=docs&ust=1697127797885395&usg=AOvVaw3_h_V-xAykXaSiah1Bqhsr)

**Comment by amc-corey-cox** [comment]
They probably looked at it before we fixed it, there are other things mentioned that we've already fixed, like the lack of pombase genes
