### ISSUE TITLE
STRING is an aggregator

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#393]
Physical interactions appear to come from STRING, but STRING is an aggregator. Shouldn’t a primary curated data source like BioGRID or Intact be ingested? This would also allow the inclusion of primary publications (currently blank).

Harry Caufield: Worth noting that primary source PMIDs can also be retrieved from STRING

**Comment by sagehrke** [comment]
Review STRING ingest. Provide evidence the data is being passed through STRING or curated from BioGRID or Intact.
Action: (1) Provide better provenance. (2) See if we can find evidence.

**Comment by RichardBruskiewich** [comment]
Curating the primary knowledge source and publications can be done in the future; for the short term, we will add 'Evidence & Conclusion" codes to STRING edges, for all evidence categories with scores greater than zero

**Comment by RichardBruskiewich** [comment]
Partially resolved by https://github.com/monarch-initiative/monarch-ingest/pull/528.

**Comment by monicacecilia** [comment]
https://github.com/monarch-initiative/monarch-ingest/issues/533

**Comment by kevinschaper** [comment]
I'm inclined to close this and make a new issue for creating a BioGRID ingest

**Comment by RichardBruskiewich** [comment]
OK. Did Harry tell you where the STRING PMID's are lurking?

**Comment by sagehrke** [comment]
Closing. The BioGRID ingest is a different issue. Thank you!

**Comment by caufieldjh** [comment]
> OK. Did Harry tell you where the STRING PMID's are lurking?

For reference, these can be retrieved from the evidence portion of the STRING Postgres DB (as per here: https://stringdb-downloads.org/download/database.schema.v12.0.pdf) - and individually through their API (https://string-db.org/help/api/)
