### ISSUE TITLE
Community Engagement: How does one access the training and outreach pages from the Monarch initiative site? I thought I would find this info under the help menu but I didn’t.

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#395]

**Comment by matentzn** [comment]
The page (add as one of these cool circles on ["About" page](https://next.monarchinitiative.org/about)) should have roughly this layout:

# Monarch Outreach Activities

- [OBO Academy: Monarch Seminar Series](https://oboacademy.github.io/obook/courses/monarch-obo-training/): Training for Semantic Engineers, Ontology Curators and Knowledge Scientists on basic technologies in and around the Monarch Initiative and Open Biological and Biomedical Ontologies (OBO).
- Mondo monthly outreach call


@sagehrke can you add a bit of content here for @glass-ships to add?

**Comment by sagehrke** [comment]
### **Outreach**
The Monarch Initiative is a community effort, and we welcome your participation! 

### **Ways to Get Involved**

**[OBO Academy: Monarch Training Series](https://oboacademy.github.io/obook/courses/monarch-obo-training/)**
Training for Semantic Engineers, Ontology Curators, and Knowledge Scientists on basic technologies in and around the Monarch Initiative and Open Biological and Biomedical Ontologies (OBO). 
- The OBO Academy develops Self-paced tutorials in the OBOOK, hosts fortnightly live training sessions on Zoom, and maintains a YouTube channel with lesson recordings.
- Youtube channel: https://www.youtube.com/@obo-academy
- Join the OBO Academy mailing list using this [link](https://groups.google.com/g/monarch-tutorials)

**[Mondo Outreach Call](https://mondo.monarchinitiative.org/pages/workshop/#outreach)**
The Mondo Outreach calls aim to bring together stakeholders and clinical terminology experts to discuss specific use cases and requirements. Our goal is to improve Mondo with a focus on our user needs.
- These calls are scheduled on Fridays, every four weeks. You can find the schedule with links to the Zoom information [here](https://mondo.monarchinitiative.org/pages/workshop/#outreach) 
- Join the Mondo User mailing list using this [link](https://groups.google.com/g/mondo-users)

**[LinkML Community Meeting](https://linkml.io/linkml/)**
The LinkML Community Meeting aims to bring together users of the LinkML resource. These calls include tutorials, demos, and Q&A opportunities with the LinkML developers.  
- These calls are scheduled for the third Thursday of every month. You can find the schedule with Zoom information [here](https://docs.google.com/document/d/1MStpDyh9LOZYJTjLtnpOsNYc3HaeU-bz0CHAI9xOjfQ/edit#heading=h.6sqkx1xhumse)
- Join the LinkML Community LinkedIn group using this [link](https://www.linkedin.com/groups/14303246/)
- Join the LinkML Community mailing list [here](https://groups.google.com/g/linkml-community)
- Join the LinkML Community Slack [here](https://obo-communitygroup.slack.com/archives/C04EU7JL1NF)

### **Follow us to learn more!**
_(note for @glass-ships can these maybe be buttons?)_
- Monarch GitHub Organization: https://github.com/monarch-initiative
- Monarch LinkedIn Profile: https://www.linkedin.com/company/the-monarch-initiative/
- Monarch Blog: https://monarchinit.medium.com/ 
- Monarch YouTube Channel: https://www.youtube.com/@monarchinitiative

### **For questions or technical support**
We welcome all questions, requests, and feedback! 
Please submit your inquiry to our [Monarch Helpdesk](https://github.com/monarch-initiative/helpdesk), and we will connect you with someone who can help.

**Comment by sagehrke** [comment]
@nlharris @matentzn @monicacecilia  Anything else we should add to this new page? 
The one thing I can think of is this would be a great opportunity to make a new "Monarch User" google group and list the link for people to join. This could be the first step in making our user list we have been wishing and hoping for. What do you think?

**Comment by nlharris** [comment]
Adding a "Join the Monarch User group" link seems like a good idea to me!

I like your draft of the page content. For LinkML, I would suggest pointing to the LinkML site (https://linkml.io/linkml/faq/contributing.html) rather than reproducing links here that could end up needing to be updated in two places.

I would change the header "Mondo Outreach Call" to be "Mondo" (it's not just about calls) and add the call info to the first bullet point. For LinkML, I would change that whole section. Header could be "LinkML (the Linked data Modeling Language)", and below it you could note that LinkML is used by Monarch but also in many other projects. Then don't put any info about the calls or list, just a link to https://linkml.io/linkml/faq/contributing.html.

You can add me as a reviewer for the PR.

**Comment by glass-ships** [comment]
> can these maybe be buttons?

do you mean additional buttons on the About page? 
my only concern would be that it's getting a little crowded

**Comment by sagehrke** [comment]
> > can these maybe be buttons?

> do you mean additional buttons on the About page?
> my only concern would be that it's getting a little crowded

No, I meant on the Outreach page in that section. So have the Title "Follow up to learn more!" and then buttons (perhaps even the logo for each type of media) that links out. I am thinking like the little buttons on the footer of the website.

**Comment by sagehrke** [comment]
**Addition for @glass-ships ** 

Under the "Follow us to learn more!" section, add the following before the social media / link buttons:

> Stay updated on the latest from the Monarch Initiative by joining our user mailing list. [Click here](https://groups.google.com/a/tislab.org/g/monarch-users) to join.

**Comment by glass-ships** [comment]
@nlharris my only comment about the LinkML section is that https://linkml.io/linkml/faq/contributing.html doesn't contain information about the calls, mailing list, or linkedin group - would you still like to omit those bullet points?

**Comment by nlharris** [comment]
Hmm, then I guess we need to add those things to the LinkML website (or decide if we don't want to make them that public). I will pursue that. I don't think the Monarch website is the right place for that info, so you can just point to that contributing page and I'll look into adding the missing info to that.

**Comment by nlharris** [comment]
https://github.com/linkml/linkml/issues/1669

**Comment by sagehrke** [comment]
@glass-ships apologies. **Please remove this**. It is not ready for primetime. 

>Under the "Follow us to learn more!" section, add the following before the social media / link buttons:
>Stay updated on the latest from the Monarch Initiative by joining our user mailing list. [Click here](https://groups.google.com/a/tislab.org/g/monarch-users) to join.

**Comment by sagehrke** [comment]
**Updates needed to https://dev.monarchinitiative.org/outreach before launch:**

- Change wording of the second bullet point from "These calls are scheduled for the second Thursday of every month. You can find more information about the calls [here](https://mondo.monarchinitiative.org/pages/workshop/#outreach)." to 
"These calls are scheduled monthly. You can find more information about the calls [here](https://mondo.monarchinitiative.org/pages/workshop/#outreach).

- Remove third bullet point "You can find the schedule with Zoom information [here](https://docs.google.com/document/d/1MStpDyh9LOZYJTjLtnpOsNYc3HaeU-bz0CHAI9xOjfQ/edit#heading=h.6sqkx1xhumse)."

![Image](https://github.com/monarch-initiative/monarch-app/assets/99770056/31bdd4e1-ec6b-41d2-8561-8ab65790cc51)


- Remove this section on LinkML - it is no longer relevant since it does not give any information on how to be involved. We will add information on LinkML when we integrate more info on Monarch products to the site. 

![Image](https://github.com/monarch-initiative/monarch-app/assets/99770056/96c12958-7653-4371-a791-42de0bdb20d0)


- Move the Mondo Section above the OBO Academy section. 
- Update the link in this sentence "Join the OBO Academy mailing list [here](https://groups.google.com/g/monarch-tutorials)" --- it is currently broken. 

@glass-ships
