### ISSUE TITLE
Members (current and alum) with missing/dead links

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#399]
MISSING/DEAD LINKS

Current:
- ~~Bryan Laraway~~
- Leigh Carmody
- Nomi Harris
- Sebastian Köhler
- Jules Jacobsen
- Nicolas Matentzoglu

Alum: 

- David Osumi-Sutherland
- Kent Shefchek
- Victoria Alexandra Soesanto
- Vida Ravanmehr
- Deepak Unni
- Eric Douglass
- Sarah Kim
- Jeremy Nguyen Xuan
- Nicole Washington
- Tomasz Konopka
- Jen Martin
- Tom Conlin
- Lilly Winfree
- Tudor Groza
- Craig McNamara
- Edwin Zhang
- Michael Davis
- Zhou (Joe) Yuan
- Charles Borromeo
- Jeremy Espino

LINKS TO GOOGLE SCHOLAR

- Seth Carbon
- Suzanna Lewis

**Comment by glass-ships** [comment]
RE: comment from #304 

Would be acceptable / in poor taste to google some members to get updated links?

Should we reach out to them to find a link?

**Comment by sagehrke** [comment]
Here are my thoughts on this: 

- My opinion on this is only current members have links to more information about themselves, including email. All alumni can be listed, but no links should be connected to them. It is too hard to keep links up to date on people we no longer (or rarely) interact. So the action here would be to remove links associated with alumni @glass-ships. Glass before you do this, @nlharris would you agree with this strategy?  
- Sebastian's image is a circle, while the rest are square. Let's update it to be a square. @glass-ships 
- Let's make sure to compare the list on the website with the latest member list. I can do this and share updates needed with @glass-ships (this update is in progress, so I will need a few weeks to finalize it)
- I can also support connecting with people to obtain their links / photos as needed and will share with @glass-ships to add.

**Comment by glass-ships** [comment]
> Sebastian's image is a circle, while the rest are square. Let's update it to be a square. 

This is more #304 related, but we _cant_ update it to be a square unless he sends us a new picture. The one he has is white with a circle background

> I can also support connecting with people to obtain their links / photos as needed and will share 

That would be great. messaged you on slack with what contact info i managed to find.

**Comment by nlharris** [comment]
@sagehrke I agree with your strategy!
