### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-app#4]
@sierra-moxon has some experience in doing this for a FastAPI endpoint

**Comment by glass-ships** [comment]
This was a while ago, and we now have a couple GitHub actions for testing and such. 

Was there something specific in mind here?

**Comment by putmantime** [comment]
@glass-ships Could you give a little bulleted list of what we have here in a comment and we can review

**Comment by glass-ships** [comment]
The current actions are listed [here](https://github.com/monarch-initiative/monarch-api/actions)
We have actions to: 
- build and push the monarch api docker iamge
- build and deploy documentation
- install the backend and run pytest
- install the frontend and run linting, accessibility, e2e, etc teseting

**Comment by glass-ships** [comment]
I'm gonna close this for now, and if we think of anything else we might need, we can open up a new ticket for it!
