### ISSUE TITLE
Add "How to" page on the Monarch App

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#400]
Create a page in the Monarch App that details how to use and interpret various functions of the site, including definitions of common terms. This can also be done with the hover-over text info bubbles if that makes more sense.

**Comment by monicacecilia** [comment]
Possible contents: 
1. How to search and use information about a node (disease, phenotype, etc)
2. How to use the Phenotype Comparison tool
3. How to find additional info about team and other tooling

**Comment by amc-corey-cox** [comment]
Vince and I discussed this issue. He is a little uncomfortable with creating a dedicated "Howo to" page to contextualize the use of the website. Instead, he'd rather incorporate whatever help-text or explanatory information directly into the UI of the website.

Some ideas we tossed around were to have a "helpful mode" that gives greater context and information overlaid on the interface. Alternatively, we could have different perspectives applied, i.e. "I'm a doctor and I want to..." with overlay on how to do these things.

**Comment by amc-corey-cox** [comment]
Part of the reasoning on this is that if we need a dedicated "How to" page, we have probably missed the mark on the UI and need to improve the UI instead.

We do think it is valuable to do research on what use-cases are that we need to build towards and how to incorporate these into the UI.

**Comment by amc-corey-cox** [comment]
Also, if we want to produce these videos as items to hype the new Monarch App/UI this is probably a great use but we don't want to leave these getting stale on the website. Especially, we don't want to have to try to maintain this as we continue to improve the UI.

**Comment by amc-corey-cox** [comment]
As an example, this video on our about page is great but it is already out-of-date. 
https://monarchinitiative.org/about

This is fine on something like an about page but if we're creating a "How to" page people are going to expect it to be current.

**Comment by amc-corey-cox** [comment]
I'm bumping this to our next Milestone so Moni and I have some time to talk about it and get some ideas on how to move forward in light of Vince's statement that How to's are sometimes an indicator that UI needs improvement.

**Comment by sagehrke** [comment]
Related #567

**Comment by amc-corey-cox** [comment]
Another possible resource is Michael Gargano. michael.gargano@jax.org

**Comment by amc-corey-cox** [comment]
Shepherd was suggested as an option for how to guide users on our site:
https://shepherdjs.dev/
