### ISSUE TITLE
Documentation about data sources should include citations

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-app#404]
As pointed out by a reviewer of the Monarch NAR paper, we should add citations to our data sources (as we would want other to do for us -- it's the golden rule of data sharing).

For example, https://monarch-initiative.github.io/monarch-ingest/Sources/zfin/ (I checked that the new site still points to these pages for data sources) should have the citation:
> Bradford, Y.M., Van Slyke, C.E., Ruzicka, L., Singer, A., Eagle, A., Fashena, D., Howe, D.G., Frazer, K., Martin, R., Paddock, H., Pich, C., Ramachandran, S., Westerfield, M. (2022) Zebrafish Information Network, the knowledgebase for Danio rerio research. Genetics. 220(4). PMID: 35166825  PMCID: [PMC8982015](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc8982015/)  DOI: [10.1093/genetics/iyac016](https://doi.org/10.1093/genetics/iyac016)

**Comment by glass-ships** [comment]
Thanks @nlharris 

Are the citations we collected in this [google doc](https://docs.google.com/spreadsheets/d/1uPI6MLm50WU0bdkOS6AiFGeS7SJ9FfjqwEAeCrpNF7A/) suitable for adding to these pages?

**Comment by nlharris** [comment]
Yes, at a quick glance they look suitable!

**Comment by glass-ships** [comment]
Resolved by https://github.com/monarch-initiative/monarch-ingest/pull/532
