### ISSUE TITLE
List of data sources is out of date

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-app#405]
According to @cmungall, https://monarch-initiative.github.io/monarch-ingest/Sources/ is out of date. (This is an old page but the new site points to it.)

See also #404 and https://github.com/monarch-initiative/QC/issues/29

**Comment by kevinschaper** [comment]
Need to remove:

- [x] Alliance Gene to Disease
- [x] Consider removing/hiding dictyBase, until it's present in phenio?
- [x] Xenbase gene to phenotype

Hide but not remove?  (we haven't prioritized publications + entity to pub associations, but presumably we'll get back to them?)
- [x] Flybase gene literature
- [x] MGI gene literature
- [x] RGD gene literature
- [x] SGD gene literature
- [x] Xenbase gene literature

**Comment by glass-ships** [comment]
https://github.com/monarch-initiative/monarch-ingest/pull/532
