### ISSUE TITLE
Link out from Association Details

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#408]
<img width="789" alt="Screenshot 2023-10-17 at 11 05 38 AM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/43511efa-7b9e-4353-a31f-d1cafe010f80">

We need to link out from the association details. We should link provided_by to our docs, infores to the infores wiki (I think?) and publications and evidence code curies should get expanded with the curies library. 

That means that this needs to start on the backend to provide urls the api, and move to the frontend to actually use the urls.

**Comment by glass-ships** [comment]
Seems like we do have code to handle this in `SectionAssociationDetails`

```
      <AppDetail title="Provided By" icon="notes-medical">
        <AppLink :to="association.provided_by_link?.url || ''">
          {{ association.provided_by_link?.id || association.provided_by }}
        </AppLink>
      </AppDetail>
```

but it doesn't seem to be finding the url, even if it is provided. 

maybe @vincerubinetti has some idea why that might be the case? 

(I've confirmed the url exists for Ehlers Danlos syndrome (MONDO:0020066) but the AppLink still defaults to the text - see below)

```
$ monarch associations -e MONDO:0020066

...
      "provided_by": "hpoa_disease_to_phenotype_edges",
      "provided_by_link": {
        "id": "hpoa_disease_to_phenotype",
        "url": "https://monarch-initiative.github.io/monarch-ingest/Sources/hpoa/#disease_to_phenotype"
      },
      "publications": [
        "OMIM:225400"
      ],
      "qualifiers": [],
      "frequency_qualifier": null,
      "has_evidence": [
        "ECO:0000501"
      ],
...
```

**Comment by vincerubinetti** [comment]
I'm using this endpoint, which I can confirm _does not_ have the link information:

https://next.monarchinitiative.org/v3/api/entity/MONDO:0020066/biolink:DiseaseToPhenotypicFeatureAssociation

```
"provided_by": "hpoa_disease_to_phenotype_edges",
"provided_by_link": null,
```

**Comment by glass-ships** [comment]
Ah, right. that comes from the directional association endpoint, which we're not even really using anymore. 

I'll make a PR to switch that over - thanks vince!

**Comment by vincerubinetti** [comment]
You're using something different for the associations endpoint now? That affects a bunch of components and will be a little difficult. It affects the summary view, table view, and evidence view.
