### ISSUE TITLE
Attribution for GO data is always GOA

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/monarch-app#426]
**Please describe your question, suggestion, or concern.**

Data is ingested from GOA, but GOA is a third party DB and this isn't the "provided by" source. The primary source is in the "assigned by" column.
Also for all cases I looked at the publication is '0' for experimentally sourced data.

See for example:

https://monarchinitiative.org/PomBase:SPAC20H4.06c?associations=biolink:MacromolecularMachineToMolecularActivityAssociation

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q9HE07&aspect=molecular_function

**Comment by kevinschaper** [comment]
This is a great point @ValWood - thank you! We'll get it fixed in our ingest for our next release in November.

**Comment by RichardBruskiewich** [comment]
Resolved by https://github.com/monarch-initiative/monarch-ingest/pull/543
