### ISSUE TITLE
Show Mondo mappings in Mondo pages (again)

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#427]
Comparing https://previous.monarchinitiative.org/disease/MONDO:0007947 with https://monarchinitiative.org/MONDO:0007947

In the new website, I cannot see the mappings we displayed in the ‘External Resources’ section on the old website. 
I am unable to find information about:
Clinical Synopsis
Clinical Information for patients
Other Mappings

Requested action: to show Mondo mappings in Mondo pages (again). The source of these mappings will be SSSOM. 

Thank you! 🌷

screenshot with old info from ‘previous’ 
<img width="622" alt="Screen Shot 2023-10-21 at 4 39 44 PM" src="https://github.com/monarch-initiative/monarch-app/assets/1714621/f257ed8d-3f91-4d7e-a47c-35cb6a022a0b">

**Comment by kevinschaper** [comment]
I got the SSSOM mappings loaded up into Solr, and @glass-ships got the generic SSSOM API endpoint up and running. 

Next we need to supply the mappings in our entity page response. It's a little challenging that we're potentially suppling both xrefs and mappings for a given entity - I think keeping them separate, and supplying both, is the most clear. 

in pseudo-monarch-app code, it should be
```
entity.mappings = [make_expanded_curie(get_other_entity(this_entity, mapping) for mapping in get_mappings(entity_id=<this node>)]
```

**Comment by matentzn** [comment]
Keeping them visually very separate is best - eventually we should replace this by a sssom-api widget, but for now I agree with you
