### ISSUE TITLE
Add BioGRID ingest 

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#438]
Feedback from reviewers and @cmungall pointed out where our STRING ingest is producing associations that are lacking in information relative to what we had from Dipper's BioGRID ingest. 

https://downloads.thebiogrid.org/File/BioGRID/Release-Archive/BIOGRID-4.4.226/BIOGRID-ALL-4.4.226.mitab.zip

This is a big improvement, in that the file has both pubmed identifiers and interaction types. We will be able to map from the NCBI Gene IDs to our preferred gene IDs. 

has columns: 
     1  #ID Interactor A
     2  ID Interactor B
     3  Alt IDs Interactor A
     4  Alt IDs Interactor B
     5  Aliases Interactor A
     6  Aliases Interactor B
     7  Interaction Detection Method
     8  Publication 1st Author
     9  Publication Identifiers
    10  Taxid Interactor A
    11  Taxid Interactor B
    12  Interaction Types
    13  Source Database
    14  Interaction Identifiers
    15  Confidence Values

with the first row looking like:
     1  entrez gene/locuslink:6416
     2  entrez gene/locuslink:2318
     3  biogrid:112315|entrez gene/locuslink:MAP2K4|uniprot/swiss-prot:P45985|refseq:NP_003001|refseq:NP_001268364
     4  biogrid:108607|entrez gene/locuslink:FLNC|uniprot/swiss-prot:Q14315|refseq:NP_001120959|refseq:NP_001449
     5  entrez gene/locuslink:JNKK(gene name synonym)|entrez gene/locuslink:JNKK1(gene name synonym)|entrez gene/locuslink:MAPKK4(gene name synonym)|entrez gene/locuslink:MEK4(gene name synonym)|entrez gene/locuslink:MKK4(gene name synonym)|entrez gene/locuslink:PRKMK4(gene name synonym)|entrez gene/locuslink:SAPKK-1(gene name synonym)|entrez gene/locuslink:SAPKK1(gene name synonym)|entrez gene/locuslink:SEK1(gene name synonym)|entrez gene/locuslink:SERK1(gene name synonym)|entrez gene/locuslink:SKK1(gene name synonym)
     6  entrez gene/locuslink:ABP-280(gene name synonym)|entrez gene/locuslink:ABP280A(gene name synonym)|entrez gene/locuslink:ABPA(gene name synonym)|entrez gene/locuslink:ABPL(gene name synonym)|entrez gene/locuslink:FLN2(gene name synonym)|entrez gene/locuslink:MFM5(gene name synonym)|entrez gene/locuslink:MPD4(gene name synonym)
     7  psi-mi:"MI:0018"(two hybrid)
     8  "Marti A (1997)"
     9  pubmed:9006895
    10  taxid:9606
    11  taxid:9606
    12  psi-mi:"MI:0407"(direct interaction)
    13  psi-mi:"MI:0463"(biogrid)
    14  biogrid:103
    15  -

**Comment by sagehrke** [comment]
This should address #377

**Comment by RichardBruskiewich** [comment]
Substantially resolved by https://github.com/monarch-initiative/monarch-ingest/pull/549
