### ISSUE TITLE
Change default compare behavior to only using is_a predicate

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#447]
Right now we're passing all 3 predicates from our closure in for the compare endpoint, but we should only use the is_a predicate.

I think this is probably a semsimian-server change.

**Comment by kevinschaper** [comment]
We should go from 

```
    let predicates: Option<Vec<Predicate>> = Some(vec![
        "rdfs:subClassOf".to_string(),
        "BFO:0000050".to_string(),
        "UPHENO:0000001".to_string(),
    ]);
```

to 

```
    let predicates: Option<Vec<Predicate>> = Some(vec![
        "rdfs:subClassOf".to_string(),
    ]);
```

**Comment by glass-ships** [comment]
See latest commit for details: https://github.com/glass-ships/semsimian-server/commit/4708dc5061cbe1d9ab1c8233d544db3111cee373
