### ISSUE TITLE
phenodigm_score is getting `string` type in typescript

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#449]
I see that in model.yaml it's defined as a float, and then in similarity.yaml's own score is commented out, and then it has fields that inherit from score. I think this is likely a problem with the typescript generator in linkml that we'll need to fix.

**Comment by glass-ships** [comment]
i had a look through typescript-gen but couldn't see where the relevant code would be. any ideas?

**Comment by glass-ships** [comment]
Would be closed by https://github.com/linkml/linkml/pull/1700

**Comment by glass-ships** [comment]
that PR has been merged, model has been regenerated with latest commit of linkml (release on the way, will update when it's out)
