### ISSUE TITLE
Copy monarch-ui-new into frontend directory plus GitHub action for tests

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#47]
To start building towards our mono-repo, let's bring monarch-ui-new into the frontend directory. We need to make sure that the Makefile that generates the typescript interfaces writes to a good location after it's brought in, and we should set up a github action to run the tests for each PR. 

For this PR, let's leave monarch-api in place. We'll want to move it down into a backend directory, but I don't think that's strictly necessary in this PR.

**Comment by glass-ships** [comment]
Being worked on in #48

**Comment by glass-ships** [comment]
Addressed by PR #48
