### ISSUE TITLE
Add a shortcut from disease pages to compare (and eventually search)

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#475]
Thinking my way through a UI demo that will go from from search, to a disease page, and then to phenotype compare. It occurred to me that it's a little awkward that I'll be on `Ehlers-Danlos syndrome, hypermobility type` page, and then if I want do compare it against other diseases, that I need to navigate out to the compare tool and type the name again. 

I think there's more that we'll be able to do in the long run to bring phenotypic similarity to the node pages, but to get a start on that, I think we should have some affordance (link? button? maybe it's somehow inline and you choose the other disease or collection of phenotypes right on the page?) that will allow for doing a comparison using the disease that you're currently viewing.

**Comment by vincerubinetti** [comment]
I think this is a good idea, and the cleanest and easiest way to do it probably is just by having a button like "Send to Phenotype Explorer". We have something like that on the (inactive) text annotator page, which just remembers a list of phenotypes, navigates to the phenotype explorer, and pre-populates the first (set A) box.

To me the logical place for this would be at the top of the associations section, and only present when the node page is a disease and the selected association type is phenotype.
