### ISSUE TITLE
Koza support to post-process input files to remove hash ('#') comment prefix characters in a header line. 

### ISSUE THREAD

**Issue by RichardBruskiewich** [monarch-initiative/monarch-app#477]
BioGRID 'mitab' download files have header lines with hash ('#') comment prefix characters. The Monarch ingest download process needs to detect and remove these syntactic characters to avoid parsing issues.

**Comment by matentzn** [comment]
SSSOM has the same. Note there is a risk using pandas "comment" parameter: its possible values in the table contain hashes.

**Comment by kevinschaper** [comment]
Adding 2023-12 milestone, but we want this early in the process to go with the BioGRID ingest

**Comment by glass-ships** [comment]
@RichardBruskiewich sorry i'm not entirely following, can you provide a little extra context? 

Is it that Koza is trying to process lines starting with `#` as if they're rows of data?

**Comment by RichardBruskiewich** [comment]
Hi @glass-ships (cc: @kevinschaper),

I can't speak for Nico's example of SSSOM, but the use case which inspired this issue is that the **BioGRID** input file at **https://downloads.thebiogrid.org/Download/BioGRID/Release-Archive/BIOGRID-4.4.226/BIOGRID-ALL-4.4.226.mitab.zip** (a [**"MITAB" formatted file**](https://wiki.thebiogrid.org/doku.php/psi_mitab_file#:~:text=The%20MITAB%20format%20is%20part%20of%20the%20PSI-MI,interactions%20per%20row.%20Columns%20are%20separated%20by%20tabulations.), when unzipped) is a regular TSV text file with headers, except that the header line (**_only_**) has a leading hash ("#") character, which gets in the way of parsing the header, to get at the columns of data in the table.

This issue here merely suggests that we figure out how to:

1. strip the leading hash character away during post-download processing of the file, and possibly
2. have a way of signalling that this pro-processing needs to be done for a given header (i.e. as some kind of special 'header' directive in the ingest YAML configuration file).

If not the above, I'm pleased to follow whatever 'best practices' are needed to get the input file properly read into the BioGRID ingest script.

**Comment by glass-ships** [comment]
Ahhh I'm starting to understand, yeah. that is... interesting for sure. 
I'll need to chew on this a bit to think of a good way to approach this. 

A dirty "in the meantime" approach would be to post-process separately in a script in monarch-ingest, prior to the ingest itself. 

As for Koza - one option would be to have a config yaml paramater that either tells koza (a) to look for a header leading-character, or (b) that a post-processing script exists and needs to be run on the data prior to performing any transforms. 

My main concern (not necessarily in the biogrid case, but in other potential ingests that might need to use this) would be any possible conflicts, ie. if a file has metadata/comments with a leading `#`, as well as a header line with a leading `#`. But maybe that's a niche and general enough consideration to not be worth worrying about just yet. 

I'll work on #476 in the meantime, and maybe we can get feedback from @kevinschaper when he returns from his well earned vacation

**Comment by glass-ships** [comment]
So I've made a [Koza PR](https://github.com/monarch-initiative/koza/pull/117) to resolve this. 

However, a recent release updated the minimum Pydantic in Koza to Pydantic V2. 

Which means to update it in Monarch Ingest requires updating to Pydantic V2 here as well. 

There is a branch to address this: https://github.com/monarch-initiative/monarch-ingest/pull/551 and is also ready for review,
once these two PRs get a review, biogrid should be ready to move forward
