### ISSUE TITLE
Prepare for V1 & V2 shutdown

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#484]
This should happen on when we release the 2023-12: 
- [x] Serve a page at https://api.monarchinitiative.org that explains how to continue accessing the api, and the shutdown date
- [x] Create a DNS entry for api-v2.monarchinitiative.org that points to SOM gcp load balancer 
- [x] Serve V2 api from api-v2.monarchinitiative.org 
- [x] Point previous.monarchinitiative.org at api-v2.monarchinitiative.org

**Comment by sagehrke** [comment]
Proposed Timeline for the V1 and V2 shutdown to happen (this is based on notes from the December 20th, 2023 Infrastructure meeting):

- [x] 2024-Jan-17: Populate Friends of Monarch Mailing List & blast on socials @sagehrke 
- [x] 2024-Feb-07: Implement the "Soft Break"  
- [ ] Outreach
   - [ ] Send warning messages to Friends of Monarch mailing list to include: What is being brought down, what system it will effect, potential replacement and who to contact. Send them on the following dates:
     - [x] 2024-Jan-24: 8 weeks before shutdown
     - [x] 2024-Feb-07: 6 week before shutdown + announce soft break  
     - [x] 2024-Feb-28: 4 weeks before shutdown
     - [ ] 2024-March-13: 1 week before shutdown
     - [ ] 2024-March-20: day of shutdown
   - [x] Ping LinkedIn page on the same timeline
   - [x] @amc-corey-cox and @kevinschaper are to draft these messages 
- [ ] 2024-March-20: shutdown

FYI: @monicacecilia

**Comment by amc-corey-cox** [comment]
Here is the document for the current communication:

https://docs.google.com/document/d/1Q9PcCKI7qO9Tbt2Hkk89SMyriWupsQPe7cZe-KTKKPI/edit

**Comment by sagehrke** [comment]
The blog with a timeline and information on how to contact us for help can be found here: https://monarchinit.medium.com/migrating-to-the-new-monarch-infrastructure-fe9d98ccf64a

**Comment by kevinschaper** [comment]
Nothing else to do for this in the context of this issue/milestone
