### ISSUE TITLE
Update Team Page on UI - summary of all changes 

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#489]
@glass-ships This ticket is a summary of the Team page updates mentioned in the following tickets: 
- [x] https://github.com/monarch-initiative/monarch-app/issues/74
- [x] https://github.com/monarch-initiative/monarch-app/issues/304
- [x] https://github.com/monarch-initiative/monarch-app/issues/399

Please address the previous comments on the above tickets and the new information below. 

Next steps:
- Cross check the list of members in the "MonarchTeam" tab of the **The Monarch Initiative contact list** [not linking here as it is a private document - see Slack message from me with the link] with what is already listed on the website Team page. 
  - Identify who needs to be added or removed 
  - Confirm who needs a new headshot and who is missing a link to their info page on an external site. 
    - Share this list with me in a google sheet on Slack so I can help ping folks. 
- Reminder from the tickets listed above - we are only listing the alumni with their names - no photos or links
- SAB members will be added before the alumni section. Include photos and links. 

Note: it seems reasonable to finish this for the December release. To clean this up for the new year, if we are missing some current member pictures or links, let's still push this out for Dec 14th so we can close these tickets. Anything left over and still needing an update can be made into a new January ticket with specific additional needs addressed.

**Comment by glass-ships** [comment]
Addressing in #487
