### ISSUE TITLE
ZP:0143081 not found on monarch site

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#496]
Looking at the google search console complaints for pages that aren't found, I saw this ZP term, and sure enough, we don't have this node in our KG. 

It seems like it may be a phenio issue.

**Comment by caufieldjh** [comment]
Yep, I don't see this term in PHENIO.
I do see some, but not all, of its [child terms](http://purl.obolibrary.org/obo/ZP_0143081), for example:
ZP:0137238 is present.
ZP:0144045 is not present.

**Comment by caufieldjh** [comment]
And there's a pretty good reason why: PHENIO doesn't include ZP. Just ZFA.
So perhaps it is time to bring it in.

**Comment by matentzn** [comment]
OMG... did fixing the base_iris of the uPheno import work?

**Comment by caufieldjh** [comment]
As far as I know, it worked - but ZP_0143081 and some of its child terms (like ZP_0144045 from above) aren't in Upheno2.

**Comment by sagehrke** [comment]
Hi @matentzn and @caufieldjh can you please share an update on this ticket? Including an approximate timeline for the fix. Thank you!

**Comment by matentzn** [comment]
@caufieldjh I have updated uPheno2, when you update PHENIO you should see all the missing classes. This issue can be closed as soon as you verify that the new PHENIO has those ZP ids!

**Comment by caufieldjh** [comment]
Thanks @matentzn - building new PHENIO today.

**Comment by caufieldjh** [comment]
The missing ZP IDs are now in the [latest PHENIO release](https://github.com/monarch-initiative/phenio/releases/tag/v2024-01-04).
