### ISSUE TITLE
Create strategy to report what is included in each Monarch KG/App release

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#507]
I'd like to start an initiative to make a summary of all things included in a monthly release starting in 2024. We have our Milestones for reference that I can help pull information from. But I am curious as to what would be an easy, but useful way, to collect the information. Ultimately, I hope we will have release emails to our users each month once we have a better user mailing list (in progress...), and this monthly summary would be the basis for that. 

Do you all have any ideas for how to collate this info?  My immediate thought is a Google doc that we can add to each month. But if there is a GH hack we can use instead, I would be happy with that too. 

This ticket is meant to discuss strategy and ideas. Ultimately, our final decision around this should be added to our Release SOP #344

**Comment by sagehrke** [comment]
Request for ideas from @kevinschaper @glass-ships @amc-corey-cox @matentzn and anyone else interested in documentation strategy.

**Comment by glass-ships** [comment]
GitHub Releases would kinda do exactly this. 

The button to automatically generate release notes by default creates a list of all PRs that were merged between the last and current releases:

![image](https://github.com/monarch-initiative/monarch-app/assets/26975530/bd11eff8-e95d-4578-acb6-bafcdea79020)

We currently only use releases to publish the backend (monarch-py) to PyPi whenever we push changes past dev to the production site as it is, so in a way we might already be doing this

**Comment by kevinschaper** [comment]
I think we should probably just go for it on making a release in monarch-ingest, even though the first one is going to be a little bit of a nightmare, since it might want to bring in every PR from the start. 

What it won't capture that I really would like to have is the versions of everything we bring in. We really should label which version of Phenio, Mondo, HPO, Alliance, bGee, etc that we have in a build of the KG.

**Comment by amc-corey-cox** [comment]
I endorse bite the bullet and do it even if it's a real mess. We can sort it out later if we need to. Also, can we manually edit the generated release notes afterward if we want to?

**Comment by amc-corey-cox** [comment]
> What it won't capture that I really would like to have is the versions of everything we bring in. We really should label which version of Phenio, Mondo, HPO, Alliance, bGee, etc that we have in a build of the KG.

Could we make this a variable set in GitHub and pull it in?

**Comment by glass-ships** [comment]
> can we manually edit the generated release notes afterward if we want to?

yep!

**Comment by monicacecilia** [comment]
Yes, this sounds like our discussion. Wonderful! 🎉

**Comment by sagehrke** [comment]
Hi all - Just checking in -- the Friends of Monarch mailing list has been revitalized and can be used for sending out monthly release updates. Should we try this for the first time in February or March release? @kevinschaper @monicacecilia

**Comment by kevinschaper** [comment]
We should look at whether we can copy files from the gcp release bucket into a release GitHub action based on the release name. 

Edit to add: we should have the ingest Jenkins job automatically create a draft release, which might make it easier to capture the phenio/mondo/hpo versions at the moment of ingest.

**Comment by monicacecilia** [comment]
I would like to see 1) release notes and 2) a change log. 

Ideally, release notes that highlight critical changes, list helpful improvements, and link to a ChangeLog that lists various other bug fixes, etc. Examples: See Release notes at https://github.com/GMOD/Apollo/releases and ChangeLog at https://github.com/GMOD/Apollo/blob/develop/ChangeLog.md

**Comment by kevinschaper** [comment]
I was hoping we could have a pre-populated markdown template for releases that would auto populate, but it looks like that's only available for pull requests. None the less, I think a template to manually populate is probably a good starting place.

**Comment by monicacecilia** [comment]
With work from https://github.com/monarch-initiative/monarch-ingest/pull/561

**Comment by kevinschaper** [comment]
I built the release notes from a combination of autogenerated release notes and our milestone goals, I think the process worked well
