### ISSUE TITLE
getting gene-phenotype associations via the api

### ISSUE THREAD

**Issue by ChristopherMancuso** [monarch-initiative/monarch-app#516]
I would like to retrieve the genes annotated to a given a given phenotype term using the api. It would be nice to get this in a format that ignores almost all other information about the phenotype in question and just returns gene annotations. For diseases, setting the `category` to `biolink:CorrelatedGeneToDiseaseAssociation` returns this subset.
https://api-v3.monarchinitiative.org/v3/api/association?category=biolink%3ACorrelatedGeneToDiseaseAssociation&entity=MONDO%3A0012933&direct=false&limit=20&offset=0

however I don't think there is a `category` called `biolink:CorrelatedGeneToPhenotypeAssociation` as the following returns nothing
https://api-v3.monarchinitiative.org/v3/api/association?category=biolink%3ACorrelatedGeneToPhenotypeAssociation&object=HP%3A0001263&limit=20&offset=0

Is there a way to retrieve just gene annotations for a given phenotype term? 

From the old api maybe something like
https://api.monarchinitiative.org/api/bioentity/phenotype/HP%3A0001263/genes?rows=100&facet=false&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=true&direct=false&direct_taxon=false

which was called using 
`/bioentity/phenotype/{id}/genes` and setting `use_compact_associations` to true and `id` to HP:0001263

I don't think these annotations are propagated, but this would be a good start for getting annotations.

Thanks for any help!

**Comment by ChristopherMancuso** [comment]
With the above post, is there a way to find the list of all available `categories` for an api call?

**Comment by kevinschaper** [comment]
Hi @ChristopherMancuso,

Sorry for not replying to this one earlier. I saw the second note and had a realization that an early tester of the API had mentioned the same challenge that we aren't exposing the values category and predicate fields, and we'd been so focused on supporting our new UI that we hadn't gotten to it - but it's so necessary!

I think we should have enumerations for categories and predicates showing up in the Swagger UI by the end of the week.

**Comment by ChristopherMancuso** [comment]
Awesome, thanks!

**Comment by kevinschaper** [comment]
I just confirmed that the enumerations are showing up on api-beta.monarchinitiative.org, so I'm going to close this issue now. Assuming all of the issues in the release look good, I think the enumerations should be visible on api-v3.monarchinitiative.org later on this evening.
