### ISSUE TITLE
Phenotype-Explorer: No associated phenotypes found

### ISSUE THREAD

**Issue by amc-corey-cox** [monarch-initiative/monarch-app#523]
When clicking in the text fields here:

https://dev.monarchinitiative.org/explore#phenotype-explorer

I dropdown is generated to give suggestions. When no text is entered this drops down with a list of suggestions that aren't useful. Clicking on the first ~10 gives the message "No associated phenotypes found". We either need to properly associate phenotypes with these diseases (e.g. for alopecia isolated or colorblindness, partial) or prune them from suggestions (e.g. for disease which has not phenotypes because it would include almost everything).

**Comment by amc-corey-cox** [comment]
This is related to #367 and might be related to #329. The relation to the larger phenogrid example issue is that we may not need examples if these drop-downs suggested diseases had manageable (and diverse) numbers of phenotypes. Likewise, we want to highlight diseases or phenotypes we think are meaningful or that our user base is likely seeking.

**Comment by kevinschaper** [comment]
We don't yet export a widened nodes file to ingest into Solr with edge content about nodes included, but if we did, we could include a column for phenotype counts, which would at least let us boost diseases with direct phenotype annotations on top.

We could also do some very specific cheat boosting to put specific recognizable/example diseases on top

**Comment by amc-corey-cox** [comment]
Normally, I'd advocate exporting the widened nodes file as a more complete solution. In this case, I think we should cheat for now and boost a selection of chosen diseases as good examples for the tool or widely applicable information. If we do, I'd want most of the boosted diseases to have between 3 and 30 associated phenotypes.

**Comment by amc-corey-cox** [comment]
Actually, can we just solve this with a look-ahead? We're grabbing the phenotypes from somewhere, can we just check each one on the list until we find enough to populate the list? I'll see if I can figure out how to do that.

**Comment by amc-corey-cox** [comment]
After some discussion, we've determined a look-ahead would work but isn't the right solution for this. We'll be implementing a ranking with a small added weight to nodes with associated phenotypes. This should allow nodes with phenotype to rise to the top without additional overhead. This also allows us to choose what nodes we want to give preference to.

**Comment by amc-corey-cox** [comment]
Here is a folder of Monarch Community presentations we can pull diseases/phenotypes of interest to pull to the top of the results.

https://drive.google.com/drive/folders/1xKB_O3LmtW0MNCqC7tIyGU2D0Niq1jY9

**Comment by kevinschaper** [comment]
I'm going to close this as fixed now that the PR is deployed on dev and looks good. We may still have ranking enhancements, but now it should hopefully be somewhat challenging to get back an entity from the autocomplete that doesn't have any phenotypes.
