### ISSUE TITLE
Repair prefixmaps merged output (tracking ticket)

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#525]
#260 is blocked right now: to upgrade Pydantic we need to bring in the latest prefixmaps, but the latest prefixmaps has some big holes in it, including OMIM. 

Actual work will happen here: https://github.com/linkml/prefixmaps/issues/62

(unless we end up moving to a new prefixmaps repo)

**Comment by amc-corey-cox** [comment]
We also have a few other issues (some closed) related to PrefixMaps. The other open issue is #411. I thought I had found a couple of closed issues earlier but I can't locate them now... GitHub search not having partial-match is frustrating.

**Comment by amc-corey-cox** [comment]
The fix for this is here https://github.com/linkml/prefixmaps/pull/63.
