### ISSUE TITLE
Return better results for blank searches

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#536]
This applies primarily to node search, but could also apply to phenotype explorer search as well.

Currently the frontend, when the textbox is focused but nothing is typed in, simply queries the backend with an empty `""` search. This returns things like "disease" and "alopecia". It would be nicer to return something more relevant, such as handpicked nodes, or perhaps more ideally, a list of nodes in order of global popularity.

This global popularity could be measured by Google Analytics and selected by hand. Or, as an enhancement, the backend could record/tally every time someone makes a node-page request to a specific entity, and the ones with the most tallies get shown first. We'd want to count actual visits to the node page probably, not just searches, because searches could be incomplete strings like "alopec".

On the frontend, we should replace the lightbulb icon autocomplete entries (currently hardcoded) with these results. We should also add the same three special blank search categories (user's recent/frequent node visits and ideas/examples/globally-popular) to the phenotype explorer search as well. This might require modifying the AppSelectTags component to support this...

**Comment by monicacecilia** [comment]
@kevinschaper 🚀 🙌 🌟  -- you can do this!

**Comment by kevinschaper** [comment]
It turns out I couldn't do it (or at least, a lot of unexpected issues came up instead), so I'm bumping this to the 2023-04 release.
