### ISSUE TITLE
Switch monarch-ingest to downloading SSSOM mappings from monarch-mapping-commons

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#549]
We're still pulling the gene mapping SSSOM from the gene mapping data bucket and MONDO SSSOM from mondo's latest release, and using CHEBI-MESH mappings that were uploaded to the data bucket as a fixed resource before we had them ready as a part of mapping commons. Now that the mapping commons is in good shape, we need to switch over to it.

**Comment by glass-ships** [comment]
download:
    - mondo mappings
    - gene mappings
    - CTD biomappings

from data.mi.org/mappings/

**Comment by glass-ships** [comment]
https://github.com/monarch-initiative/monarch-ingest/pull/562
