### ISSUE TITLE
DictyBase gene ingest producing zero rows

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#551]
It looks like we need to find a way to retrieve/generate the necessary koza mapping file

```
#
# After manually downloading the Dictyostelium discoideum 'gene' TSV table file from:
#
# https://www.ncbi.nlm.nih.gov/data-hub/gene/table/taxon/352472/
#
# (for convenience, we name the resulting file
#  something like 'dicty_symbols_to_ncbi_genes.tsv')
#
# This file specifies the resulting map of
# Dictyostelium discoideum gene symbols ('names')
# to NCBI gene identifier numbers.
```

As a short term fix, I may just drop the file into the data-cache so that we can produce a release, but we'll need sort out how to download this. We'll probably need to add support in kghub-downloader for making a rest api post (there may already be some) - unless we sort out some kind of ncbi specific api config that uses their python library.

**Comment by kevinschaper** [comment]
@RichardBruskiewich thinks that the data that he used from the ncbi table is also available in gene_info.gz that we're already downloading, so we should be able to get this working without a complex download situation

**Comment by kevinschaper** [comment]
It looks like the gene node ingest is coming from the mutant list file, rather than their gene file.  We should be using http://dictybase.org/db/cgi-bin/dictyBase/download/download.pl?area=general&ID=gene_information.txt for genes

**Comment by kevinschaper** [comment]
I thought this was solved, but it appears that all of our dictybase g2p edges are dangling in the 2023-01-15

**Comment by kevinschaper** [comment]
I checked releases going back to 2022-07-27, and dictybase g2p hasn't yet made it out of dangling_edges.

**Comment by monicacecilia** [comment]
Dear @kevinschaper, do we have a verdict? 
Did _it_ make it out of there? 🙈

**Comment by kevinschaper** [comment]
I created https://github.com/monarch-initiative/phenio/issues/55, hopefully we can get it in the next phenio build.

**Comment by kevinschaper** [comment]
I see dictyBase gene to phenotype associations now on beta, all good
