### ISSUE TITLE
Test Text Annotator beta 

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#555]

**Comment by joeflack4** [comment]
Here are some issues I noticed:
- #559 
- #560

**Comment by sagehrke** [comment]
Related tickets 

- #544 
- #562 
- #564

**Comment by madanucd** [comment]
### Text Annotator Test Setup:

**Objective:** The objective of this test setup is to evaluate the performance of entity recognition approaches in accurately identifying diseases within a given dataset. Specifically, we aim to assess the effectiveness and efficiency of Spacy with the SciSpacy model in recognizing disease entities from the Monarch Knowledge Graph (Monarch KG).

**Data:** For this evaluation, disease nodes (biolink:Disease category) from Monarch KG were used, total of 23943 disease instances.

**Specifics of SciSpacy model:**
- Leveraging the en_core_sci_sm model.
-  Model size: 15 MB.
- For further insights, refer to: [SciSpacy Documentation](https://allenai.github.io/scispacy/), [SciSpacy GitHub](https://github.com/allenai/scispacy)

**Results:**
- Out of the 23943 diseases examined, 10123 were precisely matched.
- Majority of exclusions (13820 instances were not matched) fall under some of the categories mentioned below:
  - Variants or mutations associated with specific diseases (e.g., Alzheimer disease 11, Alzheimer disease 9, Alzheimer disease 7).
  - Lengthy concepts were segmented into multiple entities, exemplified by "Neurodevelopmental disorder with cardiomyopathy, spasticity, and brain abnormalities," which was recognized as separate entities: Neurodevelopmental disorder, cardiomyopathy, spasticity, and brain abnormalities.
  - Comma delimited entities specifying associated organisms/animals: Hypoparathyroidism, non-human animal; Hydrocephalus, pig; Krabbe disease, dog.

**Enhancements/Further Directions in Future Releases based on coverage, cost, memory usage and other considerations:**
- Leverage the potential of Large Language Models (LLMs) through strategic prompt utilization.
- Embark on fine-tuning existing NER/LLM models to optimize performance.
- Explore the realm of biomedical tokenizers.
- Delve into the utilization of in-house tools such as Oaklib, OntoGPT, Phenomic Assistant (NLU pipeline), etc.
