### ISSUE TITLE
Update how to Cite Monarch on UI?

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#557]
Under the section of the new UI for citing Monarch in publications, are the two publications listed still accurate? 
https://monarchinitiative.org/cite#in-publications

I am guessing we need to add the new NAR paper at a minimum. 

@mellybelly @cmungall @monicacecilia Do you have any thoughts on this?

**Comment by glass-ships** [comment]
Potentially duplicate of #589
