### ISSUE TITLE
Text annotator: Terms not (consistently) producing annotations

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/monarch-app#559]
## Overview
I tried the new [text annotator](https://monarchinitiative.org/explore#text-annotator), and tried an arbitrary example using the word _feature_, which is annotated in the sample, but (1) did not get annotated in my own text, and (2) was not annotated every time in the sample.

## Sub-issue list
- [ ] 1. Annotations not appearing (e.g. same ones as in sample)
- [x] 2. Annotations in sample inconsistent

#### Expected
When a word in the _Try an example_ is annotated, it should also be annotated in my own text being entered.

#### Actual
The word was not annotated in my own attempt.

#### Replicability
1. Select _Try an example_
2. Observe that the term _feature_ produces annotations (in at least 1 location in the example text).
3. Clear the box, and enter _this is a feature_, and refresh the page
4. Observe _feature_ is not annotated

#### More
<details><summary>Screenshots & more</summary>
<p>

This issue does not always occur. It looks like it has something to do with text parsing, possibly just related to proper grammar / sentence structure.

For example, this is the result if you follow my steps above:
<img width="842" alt="no" src="https://github.com/monarch-initiative/monarch-app/assets/13045020/598811ad-eeff-4a9e-85f6-34fb71bae221">

But if I add a period, it gets annotated:
<img width="909" alt="yes" src="https://github.com/monarch-initiative/monarch-app/assets/13045020/16ca599e-3f6c-426f-a210-cb30e82b9214">

Capitalization did not seem to matter.

Adding a `.` wasn't the only thing that fixed the issue for me. Also ending the line with a `;` worked.

Some other cases I also just tried:
- _feature._ - worked
- _lkjdfskljf feaure kljkljd hello._ - failed
- _feature hello._ - failed

</p>
</details> 

#### Expected
If a term is annotated some place in the sample or any arbitrary body of text entered into the text box, it should be annotated in every other instance in which it appears.

#### Actual
Sometimes a term is annotated, and sometimes it is not.

#### Replicability
1. Select _Try an example_
2. Look / search for the term _feature_
3. Observe that in one place it is annotated, and in another it is not.

#### More
<details><summary>Screenshot</summary>
<p>

<img width="872" alt="Screenshot 2024-01-23 at 6 07 58 PM" src="https://github.com/monarch-initiative/monarch-app/assets/13045020/8dc4383b-ec83-4679-82ae-493cb4fea2fa">

</p>
</details> 

## Additional notes
I only experimented with entering free text and refreshing the page. I did not use the _Upload_ alternative.

**Comment by madanucd** [comment]
**Regarding Issue 1: Annotations not appearing**

The issue of missing annotations, as observed in the provided sample, seems to stem from Spacy's reliance on grammatical relations when predicting entities within a given text. For instance, in the sentence "Photophobia nystagmus strabismus with foveal hypoplasia," where concepts lack separation by commas, Spacy overlooks the entities "nystagmus" and "strabismus." Conversely, when commas are present ("Photophobia, nystagmus, strabismus with foveal hypoplasia"), Spacy accurately identifies all entities.

Addressing this concern involves exploring potential enhancements in accuracy, which may include a deeper exploration of rule-based matching techniques. However, it's worth noting that delving into such techniques, as outlined in the Spacy documentation (https://spacy.io/usage/rule-based-matching), may not directly resolve the current issue at hand.


**Regarding Issue 2: Annotations in sample inconsistent**

The problem has been addressed in the following pull request: [PR #574](https://github.com/monarch-initiative/monarch-app/pull/574). This PR resolves the inconsistency by employing a pattern-based approach, similar to that mentioned for issue 1, to title-case recognized entities with multiple instances. This ensures their recognition across multiple instances.

**Comment by joeflack4** [comment]
Just curious, it looks like (2) was solved, but has (1) not been solved yet? If not, has it been moved into a new issue?

Thanks for your attention to these!

**Comment by madanucd** [comment]
Following our discussion, it's evident that issue 1 revolves around the imperative of maintaining proper grammar and sentence structure to ensure accurate entity recognition. The coherence and grammatical precision of the input directly impact the model's ability to identify entities effectively. It's crucial to acknowledge that consistently encountering ungrammatical or highly fragmented sentences can significantly impede the model's accuracy in identifying entities.

While our primary focus remains on achieving comprehensive coverage, prioritizing the recognition of all diseases, phenotypes, and genes within the monarch KG, I am fully open to addressing issue 1 separately if you deem it critical. We could explore this matter further through enhanced fine-tuning methods. However, please note that this may extend beyond the current project scope. Please advise.

Thank you.
