### ISSUE TITLE
Text annotator: Add 'submit' button

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/monarch-app#560]
## Overview
When I used the [Text Annotator](https://monarchinitiative.org/explore#text-annotator), to trigger submission of text and get annotation results the options appear to be: (a) click outside the text box, or (b) refresh the page.

This wasn't immediately clear to me and at first I thought it was broken. I tried refreshing the page first and it was only after playing with it for a while that I realized that clicking outside the box also works.

Can we add like a _Submit_ button so it is more clear how to use it?

An alternative might be to do auto-refresh. You could do this with a delay of maybe 1-2 seconds after the user stops typing. Could also add a small spinner/progress icon animation in some corner of the app while it is refreshing.

**Comment by joeflack4** [comment]
Normally for an issue like this I choose a label such as `ux` or `ux-issue`. Can we add such a label? If not, _enhancement_ is fine.

**Comment by twhetzel** [comment]
I also found it confusing to know how to trigger/submit the text annotation. I eventually clicked on the "Text Annotation X1" button.

**Comment by joeflack4** [comment]
Ahh I see. Then I think that button "Text Annotator X<sub>1</sub>" could be renamed to "Submit" or "Annotate", and should go below the input box, to the left of "Upload..." or perhaps below it, which is pretty conventional.
