### ISSUE TITLE
Make table results downloadable from web to txt or csv

### ISSUE THREAD

**Issue by jberghoutPfizer** [monarch-initiative/monarch-app#57]
Feature Request: a download button option for table results on different pages within the MONDO website. As an example, the MONDO term to causal gene relationships: https://monarchinitiative.org/disease/MONDO:0005453#causal-gene

I realize these can be recreated through the API, but sometimes the table is exactly what I would want and can already see in front of me. So learning how to set up an API query is so many extra steps.

**Comment by kevinschaper** [comment]
Thanks for making this issue @jberghoutPfizer, and I agree completely!

I know that this feature existed on the v1 monarch web UI, but doesn't exist on v2 - so I'm not sure if it was related to any technological limitations (perhaps association lists on very high level terms were expensive to produce?). 

We're working on building v3 right now and we'll move this issue into that queue and look at it there. 

Our new API will be based on our monarch-py python & cli data access tool. It doesn't have TSV support yet, but having this issue in mind now is really helpful for considering where we'll put the TSV conversion code and how we can make it available from the web api as well.

**Comment by vincerubinetti** [comment]
@jberghoutPfizer Do you expect to have an option for downloading the full table of results, the current page of results, or both?

Kevin, would this be like a `?csv=true` parameter in the same API endpoint search, and it just actually provides the CSV content instead of JSON? Or would it just be something like `?limit=99999999` to get all rows of the table at once (hopefully without crashing), return JSON, and let the frontend format and download as csv/tsv/etc. We can do whatever is easier for you, I just want to get mentally prepared.

**Comment by jberghoutPfizer** [comment]
I would expect the full table, otherwise it's just a fragment of the results that I need to stitch back together.

But to save your infrastructure - ok if you want to build in a reasonable limitation (with a warning that "website downloads are limited to ~500 rows or less, please use the API" type of thing) to avoid having someone pull back the entire ontology and annotations through this.

My reasonable use case scenario is anticipating more like 10-50 rows.

**Comment by ValWood** [comment]
@valwood

**Comment by glass-ships** [comment]
It definitely took us a while, but I just wanted to mention that we just brought in a [PR](https://github.com/monarch-initiative/monarch-app/pull/537) for this! 

It's now live on the dev version of the site https://dev.monarchinitiative.org 
Association tables are now downloaded in TSV format (with soft plans to include separate JSON/CSV options at a later date) 

Please feel free to re-open this issue if there are any additional questions or concerns about this feature!

**Comment by ValWood** [comment]
Hi, @kevinschaper  we can't find the human gene-> causal disease file.
Can you point us in the right direction.
