### ISSUE TITLE
Missing data in v3 API compared to v1?

### ISSUE THREAD

**Issue by colleenXu** [monarch-initiative/monarch-app#577]
I couldn't find the following kinds of data in the current API when searching by association-type.

* Disease ⭤ Pathway ([example](https://api.monarchinitiative.org/api/bioentity/disease/MONDO%3A0010524/pathways?rows=-1&facet=false&unselect_evidence=true&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=true&direct_taxon=false))
* any relationship with Variants (dbSNP/rsIDs): there used to be [Disease ⭤ Variant](https://api.monarchinitiative.org/api/bioentity/disease/MONDO%3A0004747/variants?rows=-1&facet=false&unselect_evidence=true&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=true&taxon=NCBITaxon%3A9606&direct_taxon=false&relation=RO%3A0003304), [Gene ⭤ Variant](https://api.monarchinitiative.org/api/bioentity/gene/HGNC%3A2950/variants?rows=-1&facet=false&unselect_evidence=true&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=true&direct_taxon=false), [Phenotype ⭤ Variant](https://api.monarchinitiative.org/api/bioentity/phenotype/HP%3A0002944/variants?rows=-1&facet=false&unselect_evidence=true&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=true&taxon=NCBITaxon%3A9606&direct_taxon=false)
* [gene ortholog ⭤ Disease](https://api.monarchinitiative.org/api/bioentity/gene/HGNC%3A9508/ortholog/diseases?rows=-1&facet=false&unselect_evidence=true&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=true&direct_taxon=false)
* [gene ortholog ⭤ Phenotype](https://api.monarchinitiative.org/api/bioentity/gene/HGNC%3A8548/ortholog/phenotypes?rows=-1&facet=false&unselect_evidence=true&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=true&direct_taxon=false)

Are they no longer available though this API? 

(CC @kevinschaper, related to https://github.com/biothings/biothings_explorer/issues/774)

**Comment by kevinschaper** [comment]
We don't currently have disease to pathway or any variant data.

Right now the endpoint is a fairly direct representation of the kgx with necessary ontology closure info for indirect lookups, so we're not providing the two hop gene to disease or gene to phenotype via orthology as associations. We do plan to support that again eventually, but haven't yet settled on how.

**Comment by colleenXu** [comment]
Question answered, so I'm closing the issue...

**Comment by colleenXu** [comment]
@kevinschaper Ooops, I just remembered. I also see no items for a specific association-type: [Chem to Disease/Pheno](https://api-v3.monarchinitiative.org/v3/api/association?category=biolink%3AChemicalToDiseaseOrPhenotypicFeatureAssociation&format=json&limit=20&offset=0). 

Is that expected?
