### ISSUE TITLE
Add initial support for histo-pheno endpoint

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#58]
getHistoPheno in histo-pheno.ts currently calls `biolink/<disease id>/phenotypes` with these parameters

```
    rows: 0,
    facet: true,
    unselect_evidence: false,
    exclude_automatic_assertions: false,
    fetch_objects: false,
    use_compact_associations: false,
    direct: false,
    direct_taxon: false,
```

and from the facet data it produces this typescript:

```
/** histo-pheno data (for frontend) */
type HistoPheno = Array<{
  id: string;
  name: string;
  count: number;
}>;
```

Some historical discussion on the terms that are used to `facet.query` Solr is here: https://github.com/monarch-initiative/biolink-api/issues/123

This case is likely too high level, but will still serve to make a start. 

- [x] Represent this id/name/count as a class in the monarch-api linkml schema
- [x] Wrap a collection of those classes into a response class
- [x] Stub out the api endpoint that will return the response class
- [x] Make a fixture json file on the frontend side as an example of the response for this schema
- [x] Make a frontend method for the api request
- [x] Add a mock test to query the api
- [x] Add a mock test that checks the fixture contents
- [ ] Find the list of high level terms to query in the biolink codebase
- [ ] Add facet.query support in monarch-py (this should be it's own issue)
- [ ] Make a decision about whether histopheno query should be owned by monarch-api or monarch-py
- [x] Implement the histo-pheno query
- [x] Add tests

**Comment by kevinschaper** [comment]
The high level HPO terms are listed here along with the labels used for histopheno: https://github.com/biolink/ontobio/blob/0ec3aa6fea9d4492a9873a4b9b394c4866f741b6/ontobio/vocabulary/upper.py#L9

```
class HpoUpperLevel(Enum):
    skeletal_system = 'HP:0000924'
    nervous_system  = 'HP:0000707'
    head_neck = 'HP:0000152'
    integument = 'HP:0001574'
    eye = 'HP:0000478'
    cardiovascular_system = 'HP:0001626'
    metabolism_homeostasis = 'HP:0001939'
    genitourinary_system = 'HP:0000119'
    digestive_system = 'HP:0025031'
    neoplasm = 'HP:0002664'
    blood = 'HP:0001871'
    immune_system = 'HP:0002715'
    endocrine = 'HP:0000818'
    musculature = 'HP:0003011'
    respiratory = 'HP:0002086'
    ear = 'HP:0000598'
    connective_tissue = 'HP:0003549'
    prenatal_or_birth = 'HP:0001197'
    growth = 'HP:0001507'
    breast = 'HP:0000769'
```

We should put this enumeration into the schema

**Comment by glass-ships** [comment]
Added a histopheno query command in monarch-py to help out with this:
https://github.com/monarch-initiative/monarch-py/pull/38

**Comment by vincerubinetti** [comment]
#66 

Make sure to include "closed by #xxx" in PR comments so they are closed when the PR is merged.
