### ISSUE TITLE
Unmatch logic doesn't seem to be working

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#587]
https://github.com/monarch-initiative/monarch-app/blob/8e31ecdef230615603ec881e56855028544b5031/frontend/src/api/phenotype-explorer.ts#L135

Seems to unmatch inconsistently depending on direction of set comparison

**Comment by vincerubinetti** [comment]
Example:

HP:0001162,ZP:0000018

HP:0025096
