### ISSUE TITLE
Minor update to Resources page

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#588]
Request from @monicacecilia 

- On the Resources page https://monarchinitiative.org/resources, we should remove the App. 
- Somewhere, probably the 'About' page we should clarify what the Monarch App is. 
   - I see links to the Source documentation as well as the API 
   - @monicacecilia can you clarify what you'd like clarified on the About page? 😄

**Comment by glass-ships** [comment]
We shouldn't manually remove this from the `resources.json`, since that file is generated from monarch-documentation. 

@matentzn as you managed the code that generates this file, can you suggest an approach to removing monarch-app from projects that get included?

**Comment by matentzn** [comment]
Can someone explain why we should remove the app? So far, this list is a list of all Monarch flagship products. If we remove it the entire code needs to change - either the App is a Flagship product, and is listed on this page, or its not a flagship product and then ok, we can remove it easily..

**Comment by matentzn** [comment]
Remember that `mi.org !=App` the App is a part of mi.org. mi.org is our Portal, which gives access to multiple apps and products!

**Comment by glass-ships** [comment]
as we have it now, the website itself is the app, which comprises 3 main parts: the python library, the fast API backend, and the Vue typescript frontend interface, at least that's been my understanding so far

as for whether it is or isn't considered a  flagship product, I can't really say

**Comment by matentzn** [comment]
Things have changed now due to the PI meeting, please put on hold until further notice.

**Comment by glass-ships** [comment]
Did the recent changes to monarch-documentation address this? 
(ie. Is the current version of `monarch-documentation/.../resources.yaml` accurate, if i were to pull it into the app now?)

**Comment by matentzn** [comment]
Minor detail was missing: https://github.com/monarch-initiative/monarch-documentation/pull/65

I think we need to revisit a bit the display of that page. (I am assuming you are using https://github.com/monarch-initiative/monarch-documentation/blob/main/src/docs/resources/monarch-app-resources.json not the yaml file)

 We now have 6 Flagship products. 1 standard, 3 ontologies and 2 tools. These are less then there were before. We should decide if we:

1. Just want to show the flagship products in one row at the top so they are visible at first glance and then
2. Show all the _core_ products listed underneath, broken down by tool, ontology and standard

OR:

1. we break down the page by tool, ontology and standard to start with and somehow show 
2. The flagship products first, clearly indicated as such and then all the other "Core products"

Maybe you have another idea?

For now, just so we can get this first pass out the door, maybe just update the page with the new content, and then we iterate with @monicacecilia advice.

**Comment by glass-ships** [comment]
No particular ideas one way or another, I'm happy to let leadership advice and as you say, just pull it in as is for now. I've tagged you for review on #628 does just that, you can check the preview to see how it'll look on the site

**Comment by sagehrke** [comment]
Perhaps for this first pass, we simply remove the three categories and just list the flagship products on the page. It looks a bit odd in the preview on #628 to keep them in categories when there are fewer things listed. 

Then we can iterate more later with more input as you both are suggesting.

**Comment by glass-ships** [comment]
Thanks @sagehrke 
I'm not sure we can squeeze all 6 in one row, at best it'd be 5 on top row and 1 in a second row. 
For now I've condensed it to one section, but still having it 3 items for each row.
Let me know if that's ok for now.

**Comment by matentzn** [comment]
3/3 sounds good to me personally; I would suggest we focus on on content for now - display is likely to be fine tuned later.

**Comment by sagehrke** [comment]
I agree - the 3 on each row works good for this first revision @glass-ships -- you can call this done for now!
