### ISSUE TITLE
Add multi-set Phenogrid for IMPC

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#599]
IMPC is currently using a legacy.mi.org endpoint that takes one set of phenotypes and allows it to be compared against multiple other sets. As a first step towards being able to provide continuity, we should add that option to the Monarch API. 

My first reaction is that because the input would be close to compare, but not exactly the same, and the output would be close to search, but not exactly the same, we might want to just make a dedicated multi-compare endpoint. 

On the other hand, the notion of providing an overall score might be beneficial to compare, and so that would be a strong argument in favor of changing up our compare endpoint to take one `subjects` collection and many `objects` collections. Whether you have one or many, each `objects` collection would be given a score relative to the `subjects` set. A name and ID could also be passed in, so that the sets come out nicely annotated.

**Comment by kevinschaper** [comment]
We'll move this forward by meeting with Diego to work on this endpoint and also work out what changes we would need to make to the "phenogrid-in-an-iframe" implementation so that it can be fed named sets, do the comparisons and display the results.

**Comment by monicacecilia** [comment]
@kevinschaper - a kind reminder to please add info about UI work in support of this effort.

**Comment by kevinschaper** [comment]
Moving this forward to the April release, backend is in, frontend PR (#622) is almost ready for dev, and then we can round trip with IMPC to fine tune the details.
