### ISSUE TITLE
SSL Cert for api-dev is not valid

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#6]
It is mismatched, meant for api.monarchinitiative.org and needs to have its own cert issued and configured

**Comment by kevinschaper** [comment]
It's done, but it was a little bit of a rocky transition. Faisal looked into and found the part of the UI that will let us create a new certificate on its own, and then we can switch to it once it's up, rather than creating and assigning at the same time with no fallback when it's an error.
