### ISSUE TITLE
Add support for setting the base solr url

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#60]
I did a quick PR to change the default solr port from `http://localhost:8983` to `http://127.0.0.1:8983` but we should probably either pull this from the environment or allow it to be set as a command line option (or both?), and then document how to do that.

**Comment by glass-ships** [comment]
i think @kevinschaper did this already?

**Comment by glass-ships** [comment]
Added the ability to set a `MONARCH_SOLR_URL` environment variable in `monarch-py` to specify a separate Solr backend

**Comment by glass-ships** [comment]
We should _maybe_ change this to `MONARCH_SOLR_URL` in monarch-api as well, but yeah Kevin definitely already implemented this. Closing as complete
