### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by amc-corey-cox** [monarch-initiative/monarch-app#600]
We need to document several aspects of how to contribute to the Monarch app. The top-level CONTRIBUTING.md should reference a separate CONTRIBUTING.md in each of the backend and frontend sections of the app. 

- [ ] Top level CONTRIBUTING.md with information about the project and setup of the development environment.
- [ ] backend: detail of setup for development, including dependencies and suggested environment.
- [ ] backend: how to pull a PR branch and test functionality, including how to set up the environment for local testing.
- [ ] frontend: detail setup for development - including dependencies, suggested environment, and how to run locally.
- [ ] frontend: how to pull a PR and test functionality
- [ ] frontend: how to run linting and testing framework locally.

**Comment by amc-corey-cox** [comment]
I have added all of you as assignees to get your input and feedback on this issue. Please add any additional pieces we may need to consider in the CONTRIBUTING.md. If you have reviewed this and don't have anything more to add feel free to remove yourself as an assignee.

**Comment by amc-corey-cox** [comment]
I've discovered this will require some rewriting of the README.md's as well - especially moving some of their documentation over to CONTRIBUTING.md's and updating.

**Comment by monicacecilia** [comment]
Thank you! Ready to take a look whenever you are ready! 🌷
