### ISSUE TITLE
Evidence count is getting an empty value even when publications are present

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#601]
I think there is a bug in closurizer which might be doing an inner join to produce evidence counts such that evidence count is only populated when both `has_evidence` and `publications` fields have values, but comes back empty if only one column is populated. It's also not producing zeroes when neither if populated. 

Initially I was chasing after the lack of publications on ZFIN and Alliance g2p associations, saw that they were present in the data files, in the transform output, and even in the finished KG, and it fact it was only the count that was wrong.

**Comment by monicacecilia** [comment]
happy. :bowtie:
