### ISSUE TITLE
Google App iPhone autoplays video on mi.org 

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#607]
When opening monarchinitiative.org using Google App on iPhone, the videos on the homepage autoplay making it difficult to use to site. It does not seem to happen when opening Safari on iPhone. I have not checked it it happens using Chrome on iPhone.

**Comment by amc-corey-cox** [comment]
Vince was able to reproduce this with Safari using the Google Search App. This may be kind of a difficult fix because we will either have to disable auto-play for all users or attempt to detect the Browser/OS of the user which is brittle.

We're investigating a fix now.
