### ISSUE TITLE
Use `InstanceType<typeof MyComponent>>` for to get `defineExpose` type

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#615]
Rather than re-specifying the type in the consuming component. Low-hanging fruit.

https://github.com/vuejs/core/issues/4397#issuecomment-1035863245

@glass-ships you could also take a stab at this if you have some time, otherwise we can do it quickly on friday.

**Comment by glass-ships** [comment]
sure, can you expand on that a little? 
is this a one spot kinda thing or more a sweeping update across components?

**Comment by vincerubinetti** [comment]
This would be across components. I'm fairly certain we use `defineExpose` in several places. That defines functions/reactive variables/etc within the component that are exposed and can be accessed from outside it.

```ts
// FirstComponent.vue
function add(a: number, b:number) { return a + b; }
defineExpose({ someFunc })

// AnotherComponent.vue
// <template><FirstComponent ref="something"></template>
const something = ref<{ add: (a: number, b: number) => number}>();
something.add(1,2);
```

Instead of re-specifying the type of the `add` function in the second component, we can use the syntax in the issue title to just get it automatically.

**Comment by glass-ships** [comment]
I'm having a little trouble wrapping my head around the suggested syntax. 
 
Is it replacing the `defineExpose` bit?

Or only references to places where the component gets used somewhere else? (more specifically, when it's used with a ref defined, like in phenogrid:

```typescript
// ThePhenogrid.vue
<AppFlex ref="container" direction="col" class="container">
...
/** element refs */
const container = ref<{ element: HTMLDivElement }>();
```

which would i guess get turned into uhhhh
```typescript
// ThePhenogrid.vue
<AppFlex ref="container" direction="col" class="container">
...
/** element refs */
const container = ref<null | InstanceType<typeof AppFlex>>(null);
```

**Comment by vincerubinetti** [comment]
You are understanding correctly with your code examples. While it ends up being longer, it is more generic and less repetitive. Doing `{ element: HTMLDivElement }` is re-defining/duplicating the internal implementation details of the child component (AppFlex in your example). With the new way, you'd only have to change the expose type definition in one place, the component, and then typescript would immediately tell you that there's an error in all of the consuming components (ThePhenogrid in your example).

In fact, currently, if you were to change AppFlex's expose type definition, typescript wouldn't even know there's an error in ThePhenogrid, because `ref<{ element: HTMLDivElement }>();` is basically type casting (i.e. "trust me bro"), and there's no link between that ref and the AppFlex component's types. Maybe in the future, Vue's compiler/type-generator will be smart enough to see that the type of the ref attached to a component doesn't match the type of the component's expose.

**Comment by glass-ships** [comment]
Ah interesting! I think that makes sense.

(I never hit send on this comment, my bad, but i have a PR that should address this!)
