### ISSUE TITLE
Phenogrid rows are not sorted

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#636]
Not really a bug, just something I noticed while working on the metric PR. 
Every time you re-run a phenogrid analysis, the rows seem to be sorted randomly - Do we want to try to sort them on some value, even lexicographically?

**Comment by vincerubinetti** [comment]
Will be closed by https://github.com/monarch-initiative/monarch-app/pull/622

https://github.com/monarch-initiative/monarch-app/pull/622/commits/4c1194e4421976de6fe0135bb2216f68fc0c1bbf

**Comment by vincerubinetti** [comment]
Duplicate #656
