### ISSUE TITLE
FlyBase `nan` gene FB:FBgn0036414 doesn't have name in monarch-kg

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#660]
I think we need to update cat-merge to tell Pandas not to treat `nan` as NA/null/none. 🤦

**Comment by glass-ships** [comment]
possibly? i'm not entirely sure it's pandas's fault actually. 

```python
import pandas as pd
import numpy as np

df = pd.DataFrame([["nan", "", np.nan, 0],], columns=list("ABCD"))

d = df.fillna(np.nan).replace([np.nan], [None])

print(d)

...
A  B      C     D
0  nan    None  0
```

`"nan"` as a string is still making it through the merge step at least. 
do we have a line somewhere that looks for string `"nan"` and specifically converts it to a `np.nan` or something?

**Comment by glass-ships** [comment]
it's also not happening straight out of ingest, at least
![image](https://github.com/monarch-initiative/monarch-app/assets/26975530/56a76c0e-e6d8-4dfa-9ec9-90c9f6a20340)

**Comment by kevinschaper** [comment]
I just did a quick check to confirm that alliance_gene_nodes.tsv has the name and monarch-kg_nodes.tsv doesn't, so it's definitely happening in cat-merge.

**Comment by kevinschaper** [comment]
I started a PR with a test to confirm the fail: https://github.com/monarch-initiative/cat-merge/pull/64

**Comment by kevinschaper** [comment]
This is working on beta.monarchinitiative.org now
