### ISSUE TITLE
861 PomBase genes have null/blank name field

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#661]
cc'ing @valwood to be sure, but I think it would probably make sense to use the `gene_systematic_id` column to populate our `name` field when `gene_name` is empty.

**Comment by ValWood** [comment]
That makes sense, we use these as placeholder gene name.

**Comment by glass-ships** [comment]
that makes sense for name/full name, what about symbol?

**Comment by ValWood** [comment]
I don't understand the question, symbol is name?
What do you mean by "full name"

**Comment by ValWood** [comment]
We have 
Gene name	cdc2
column 9 of the PHAF file. This is equivalent to symbol.
We should probably change the label in this file to "symbol" because we have migrated to this  elsewhere on our web pages.

**Comment by ValWood** [comment]
Note that yeast do not have the concept of "full name"  , we use only "gene symbol"

**Comment by glass-ships** [comment]
RE: full name, as an [example](https://monarchinitiative.org/HGNC:59). 
The gene ABCC8 would have the "full name" of ATP binding cassette subfamily C member 8.
That makes sense though, and why when ingesting it we just use the "gene_name" field for all three. 
Using the systemic id as a fallback for all three when it's empty makes sense, it seems

Thanks Val!

**Comment by ValWood** [comment]
That makes sense. We do have a "name description" but it is often not documented and never used as an actual "full name" so we tend to ignore it (SGD is similar in this regard). These are often not meaningful anyway.

More useful are the "product descriptions" which give the best up to date description of the gene product. These evolve over time and can be similar to the name, or very different.
