### ISSUE TITLE
Begin planning genotype to phenotype ingests

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#662]
This issue is meant to serve as an epic for the work needed to fully model genotype to phenotype associations in the Monarch Graph. 

Sources: 

* Alliance AGM entity load 
   * https://fms.alliancegenome.org/datafiles/AGM/MGI 
   * https://fms.alliancegenome.org/datafiles/AGM/RGD 
   * https://fms.alliancegenome.org/datafiles/AGM/ZFIN
* Alliance Allele load (limiting to MGI/RGD/ZFIN so that we can connect to models)
   * https://fms.alliancegenome.org/datafiles/BGI/MGI
   * https://fms.alliancegenome.org/datafiles/BGI/RGD
   * https://fms.alliancegenome.org/datafiles/BGI/ZFIN
      * May also need alleles from FB, XB, WB - Alliance has a human allele BGI file as well 
* Alliance Model to Disease associations
   * subset of https://fms.alliancegenome.org/download/DISEASE-ALLIANCE_COMBINED.tsv.gz where dbObjectType is model

This issue still needs: 
* links to model/genotype to phenotype
  * Our current alliance_gene_to_phenotype ingest filters to only include gene, I think models are in the file we use
  * ZFIN fish-to-phenotype will need to come directly from ZFIN to be able to map to ZP terms
* an issue to confirm that https://www.model-ad.org/models-available/ models are available in the Alliance files, or identify MGI files? or download directly from models-ad.org. 
* links to PomBase model files

**Comment by madanucd** [comment]
For more details on implementations and documentation, please refer to the following link: [Monarch App Issue #714](https://github.com/monarch-initiative/monarch-app/issues/714).
