### ISSUE TITLE
Create a crust template for modular koza ingests

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#668]
- [x] Creates koza yaml & transform python
- [x] Adds GitHub action to run tests on PRs
- [x] ruff configuration 
- [x] Standard Makefile 
- [x] MkDocs configuration
- [x] Github action to create data release 
- [x] Github action to deploy docs

**Comment by glass-ships** [comment]
WIP @ https://github.com/glass-ships/cookiecutter-monarch-ingest

**Comment by glass-ships** [comment]
for `Github action to create data release`, what are you thinking this should look like?

**Comment by monicacecilia** [comment]
Dear @glass-ships, do you know if this last step for GH actions has been completed?

**Comment by glass-ships** [comment]
Thanks @monicacecilia yes, that should be ready, I just forgot to check it off!
