### ISSUE TITLE
Deploy vue app to GitHub pages

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#67]
As a short term hosting solution while we work on converting the UI to our new API, let's just host on GitHub pages. 

https://github.com/marketplace/actions/vue-to-github-pages

**Comment by vincerubinetti** [comment]
The linked action doesn't provide much benefit as far as I can tell and also seems to assume Vue 3 is necessarily being built with Vite (not true, and is not true of our frontend, yet).

The deploy workflow here should work just fine:
https://github.com/monarch-initiative/monarch-ui-new/blob/main/.github/workflows/deploy.yaml

but we'll have to work out where else to host the documentation.

Or, you could technically host both of them on GitHub Pages. You'd put the docs in a sub folder like `/docs` on the `gh-pages` branch, and make sure the `deploy-frontend` workflow never overwrites it or touches it, and make the `deploy-documentation` workflow deploy to that folder. Pro: same url/domain and one less new place for users to remember. Con: 404s will need to go to the main UI/app and not to the docs site.

**Comment by glass-ships** [comment]
A quick mostly dev deployment is up at https://monarch-api.netlify.app for now
But we probably want to meet up sometime and make a more concrete decision about deployment for the UI and docs

**Comment by vincerubinetti** [comment]
Implemented in #154 

Currently at https://monarch-app.monarchinitiative.org/ (hosted on GitHub Pages)

/docs should also include the mkdocs docs.
