### ISSUE TITLE
User Feedback for How-To

### ISSUE THREAD

**Issue by amc-corey-cox** [monarch-initiative/monarch-app#670]
We are gathering some limited user feedback to find out what parts of the Monarch App could use some clarifying information. We are planning to add a How-To section for the website that gives more detailed instructions on how to use the different components of the Monarch App. We're hoping for feedback on specific tasks that users want to complete that it may not be completely clear how to do in the UI.

I have collected the below feedback into a list here:
- [x] Add a section for using Monarch programmatically with API, R, or ChatGPT assistant.
- [x] Fix typo “Genes can be searched by common gene, gene ID, “ —> “common gene name, gene ID, …"
- [x] Move down the clickable HT icon. Make a new section below _“What is Monarch?”_ and its four tiles.
- [x] Gene of interest search results, add Taxon info for clarity.

**Comment by amc-corey-cox** [comment]
Add a section for using Monarch programmatically with API, R, or ChatGPT assistant.

**Comment by monicacecilia** [comment]
ToDo: 

- [x] Fix typo “Genes can be searched by common gene, gene ID, “ —> “common gene name, gene ID, …"
- [x] Move down the clickable HT icon. Make a new section below _“What is Monarch?”_ and its four tiles.

**Comment by ehurwitz** [comment]
- after searching for a gene of interest, there are multiple listings; I realized it’s the taxon but it would be great to show the taxon on the screen in this image below
![Monarch image1](https://github.com/monarch-initiative/monarch-app/assets/66528685/52849d35-73b0-4672-bcca-4eda6d885a19)
- the UI for latest posts look a little weird; I'm thinking the title for posts is meant to go more horizontally - see image below
![Monarch image 2](https://github.com/monarch-initiative/monarch-app/assets/66528685/8a22c1dd-997c-45cd-899b-2c52502f3c4b)

**Comment by amc-corey-cox** [comment]
@ehurwits I think this is probably a good idea so I'm going to make a new issue with your context. I don't think that improvement is appropriate for the scope of this current ticket. However, we do appreciate your thoughts and bringing this to our attention. We'll look at getting this into a coming Milestone.
