### ISSUE TITLE
Configure redirects from monarchinitiative.org 

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#672]
Let's borrow from the convenience of https://github.com/tis-lab/redirects/blob/main/redirects.yaml to create nginx redirects in our nginx config. 

I'm guessing we'll have a step to translate the yaml into nginx redirect format, and then we'll need to use some kind of include directive to bring that into the nginx config.

**Comment by matentzn** [comment]
Bit _yes_! I will start adding stuff as soon as a rough outline exists. Thanks @kevinschaper!

**Comment by monicacecilia** [comment]
Generate (for now): 
- monarchinitiative.org/hpo --> https://hpo.jax.org/
- monarchinitiative.org/exomiser --> https://exomiser.monarchinitiative.org/exomiser/
- monarchinitiative.org/phenopackets --> https://www.ga4gh.org/product/phenopackets/
- monarchinitiative.org/uberon --> https://github.com/obophenotype/uberon 
- monarchnitiative.org/mondo --> https://mondo.monarchinitiative.org
- monarchnitiative.org/kg --> https://monarchinitiative.org/explore

AND
create ```servicename.monarchinitiative.org``` for most foundational products, except HPO. 

This will evolve.

**Comment by kevinschaper** [comment]
This work is committed to https://github.com/monarch-initiative/monarch-app/pull/791, but will go out in the September release rather than August
