### ISSUE TITLE
query subject_closure & object_closure by default, add direct boolean param

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#68]
This change is mainly happening in monarch-py, but will change the fastapi params as well

We need to add a `direct` boolean parameter that defaults to `False`

if direct is True
`subject`, `object` & `entity` should query using `subject` and `object` fields

if direct is False
`subject`, `object` and `entity` params should actually use `subject_closure` and `object_closure` fields

**Comment by glass-ships** [comment]
See [monarch-py#53](https://github.com/monarch-initiative/monarch-py/pull/53)

**Comment by glass-ships** [comment]
Implemented in monarch-py, what changes need to be made here in the API / frontend?
