### ISSUE TITLE
Add "AI at Monarch" page to the UI

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#685]
Let's get a page up advertising our AI / LLM / embeddings related tools and data products. 

This is also a good excuse to get #442 done. 

Assigning @madanucd for content and @glass-ships to help out with integrating a new page into the UI. 

cc: @justaddcoffee @caufieldjh for help with adding content

Setting may milestone, but depending on how busy everyone is, we may need to bump to June

**Comment by caufieldjh** [comment]
Can borrow from this doc: https://docs.google.com/document/d/1B6YVEGjzOC7sizhRaKQ0B_afivFAG-Cs1E9yodHaNoA/edit#heading=h.immxzdqrubko
Or just make this new page the de facto Intro to Monarch AI Stuff resource in lieu of that GDoc.

**Comment by madanucd** [comment]
Following our discussion in one of our tech-team meetings, we have decided not to include this page at this time. Thank you!
