### ISSUE TITLE
Document Modular Alliance Disease Association Ingest

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#701]
Ingest to capture Alliance [gene/allele/genotype] to disease associations. We can expect this ingest to have a lot of associations that we don't want to bring into Monarch, for example, one of the values in the source column is "OMIM via RGD" and monarch-kg is getting OMIM from the phenol pipeline instead. For the modular ingest, it should all be included and faithfully reproduced, filtering should happen when the output of this process comes into monarch-ingest. 

Likely the most interesting problem to solve in this ingest is choosing predicates, knowledge_level and agent_type to reasonably represent what comes from the file.

repo: https://github.com/monarch-initiative/alliance-disease-association-ingest

- [x]  download yaml
- [x]  transform python
- [x]  transform yaml
- [x]  tests
- [x]  documentation
- [x]  import into monarch-ingest

**Comment by kevinschaper** [comment]
We need to figure out how to exclude (until we can capture & display) based on environmental conditions. Right now AB, which is a wildtype, is showing as a disease model for Alzheimer Disease and lots of others. I haven't tracked this back yet, but I'm guessing these could be environment/chemical induced disease models? 

<img width="1103" alt="Screenshot 2024-06-10 at 7 26 52 AM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/79c125a0-9183-4ee6-8501-2573c68e3b04">

(screenshot from local dev, looking at 2024-06-08-genotypes-and-variants kg build)

**Comment by madanucd** [comment]
Documentation is up now at https://monarch-initiative.github.io/alliance-disease-association-ingest/
