### ISSUE TITLE
Get modular NCBI gene ingest up and producing releases

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#712]
We have options here.

We could just make a Jenkinsfile to automate @hrshdhgd's pyobo based ingest: https://github.com/monarch-initiative/NCBI-gene-pyobo. This is probably the least amount of work.

We could convert https://github.com/monarch-initiative/ncbi-gene to a proper monarch-ingest-cookiecutter repo, and make it fit into a GitHub Actions workflow by limiting to a subset of taxa. This feels like it might be more maintainable (by me, I suppose!) in the long run. 

I assume it's also possible to also subset the pyobo version. So, first step here is a decision, next step is an implementation.

**Comment by kevinschaper** [comment]
Since the modular ingest cookiecutter has been working well for us, let's try going that way for this. Assigning to @glass-ships  to convert [ncbi-gene]([url](https://github.com/monarch-initiative/ncbi-gene)) to the ingest cookie cutter, adding the taxon filter from monarch-ingest to start, and then we'll expand it.

**Comment by glass-ships** [comment]
https://github.com/monarch-initiative/ncbi-gene/releases/tag/untagged-7e1667250e0bbc290a06

**Comment by kevinschaper** [comment]
working now, and splitting files by taxon
