### ISSUE TITLE
Leonardo Chimirri add to team page on UI

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/monarch-app#719]
@glass-ships @sagehrke

**Comment by glass-ships** [comment]
@leokim-l sure thing. I'll need some more information to get you added: 
- What institution are you affiliated with? (UNC, CU Denver, Lawrence Berkeley, etc.)
- What page would you like to link to? We can default to your GitHub profile if you don't have anything particular
- Could you please reach out via Slack or [email](mailto:contact@glass-ships.com) and send me a photo you'd like to appear on the website
- What is your role/job title within Monarch?
