### ISSUE TITLE
Daniel Korn add to team page on UI

### ISSUE THREAD

**Issue by DnlRKorn** [monarch-initiative/monarch-app#727]
@glass-ships 
@sagehrke

**Comment by glass-ships** [comment]
@DnlRKorn sure thing. I'll need some more information to get you added: 
- What institution are you affiliated with? (UNC, CU Denver, Lawrence Berkeley, etc.)
- What page would you like to link to? We can default to your GitHub profile if you don't have anything particular
- Can you please send me a photo you'd like to have appear on the website

@sagehrke this will be a good opportunity to update the page to reflect our move to UNC. 
Could I get: 
- a list of folks who are still with us and remained at CU Denver
- a list of folks no longer with us to be moved into the alumni category

(Should this content match the AirTable? Is that Google doc still being maintained (and if so, could you re-send that to me?))

**Comment by DnlRKorn** [comment]
- UNC
- You can just link to my github website!
- I'll send a picture on Slack!
