### ISSUE TITLE
Update the Landing Page on mi.org

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#735]
Ideally, we want a landing page that shows the different products and doesn’t make it hard for people to start the search.

- [x] Replace the phrase “Explore our knowledge…” with Monarch’s vision: "Accelerating precision medicine through Open Data Science."
- [x] ~~Move the “What is Monarch” segment down and~~ add the foundational projects at the top (from the “resources” page) ~~above the search bar~~. 
- [x] Need somewhere to put the NIH ORIP video - potentially is should be on the new landing page. 
- [x] Reword the text on the foundational product buttons

**Comment by amc-corey-cox** [comment]
I think we have all of these completed now, in the UI update branch/PR attached.
