### ISSUE TITLE
Create Monarch SAB page

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-app#74]

**Comment by monicacecilia** [comment]
Include
- [ ]  SAB purpose
- [ ]  Members (picture, organization, position)
- [ ]  Meeting Cadence

**Comment by vincerubinetti** [comment]
I can easily get to this if someone gives me the content to put in there. @putmantime can you assign someone.

**Comment by glass-ships** [comment]
same here @sagehrke happy to work on it, but I'm not sure what the SAB is or what content would need to exist there

**Comment by sagehrke** [comment]
Hi @glass-ships - you can find most of the information that @monicacecilia mentions in the comment above in our blog post announcing the SAB (Scientific Advisory Board) [Here](https://monarchinit.medium.com/introducing-the-monarch-initiatives-scientific-advisory-board-40f7e1584269). @nlharris may have the original photos that she can share with you to use. If you'd like to pull content from the blog text for the website and run it by us, that works! I'd go simple on the text - a few sentences would likely do. Meeting cadence is twice yearly. If you need more guidance, please let us know. 

@monicacecilia would you prefer we add the SAB page to the Team page [here](https://next.monarchinitiative.org/team) or add a new page with a link from the About page [Here](https://next.monarchinitiative.org/about)?

**Comment by monicacecilia** [comment]
@glass-ships Please add SAB to the Team page. Above 'Alumni.'  Thanks!
