### ISSUE TITLE
Issue with ID calls in API

### ISSUE THREAD

**Issue by NCMBianchi** [monarch-initiative/monarch-app#761]
I made a call for Huntington disease (MONDO:0007739), yet the API returns me the .json for Juvenile Huntington disease (MONDO:0016621). This didn't happen up until a few weeks ago. What happened?

https://api-v3.monarchinitiative.org/v3/api/association?subject=MONDO%3A0007739
<img width="1392" alt="Screenshot 2024-07-17 alle 16 28 42" src="https://github.com/user-attachments/assets/15a710b6-c006-4a78-b80e-84fa375ed707">

**Comment by kevinschaper** [comment]
Hi @NCMBianchi,

Sorry for the slow response, I missed this when this came in last week. We expect the API response to include annotations to children of MONDO:0007739, but that can be overridden by adding direct=true and it should only show annotations where the subject is equal to MONDO:0007739. 

Does https://api-v3.monarchinitiative.org/v3/api/association?subject=MONDO%3A0007739&direct=true bring back what you're looking for?

**Comment by NCMBianchi** [comment]
It works perfectly, thank you very much. But is it correct that without `direct=true` it only returns results for MONDO: 0016621? I parsed through the json file and I can only find results for that, while earlier I could try for both MONDO:0007739 and MONDO:0016621. Or was it a temporary error? Because I just checked and now it works again as supposed even without `direct=true`.
<img width="1392" alt="Screenshot 2024-07-23 alle 08 59 22" src="https://github.com/user-attachments/assets/d14c9083-3606-4c6b-b084-14dc7ca18b82">

Thanks though and do not worry: your answer was still very quick, kind and well argument!

**Comment by NCMBianchi** [comment]
Something else I noticed: the number of returns after using direct=true is <99 (the call limit): is that because the total number of filtered results is 72 out of >99? Or is it first returning 99 results and then filtering it down to 72? I will not reopen the issue as this is just a out of curiosity.
