### ISSUE TITLE
Notes from team meeting on 12/16/2022

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#77]
Need help from others:

- No marfan syndrome as example query. I need some new example nodes to put in there.
- Single tagline right underneath logo. "Phenotype connection"? https://docs.google.com/document/d/1i7zwT3C0WzHuXqlao7Pw9c_NqwxyAPvcqiN6arTOlRE/edit
- The three big "tiles" on the homepage under "what is monarch" need to be changed. Maybe replace with several bullet points specific to each stakeholder: informaticians, patients, clinical geneticists, researchers. Include "Model organism network"?
- Add note above search box: "Explore our knowledge on this website"?

Vince's tasks:

- "Back to results" link on node page, if coming from a search.
- Add search box to toolbar with search icon. Use auto complete query only. Submit to go to (detailed) node search results page. If not showing any rich details (like category), de-dupe autocomplete results, since it is just submitting a text string to the regular detailed node search.
- In node search results, people are confused by the icons. Maybe add a legend at bottom, or add icons in category dropdown select.
- In dropdown components, distinguish between hover and keyboard select states. Apologies to Moni, I think she mentioned this and I misunderstood what she was saying and dismissed it. The user should be able to press enter to select (for accessibility), but only after selecting the option by arrow keys, not by hovering with mouse.

**Comment by putmantime** [comment]
@vincerubinetti and @putmantime will go through this together soon.

**Comment by vincerubinetti** [comment]
@putmantime can you assign someone to the first bullet list.
