### ISSUE TITLE
Update Team Page 

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#796]
- [x] Add Evan to the UNC team; see https://github.com/monarch-initiative/monarch-app/issues/795
- [x] Move Madan to the UNC team.
- [x] Request a picture from Leonardo; alternatively, use an avatar/landscape of his choosing. 
- [x] Request a picture from Carlo; alternatively, use an avatar/landscape of his choosing. 
- [x] Move Leigh Carmody to Alumni

**Comment by sagehrke** [comment]
- [x] Move Katie to the UNC team 
- [x] Request a picture from Martha; alternatively, use an avatar/landscape of her choosing.
- [x] Add Adam Graefe to Charite team; see https://github.com/monarch-initiative/monarch-app/issues/794
- [x] Remove links in the alumni section (it's too hard to keep these up to date)

**Comment by amc-corey-cox** [comment]
I've sent e-mails to all of those missing pictures and made all of the other updates. I'm going to consider this completed unless I receive responses from the e-mails. I'm pushing this to the branch for roll-in to the Dev this week.

**Comment by amc-corey-cox** [comment]
Accept for Adam and Leonardo we have all the images in. I think this is done now. I've reached out to both for images and I'll add them if I hear back but let's consider this ready to go.
