### ISSUE TITLE
Filtering to one taxon after searching

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#80]
<img width="960" alt="Screenshot 2022-11-21 at 12 03 16 PM" src="https://user-images.githubusercontent.com/4535019/203150218-23f75395-21de-4add-a716-7d90b713304e.png">

Since we're mostly oriented around known-item searches rather than broadly browsing ("I want to go to a page/thing" vs "narrowing down attributes until I find something I like"), I think it might make sense to optimize for the first click on the taxon dropdown being to select a taxon, rather than to deselect it.

**Comment by vincerubinetti** [comment]
I want to look into this more. I don't ever recall seeing precedence for this behavior (other apps in the wild doing the same thing). However it shouldn't be difficult to implement, and for the user to understand that's how it works (hopefully). Hopefully they are not mislead into thinking only one thing can be selected (as if it were radio buttons). 

For now though, note that you can shift click to do this.
