### ISSUE TITLE
Update https://monarchinitiative.org/publications with latest publication list from Google Scholar

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#828]
Please update the [Monarch Publications page](https://monarchinitiative.org/publications) with the latest publicaitons listed in our [Monarch Google Scholar](https://scholar.google.com/citations?hl=en&user=zmUEDj0AAAAJ&view_op=list_works&authuser=1&sortby=pubdate). 

Glass was the last one who did this. They had written a code that would just pull the info from the google scholar page and populate the Monarch publications page. Feel free to tag me in the PR so I can review the links as sometimes Google Scholar does some wonky stuff. 

Thank you!

**Comment by ptgolden** [comment]
done!
