### ISSUE TITLE
Add link to Monarch KG download

### ISSUE THREAD

**Issue by amc-corey-cox** [monarch-initiative/monarch-app#831]
We don't seem to have a link to  data.monarchinitiative.org on the monarch-initiative website. I think a good location for this would be the resources tab of the explore page on the knowledge graph.

**Comment by monicacecilia** [comment]
Thanks for writing this ticket, Corey. We should also include some information that guides the user and helps them understand what can be downloaded from this page. the 'data' page is a little "info" sparse at the moment.
