### ISSUE TITLE
Relabel table of results for Disease-to-Phenotype associations for both node types

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#837]
The header for the table of results detailing the connection between a disease and its associated phenotypes should be relabeled from `"Phenotype to Disease"` to `"Disease to Phenotype."` 

The header for the table of results detailing the connection between a phenotype and its associated dieases should be relabeled from `"Disease to Phenotype"` to `"Phenotype to Disease."` 

Reminder: the config file is right. the code is getting it backwards. 👈  👀  @kevinschaper

**Comment by kevinschaper** [comment]
This was completed in the 2024-10 release. :bowtie:
