### ISSUE TITLE
Add info about which institutes are participating

### ISSUE THREAD

**Issue by jamesamcl** [monarch-initiative/monarch-app#842]
I can't find any mention of which institutes are participating in MONARCH on the website. It would be nice to have some institute logos prominent on the homepage.

**Comment by monicacecilia** [comment]
Dear James, 

Information about all teams contributing to Monarch can be found at https://monarchinitiative.org/team
Naviation: `Homepage --> About --> Team `

We used to have this information on the homepage, but it was removed earlier this year following a request to highlight the Monarch Foundational Projects and "what we do" on the homepage instead (which originated during the Directors' meeting in Cambridge). 
Please let us know if you would like to restart the conversation about displaying teams and (or) affiliations again on the home page, and we can reopen the discussion. 

Thank you!
