### ISSUE TITLE
Fix Monarch Mapping Commons build

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#853]
The mapping commons build job is failing at the download step, based on what I've seen in the KG build, it's likely due to updates to the url (and possibly columns) for HGNC gene file. 

Repo is https://github.com/monarch-initiative/monarch-mapping-commons, Jenkins job is `Generate-Monarch-Mappings`

**Comment by ptgolden** [comment]
Where is the log where I can see the failure?

**Comment by ptgolden** [comment]
ah, I see. let me check on it

**Comment by ptgolden** [comment]
The for the HGNC gene file has changed from <http://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt> to <http://ftp.ebi.ac.uk/pub/databases/genenames/out_of_date_hgnc/tsv/hgnc_complete_set.txt>

**Comment by ptgolden** [comment]
Related: https://github.com/ramiromagno/hgnc/issues/6

**Comment by ptgolden** [comment]
Fixed by https://github.com/monarch-initiative/monarch-mapping-commons/pull/62
