### ISSUE TITLE
Tiled layouts take up entire page width, stretching tiles

### ISSUE THREAD

**Issue by ptgolden** [monarch-initiative/monarch-app#856]
In the current dev layout, the width of tiled layouts is unbounded, making tiles spread out to fill the whole page. This is the case in both the publications and teams page. The change that caused this is 3510de3fb1fc08d274d0ded9c9abd5643c29e756. This stems from the same thing as #848-- changes to node pages extended to all pages in general. I will make a PR that includes fixes for both.

**Comment by sagehrke** [comment]
Complete!
