### ISSUE TITLE
Clinical Synopsis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-app#871]
On this page, there is a link called "Clinical Synopsis" https://monarchinitiative.org/disease/MONDO:0017309
The link leads to an Orphanet page. I do not think it was trademarked, but most people associated Clinical Synopsis with OMIM.  The Orphanet page offers complementary information, but not just the Clinical Synopsis. I would suggest just calling the link "Orphanet" in cases like this.

**Comment by sagehrke** [comment]
Proposed solution: 
Move Orphanet linkouts to "Other Mappings" and only display OMIM linkout under "Clinical Synopsis"

https://monarchinitiative.org/MONDO:0017309
