### ISSUE TITLE
HTML injection in phenogrid tooltips (and <AppNodeBadge> more generally)

### ISSUE THREAD

**Issue by ptgolden** [monarch-initiative/monarch-app#902]
As described in https://github.com/monarch-initiative/monarch-app/issues/887#issuecomment-2479676335, there is an HTML injection bug in the phenogrid component. The offending code is here:

https://github.com/monarch-initiative/monarch-app/blob/ce0851b2193164f8c473c4515ed19e7bafbf1e5b/frontend/src/components/ThePhenogrid.vue#L183-L203

The `name` property in `<AppNodeBadge>` (which can be user generated for columns in the multicompare mode of phenogrid) is passed as raw HTML here:

https://github.com/monarch-initiative/monarch-app/blob/ce0851b2193164f8c473c4515ed19e7bafbf1e5b/frontend/src/components/AppNodeBadge.vue#L13-L27

This breaks on labels that contain strings that can be parsed as HTML tags, such as `66.45-Dsg2<tm1a(EUCOMM)Wtsi>/Dsg2<tm1a(EUCOMM)Wtsi>`, or, for script injection fun, `Group Label <script type="text/javascript">console.alert('hi')</script>`. As a rule, it is not good to render user-generated text directly as HTML. (The [Vue documentation](https://vuejs.org/api/built-in-directives.html#v-html) agrees).

This issue would also show itself if there were ever an entity in the monarch KG that had a name with some \<angled brackets\> in it.

**Comment by ptgolden** [comment]
The injection bug was introduced in c106f349c.

@kevinschaper, do you remember why you decided you needed to pass HTML rather than text? It looks like it's to support entity labels that contain HTML, like `Lama2<sup>tm1Stk</sup>/Lama2<sup>tm1Stk</sup>  [background:] involves: 129/Sv * 129P2/OlaHsd * BALB/c * ICR`. Is it the case that labels are allowed to contain any arbitrary HTML?

**Comment by kevinschaper** [comment]
Yeah, it’s for display of html in genotype names, but it really is more that we want to allow sup tags than any html.

**Comment by kevinschaper** [comment]
I’m used to there being both html and ascii representations of genotypes, and it makes sense that they kind of require the opposite setting. Right now we’re using provided genotype names that are the html version where alleles are in sup tags (example [here](http://api.monarchinitiative.org/v3/api/entity/MGI%3A5431918)), and IMPC is passing the ascii equivalent where the alleles are in angle brackets.

**Comment by ptgolden** [comment]
In that case, a safer way to do that would be to _only_ render `<sup>` tags rather than any arbitrary HTML. I wrote a component that does just that:

`<AppNodeText text="this has <sup>superscripted text</sup> contained in it and also <some> other stuff</some>" />`

renders as:

![image](https://github.com/user-attachments/assets/4bcee3a3-cc5a-49ce-acba-c4c2da4ab7de)

**Comment by ptgolden** [comment]
It's also worth noting that the phenogrid is rendered with SVG, and `<sup>` is not an SVG tag

**Comment by ptgolden** [comment]
Nice, got it working in SVG too:

![image](https://github.com/user-attachments/assets/fde62d2d-9880-400d-8663-2f446934e599)

**Comment by ptgolden** [comment]
There are a couple more places where `v-html` is used to render HTML from the KG.

These two are node names, so they can use the new `<AppNodeText>` component:

https://github.com/monarch-initiative/monarch-app/blob/ce0851b2193164f8c473c4515ed19e7bafbf1e5b/frontend/src/pages/node/SectionTitle.vue#L27-L31

https://github.com/monarch-initiative/monarch-app/blob/ce0851b2193164f8c473c4515ed19e7bafbf1e5b/frontend/src/pages/node/SectionOverview.vue#L74-L78

This one is a node's description. @kevinschaper, can you point to an example where a node description has HTML in it?

https://github.com/monarch-initiative/monarch-app/blob/ce0851b2193164f8c473c4515ed19e7bafbf1e5b/frontend/src/pages/node/SectionOverview.vue#L30-L35

**Comment by ptgolden** [comment]
Oh, I see that there are a couple thousand entities with `<i>` in their name. I'll render those tags too. Here are some examples:

```
    {
        "name":"LEW-<i>Chrna4<sup>em4Mcwi</sup></i>"},
      {
        "name":"SS.BN-(<i>D13Mgh13-D13Mit4</i>)/Mcwi"},
      {
        "name":"SS-<i>Arhgef11<sup>em4Mcwi</sup></i>"},
      {
        "name":"SS.MNS-(<i>D10Mit11-D10M11Mit119</i>)/Mco"},
      {
        "name":"ACI.FHH-(<i>D1Rat324-D1Rat156</i>)/Eur"},
      {
        "name":"WF.BBDR-(<i>D4Arb29-D4Rat96</i>)/Wor"},
      {
        "name":"LEW.BN-(<i>D10Got9-D10Rat2</i>)/Rj"},
      {
        "name":"WF.BBDR-(<i>D4Rat96-D4Rat44</i>)/Wor"},
      {
        "name":"F344.HTX-(<i>D11Rat4-D11Arb4</i>)/Hcj"},
      {
        "name":"WF.DA-(<i>D19Mit1-D19Mit6</i>)/Kop"},
      {
        "name":"LEW.BN-(<i>D10Mgh7-D10Rat221</i>)/Ciml"},
      {
        "name":"PCK-<i>Pkhd1<sup>pck</i></sup>/CrljCrl"},
      {
        "name":"DA.ACI-(<i>D15Rat6-D15Rat13</i>)/Kini"},
      {
        "name":"FHH-<i>Adra1a<sup>m1Mcwi</i></sup>"},
      {
        "name":"BN-Lcat<i><sup>m3Mcwi</i></sup>"},
      {
        "name":"SS-<i>Kcna5<sup>m1Mcwi</i></sup>"},
      {
        "name":"BN.OLETF-(<i>D1Rat169-D1Rat90</i>)/Got"},
      {
        "name":"SHRSP.WKY-<i>(D3Rat227-D3Rat1)</i>/Tkyo"},
```

**Comment by ptgolden** [comment]
There are 41 nodes that have HTML in the description. Additionally, there are two that include the text "<stereo>...</stereo>" that will be misrendered if passed as HTML

# <stereo> text that will be misrendered if rendered as HTML (2)
```
Catalysis of the reaction: <stereo>cis,trans</stereo>-4-hydroxymuconate semialdehyde + H2O + NAD+ = 2 H+ + maleylacetate + NADH.

Catalysis of the reaction: oxaloacetate = <stereo>enol</stereo>-oxaloacetate.
```

# `<i>` tags (2)
```
A rare, genetic, developmental defect during embryogenesis disorder characterized by severe, early-onset, salt-wasting adrenal insufficiency and ambiguous/female external genitalia (irrespective of chromosomal sex) due to mutations in the <i>CYP11A1</i> gene. Milder cases may present delayed onset of adrenal gland dysfunction and genitalia phenotype may range from normal male to female in individuals with 46,XY karyotype. Imaging studies reveal hypoplastic/absent adrenal glands and biochemical findings include low serum cortisol, mineralocorticoids, androgens, and sodium, with elevated potassium levels.

A rare disorder due to poisoning characterized by acute onset of potentially life-threatening illness following ingestion, inhalation, or injection of ricin, a lectin present in the seeds of <i>Ricinus communis</i>, the castor oil plant. Clinical presentation depends on the route of administration, inhalation being the most toxic route, followed by oral ingestion. Presenting signs and symptoms include nausea, vomiting, diarrhea, hematemesis, and melena (upon ingestion), cough, wheezing, dyspnea, sore throat, and congestion (upon inhalation), and erythema, induration, blisters, capillary leak syndrome, and localized necrosis (upon injection). The condition can progress to seizures, shock, organ failure, pulmonary edema, and respiratory failure.
```

# `<a>` tags (39)

```
Patch of thickened, pseudostratified epithelium that is associated with the lateral semicircular canal. It consists of regular arrays of sensory hair cells interspersed with supporting cells. The lateral crista has its own characteristic shape and polarity pattern. (See Anatomical Atlas entry for <a href='http://zfin.org/zf_info/anatomy/dict/sens/sens.html'>sensory patches of the ear</a> by T. Whitfield.)

Macula that is located in the developing anterior inner ear, and gives rise to the macula utricle. (See Anatomical Atlas entry for <a href='http://zfin.org/zf_info/anatomy/dict/sens/sens.html'>sensory patches of the ear</a> by T. Whitfield.)
```
