### ISSUE TITLE
Recent and popular node searches

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-app#95]
Currently under the node search box we have this:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/8326331/160520675-6f93ce00-3522-4919-b4a8-110f67a0a301.png">

These are our hand picked examples. It'd also be cool to have rows of "Your recent searches" and "Popular searches".

"Popular searches" would have to be supported by the backend. @falquaddoomi how much work would this be? Is there an endpoint for this already that I'm unaware of?

"Your recent searches" would be handled by the frontend. I could do it by a combination of recency and frequency, and both by what you search and what node pages you visit. E.g., if you visit "marfan syndrome" a lot, it'll show up here, even if it wasn't the last thing you searched.

I could even add a "starred" feature, both at the top of the node page and next to node search results, and have a row just for "your starred nodes". This could serve as a manual list of favorites for users, or a "look at later" list, or whatever.

**Comment by falquaddoomi** [comment]
@vincerubinetti AFAIK the backend is read-only; there isn't any persistent state stored in it. If we wanted to support storing searches, we'd have to add a database, or just store it in memory, but it's IMHO a nontrivial amount of work. Also (and this coming from prior experience on other bio database interfaces) you never know what people are going to search for, or how sensitive they consider their search history to be. It's IMHO a lot safer to just implement the "recent searches" feature with client-side data and forego the popular searches.

**Comment by vincerubinetti** [comment]
That sounds reasonable to me. Sounds like way too much work for too little value.

If we really wanted to have global popular searches, we could always once in a while just check what people are searching for the most and make those the example searches.
