### ISSUE TITLE
Write product spec sheet / design document

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#98]
Create documentation that will be used as reference in implementation and planning. What are we doing in this app, what are we not doing. How far are we going away from the current existing Monarch web app. 

Take all of the raw information gathered in the "gather research" phase, and distill/condense/consolidate all of it into a design for new Monarch Application.

Output of this should be a design document that defines project plan, scope and features included in the first release (MVP).

Write this in terms of granular, specific features and functionalities, but not particular implementation details. These should probably be thought of as specific tasks, like user stories, distilled down to a sentence. Good examples are: 

- "be able to view any returned data in tabular form and download as CSV"

There can also be another **separate** bulleted list that captures more general ideas/philosophies/approaches (like in monarch-initiative/monarch-api#115), such as:

- focus on progressive disclosure

**Comment by vincerubinetti** [comment]
Completed

[Product spec sheet](https://docs.google.com/document/d/1eawNRvU9jr7l-pCWFxhw7D6wvvBq1PTRHyPqGCAZlY0/edit) google doc
