### ISSUE TITLE
Create detailed readme

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#99]
Create detailed read me for the repository that succinctly covers the following information:

- how to install necessary dependencies (node, yarn, etc)
- how to run, test, and build the app (yarn start, build, test, etc)
- contribution guideline for how to make changes to the code. this can largely defer to the CHAI `software-guidelines` repo (still a WIP). conformance should also happen mostly automatically (eg, can't merge a pr without a review, cant merge without tests passing, lint as a test to ensure code formatting consistency, etc).

**Comment by vincerubinetti** [comment]
Done largely in monarch-initiative/monarch-ui-new#56 and we will continue to add necessary details as they come up.
